// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: companies.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const getKnownCompanyByNameNormalized = `-- name: GetKnownCompanyByNameNormalized :one

SELECT id, name_normalized, domains, created_at FROM auth.known_companies WHERE name_normalized = $1
`

// Company verification database (ADR-019 §3, migration 0007) — the
// previously-deferred Verification Model § 5 piece, built now.
// Matching happens against name_normalized (lowercased, whitespace-
// collapsed) — never the raw display name a user typed. Returns
// apperror.ErrNotFound (wrapped) for an unknown company, the MVP fallback
// case (ADR-019 §3).
func (q *Queries) GetKnownCompanyByNameNormalized(ctx context.Context, nameNormalized string) (AuthKnownCompany, error) {
	row := q.db.QueryRow(ctx, getKnownCompanyByNameNormalized, nameNormalized)
	var i AuthKnownCompany
	err := row.Scan(
		&i.ID,
		&i.NameNormalized,
		&i.Domains,
		&i.CreatedAt,
	)
	return i, err
}

const insertUnverifiedCompanyClaim = `-- name: InsertUnverifiedCompanyClaim :exec
INSERT INTO auth.unverified_company_claims (user_id, company_name_entered, domain)
VALUES ($1, $2, $3)
`

type InsertUnverifiedCompanyClaimParams struct {
	UserID             uuid.UUID `json:"user_id"`
	CompanyNameEntered string    `json:"company_name_entered"`
	Domain             string    `json:"domain"`
}

// Flags an unknown-company (name, domain) pair for the not-yet-assigned
// manual reviewer (ADR-019 §3) — no reviewer UI in this slice, just the
// queue.
func (q *Queries) InsertUnverifiedCompanyClaim(ctx context.Context, arg InsertUnverifiedCompanyClaimParams) error {
	_, err := q.db.Exec(ctx, insertUnverifiedCompanyClaim, arg.UserID, arg.CompanyNameEntered, arg.Domain)
	return err
}
