// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthAccountStatus string

const (
	AuthAccountStatusActive      AuthAccountStatus = "active"
	AuthAccountStatusDeactivated AuthAccountStatus = "deactivated"
	AuthAccountStatusDeleted     AuthAccountStatus = "deleted"
)

func (e *AuthAccountStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthAccountStatus(s)
	case string:
		*e = AuthAccountStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthAccountStatus: %T", src)
	}
	return nil
}

type NullAuthAccountStatus struct {
	AuthAccountStatus AuthAccountStatus `json:"auth_account_status"`
	Valid             bool              `json:"valid"` // Valid is true if AuthAccountStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthAccountStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AuthAccountStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthAccountStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthAccountStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthAccountStatus), nil
}

type AuthIdentityProvider string

const (
	AuthIdentityProviderApple  AuthIdentityProvider = "apple"
	AuthIdentityProviderGoogle AuthIdentityProvider = "google"
)

func (e *AuthIdentityProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthIdentityProvider(s)
	case string:
		*e = AuthIdentityProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthIdentityProvider: %T", src)
	}
	return nil
}

type NullAuthIdentityProvider struct {
	AuthIdentityProvider AuthIdentityProvider `json:"auth_identity_provider"`
	Valid                bool                 `json:"valid"` // Valid is true if AuthIdentityProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthIdentityProvider) Scan(value interface{}) error {
	if value == nil {
		ns.AuthIdentityProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthIdentityProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthIdentityProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthIdentityProvider), nil
}

type AuthVerificationPurpose string

const (
	AuthVerificationPurposePhone          AuthVerificationPurpose = "phone"
	AuthVerificationPurposePersonalEmail  AuthVerificationPurpose = "personal_email"
	AuthVerificationPurposeCorporateEmail AuthVerificationPurpose = "corporate_email"
	AuthVerificationPurposeEmailSignup    AuthVerificationPurpose = "email_signup"
	AuthVerificationPurposeEmailLogin     AuthVerificationPurpose = "email_login"
)

func (e *AuthVerificationPurpose) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthVerificationPurpose(s)
	case string:
		*e = AuthVerificationPurpose(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthVerificationPurpose: %T", src)
	}
	return nil
}

type NullAuthVerificationPurpose struct {
	AuthVerificationPurpose AuthVerificationPurpose `json:"auth_verification_purpose"`
	Valid                   bool                    `json:"valid"` // Valid is true if AuthVerificationPurpose is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthVerificationPurpose) Scan(value interface{}) error {
	if value == nil {
		ns.AuthVerificationPurpose, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthVerificationPurpose.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthVerificationPurpose) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthVerificationPurpose), nil
}

type AuthKnownCompany struct {
	ID             uuid.UUID          `json:"id"`
	NameNormalized string             `json:"name_normalized"`
	Domains        []string           `json:"domains"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type AuthRefreshToken struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	IssuedAt   pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	ReplacedBy pgtype.UUID        `json:"replaced_by"`
}

type AuthSosEvent struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	ContextMessage   pgtype.Text        `json:"context_message"`
	Latitude         float64            `json:"latitude"`
	Longitude        float64            `json:"longitude"`
	TriggeredAt      pgtype.Timestamptz `json:"triggered_at"`
	ContactsNotified int32              `json:"contacts_notified"`
}

type AuthTrustedContact struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	Name        string             `json:"name"`
	PhoneNumber pgtype.Text        `json:"phone_number"`
	Email       pgtype.Text        `json:"email"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type AuthUnverifiedCompanyClaim struct {
	ID                 uuid.UUID          `json:"id"`
	UserID             uuid.UUID          `json:"user_id"`
	CompanyNameEntered string             `json:"company_name_entered"`
	Domain             string             `json:"domain"`
	FlaggedAt          pgtype.Timestamptz `json:"flagged_at"`
}

type AuthUser struct {
	ID                    uuid.UUID          `json:"id"`
	LinkedinSub           pgtype.Text        `json:"linkedin_sub"`
	FullName              string             `json:"full_name"`
	ProfilePhotoUrl       pgtype.Text        `json:"profile_photo_url"`
	Headline              pgtype.Text        `json:"headline"`
	TrustLevel            int16              `json:"trust_level"`
	AccountStatus         AuthAccountStatus  `json:"account_status"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	PhoneNumber           pgtype.Text        `json:"phone_number"`
	PersonalEmail         pgtype.Text        `json:"personal_email"`
	LegalName             pgtype.Text        `json:"legal_name"`
	Address               pgtype.Text        `json:"address"`
	CompanyDomain         pgtype.Text        `json:"company_domain"`
	WorkEmailVerified     bool               `json:"work_email_verified"`
	WorkEmailVerifiedAt   pgtype.Timestamptz `json:"work_email_verified_at"`
	AgeConfirmedOver18    bool               `json:"age_confirmed_over_18"`
	AgeConfirmedAt        pgtype.Timestamptz `json:"age_confirmed_at"`
	WorkEmailHash         pgtype.Text        `json:"work_email_hash"`
	RatingAverage         pgtype.Numeric     `json:"rating_average"`
	RatingCount           int32              `json:"rating_count"`
	RatingUpdatedAt       pgtype.Timestamptz `json:"rating_updated_at"`
	LastLocationLat       pgtype.Float8      `json:"last_location_lat"`
	LastLocationLng       pgtype.Float8      `json:"last_location_lng"`
	LastLocationUpdatedAt pgtype.Timestamptz `json:"last_location_updated_at"`
}

type AuthUserIdentity struct {
	ID       uuid.UUID            `json:"id"`
	UserID   uuid.UUID            `json:"user_id"`
	Provider AuthIdentityProvider `json:"provider"`
	Subject  string               `json:"subject"`
	Email    pgtype.Text          `json:"email"`
	LinkedAt pgtype.Timestamptz   `json:"linked_at"`
}

type AuthVerificationCode struct {
	ID        uuid.UUID               `json:"id"`
	UserID    pgtype.UUID             `json:"user_id"`
	Purpose   AuthVerificationPurpose `json:"purpose"`
	Target    string                  `json:"target"`
	CodeHash  string                  `json:"code_hash"`
	Attempts  int16                   `json:"attempts"`
	ExpiresAt pgtype.Timestamptz      `json:"expires_at"`
	CreatedAt pgtype.Timestamptz      `json:"created_at"`
}
