// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Backs the soft cap of 3 per user (ADR-026 §1), enforced at the service
	// layer, not a DB constraint.
	CountTrustedContactsForUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (AuthRefreshToken, error)
	// age_confirmed_at is set to now() only when age_confirmed_over_18 is true
	// (the only case CreateUser is ever called with, in practice — the service
	// layer rejects false before reaching here) — never backdated, never set
	// for a false confirmation.
	CreateUser(ctx context.Context, arg CreateUserParams) (AuthUser, error)
	// Scoped to (id, user_id) so a caller can never delete another user's
	// contact by guessing an id — the service layer additionally checks
	// ownership explicitly first (same "no row for this caller -> Forbidden"
	// pattern ratings.go/safety.go already established) rather than relying on
	// this WHERE clause alone to produce the right error shape.
	DeleteTrustedContact(ctx context.Context, arg DeleteTrustedContactParams) (int64, error)
	DeleteVerificationCode(ctx context.Context, arg DeleteVerificationCodeParams) error
	DeleteVerificationCodeByTarget(ctx context.Context, arg DeleteVerificationCodeByTargetParams) error
	GetIdentityByProviderSubject(ctx context.Context, arg GetIdentityByProviderSubjectParams) (AuthUserIdentity, error)
	// Company verification database (ADR-019 §3, migration 0007) — the
	// previously-deferred Verification Model § 5 piece, built now.
	// Matching happens against name_normalized (lowercased, whitespace-
	// collapsed) — never the raw display name a user typed. Returns
	// apperror.ErrNotFound (wrapped) for an unknown company, the MVP fallback
	// case (ADR-019 §3).
	GetKnownCompanyByNameNormalized(ctx context.Context, nameNormalized string) (AuthKnownCompany, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (AuthRefreshToken, error)
	GetRefreshTokenByID(ctx context.Context, id uuid.UUID) (AuthRefreshToken, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (AuthUser, error)
	GetUserByLinkedInSub(ctx context.Context, linkedinSub pgtype.Text) (AuthUser, error)
	// personal_email's mere presence already means "verified" in this schema
	// (same "presence IS the signal" convention as linkedin_sub/phone_number —
	// it's only ever written via UpdateUserPersonalEmail, which only runs
	// after a successful OTP check) — no separate boolean to check here.
	// Used by SignUpOrRecoverWithEmail (ADR-014 decision #3, passwordless as
	// of ADR-019 §1) to detect the recovery case: an email-OTP signup against
	// an address that's already someone's verified personal_email.
	GetUserByPersonalEmail(ctx context.Context, personalEmail pgtype.Text) (AuthUser, error)
	// Reuse-abuse check (ADR-019 §3) — called before committing a corporate-
	// email verification to detect whether this exact mailbox already
	// verified a DIFFERENT account. Returns apperror.ErrNotFound (wrapped) if
	// no user has this hash yet.
	GetUserByWorkEmailHash(ctx context.Context, workEmailHash pgtype.Text) (AuthUser, error)
	GetVerificationCode(ctx context.Context, arg GetVerificationCodeParams) (AuthVerificationCode, error)
	GetVerificationCodeByTarget(ctx context.Context, arg GetVerificationCodeByTargetParams) (AuthVerificationCode, error)
	IncrementVerificationAttempts(ctx context.Context, arg IncrementVerificationAttemptsParams) (AuthVerificationCode, error)
	IncrementVerificationAttemptsByTarget(ctx context.Context, arg IncrementVerificationAttemptsByTargetParams) (AuthVerificationCode, error)
	InsertIdentity(ctx context.Context, arg InsertIdentityParams) (AuthUserIdentity, error)
	InsertSOSEvent(ctx context.Context, arg InsertSOSEventParams) error
	// Minimal real SOS + trusted contacts (ADR-026, Slice H).
	InsertTrustedContact(ctx context.Context, arg InsertTrustedContactParams) (AuthTrustedContact, error)
	// Flags an unknown-company (name, domain) pair for the not-yet-assigned
	// manual reviewer (ADR-019 §3) — no reviewer UI in this slice, just the
	// queue.
	InsertUnverifiedCompanyClaim(ctx context.Context, arg InsertUnverifiedCompanyClaimParams) error
	ListIdentitiesForUser(ctx context.Context, userID uuid.UUID) ([]AuthUserIdentity, error)
	ListTrustedContactsForUser(ctx context.Context, userID uuid.UUID) ([]AuthTrustedContact, error)
	MarkRefreshTokenReplaced(ctx context.Context, arg MarkRefreshTokenReplacedParams) error
	RevokeRefreshTokenByHash(ctx context.Context, tokenHash string) error
	// ADR-019 §2's post-auth profile-completion screen — CompleteProfileSetup
	// is the only caller. fullName is always required there, unlike every
	// other field on this table.
	UpdateUserFullName(ctx context.Context, arg UpdateUserFullNameParams) (AuthUser, error)
	// 40km geo-visibility (ADR-021 §4) — the browse screen's on-demand
	// location read is the only call site for this; no trust-level bump, no
	// other side effect. Plain unconditional UPDATE, not order-guarded: unlike
	// the event-consumer upserts elsewhere, this is a direct RPC write from the
	// same user's own device in request order, not a redelivered/out-of-order
	// Pub/Sub message.
	UpdateUserLastKnownLocation(ctx context.Context, arg UpdateUserLastKnownLocationParams) (AuthUser, error)
	// The LinkedIn branch of LinkIdentityToUser (ADR-014) — links LinkedIn to
	// an already-authenticated Level 0+ account (Profile's "Connect LinkedIn").
	// Direct LinkedIn signup (CompleteLinkedInOnboarding, unchanged by this
	// slice) still creates accounts via CreateUser directly; this query is
	// only for the linking-to-an-existing-account path. The partial unique
	// index idx_users_linkedin_sub (migration 0001) is what actually rejects
	// linking a LinkedIn subject already claimed by a different user — the
	// caller (internal/service) maps that 23505 into apperror.ErrConflict,
	// same pattern as UpdateUserPhoneNumber/UpdateUserPersonalEmail below.
	UpdateUserLinkedInSub(ctx context.Context, arg UpdateUserLinkedInSubParams) (AuthUser, error)
	UpdateUserPersonalDetails(ctx context.Context, arg UpdateUserPersonalDetailsParams) (AuthUser, error)
	UpdateUserPersonalEmail(ctx context.Context, arg UpdateUserPersonalEmailParams) (AuthUser, error)
	// Level 2/3 verification (ADR-012, backend/PLAN.md's matching addendum).
	// Each mutation also writes trust_level in the same statement — the caller
	// (internal/service) computes the new value via computeTrustLevel before
	// calling these, so the row is never left with a stale trust_level between
	// the field write and a separate recompute step.
	UpdateUserPhoneNumber(ctx context.Context, arg UpdateUserPhoneNumberParams) (AuthUser, error)
	// work_email_hash is set alongside company_domain/work_email_verified
	// (ADR-019 §3) — a keyed HMAC of the normalized raw address, the reuse-
	// abuse check's UNIQUE anchor (GetUserByWorkEmailHash below is what
	// detects a collision BEFORE this runs; the UNIQUE constraint here is the
	// last-resort race guard, same pattern as phone_number/personal_email).
	UpdateUserWorkEmailVerified(ctx context.Context, arg UpdateUserWorkEmailVerifiedParams) (AuthUser, error)
	// The rating-updated consumer's idempotent, order-guarded upsert (ADR-018
	// Decision 2, ADR-017's addendum Step 5b) — users.rating_average/
	// rating_count are a read-only cache of what services/meetup owns as of
	// this migration, written only from here. The WHERE clause is the
	// ordering guard: applies unconditionally the first time (rating_updated_at
	// still NULL from auth/0004's ALTER TABLE default), otherwise only if this
	// event is strictly newer than whatever's already stored — an
	// out-of-order redelivery of an older event is a no-op, not a regression.
	// Rows affected (0 or 1) tells the caller whether the guard actually
	// skipped a stale event, purely for logging.
	UpsertUserRatingCache(ctx context.Context, arg UpsertUserRatingCacheParams) (int64, error)
	// One pending code per (user_id, purpose) — a resend overwrites the
	// existing row (including resetting attempts and created_at) rather than
	// stacking a second one.
	UpsertVerificationCode(ctx context.Context, arg UpsertVerificationCodeParams) (AuthVerificationCode, error)
	// Email-OTP signup (ADR-014 decision #2, migration 0004; passwordless as
	// of ADR-019 §1) — the account may not exist yet at OTP-send time (see
	// SignUpOrRecoverWithEmail's recovery path), so these four mirror the
	// four above exactly except keyed by (purpose, target) instead of
	// (user_id, purpose), via idx_verification_codes_signup_target. Used for
	// both VERIFICATION_PURPOSE_EMAIL_SIGNUP and VERIFICATION_PURPOSE_EMAIL_LOGIN
	// (migration 0006, ADR-019 §1) — user_id is always NULL on these rows.
	UpsertVerificationCodeForSignup(ctx context.Context, arg UpsertVerificationCodeForSignupParams) (AuthVerificationCode, error)
}

var _ Querier = (*Queries)(nil)
