// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sos.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countTrustedContactsForUser = `-- name: CountTrustedContactsForUser :one
SELECT count(*) FROM auth.trusted_contacts WHERE user_id = $1
`

// Backs the soft cap of 3 per user (ADR-026 §1), enforced at the service
// layer, not a DB constraint.
func (q *Queries) CountTrustedContactsForUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTrustedContactsForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteTrustedContact = `-- name: DeleteTrustedContact :execrows
DELETE FROM auth.trusted_contacts WHERE id = $1 AND user_id = $2
`

type DeleteTrustedContactParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

// Scoped to (id, user_id) so a caller can never delete another user's
// contact by guessing an id — the service layer additionally checks
// ownership explicitly first (same "no row for this caller -> Forbidden"
// pattern ratings.go/safety.go already established) rather than relying on
// this WHERE clause alone to produce the right error shape.
func (q *Queries) DeleteTrustedContact(ctx context.Context, arg DeleteTrustedContactParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTrustedContact, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertSOSEvent = `-- name: InsertSOSEvent :exec
INSERT INTO auth.sos_events (user_id, context_message, latitude, longitude, contacts_notified)
VALUES ($1, $2, $3, $4, $5)
`

type InsertSOSEventParams struct {
	UserID           uuid.UUID   `json:"user_id"`
	ContextMessage   pgtype.Text `json:"context_message"`
	Latitude         float64     `json:"latitude"`
	Longitude        float64     `json:"longitude"`
	ContactsNotified int32       `json:"contacts_notified"`
}

func (q *Queries) InsertSOSEvent(ctx context.Context, arg InsertSOSEventParams) error {
	_, err := q.db.Exec(ctx, insertSOSEvent,
		arg.UserID,
		arg.ContextMessage,
		arg.Latitude,
		arg.Longitude,
		arg.ContactsNotified,
	)
	return err
}

const insertTrustedContact = `-- name: InsertTrustedContact :one

INSERT INTO auth.trusted_contacts (user_id, name, phone_number, email)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, phone_number, email, created_at, updated_at
`

type InsertTrustedContactParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	Name        string      `json:"name"`
	PhoneNumber pgtype.Text `json:"phone_number"`
	Email       pgtype.Text `json:"email"`
}

// Minimal real SOS + trusted contacts (ADR-026, Slice H).
func (q *Queries) InsertTrustedContact(ctx context.Context, arg InsertTrustedContactParams) (AuthTrustedContact, error) {
	row := q.db.QueryRow(ctx, insertTrustedContact,
		arg.UserID,
		arg.Name,
		arg.PhoneNumber,
		arg.Email,
	)
	var i AuthTrustedContact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.PhoneNumber,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTrustedContactsForUser = `-- name: ListTrustedContactsForUser :many
SELECT id, user_id, name, phone_number, email, created_at, updated_at FROM auth.trusted_contacts WHERE user_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListTrustedContactsForUser(ctx context.Context, userID uuid.UUID) ([]AuthTrustedContact, error) {
	rows, err := q.db.Query(ctx, listTrustedContactsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthTrustedContact
	for rows.Next() {
		var i AuthTrustedContact
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.PhoneNumber,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
