// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO auth.users (linkedin_sub, full_name, profile_photo_url, headline, trust_level, age_confirmed_over_18, age_confirmed_at)
VALUES ($1, $2, $3, $4, $5, $6, CASE WHEN $6 THEN now() ELSE NULL END)
RETURNING id, linkedin_sub, full_name, profile_photo_url, headline, trust_level, account_status, created_at, updated_at, phone_number, personal_email, legal_name, address, company_domain, work_email_verified, work_email_verified_at, age_confirmed_over_18, age_confirmed_at, work_email_hash, rating_average, rating_count, rating_updated_at, last_location_lat, last_location_lng, last_location_updated_at
`

type CreateUserParams struct {
	LinkedinSub        pgtype.Text `json:"linkedin_sub"`
	FullName           string      `json:"full_name"`
	ProfilePhotoUrl    pgtype.Text `json:"profile_photo_url"`
	Headline           pgtype.Text `json:"headline"`
	TrustLevel         int16       `json:"trust_level"`
	AgeConfirmedOver18 bool        `json:"age_confirmed_over_18"`
}

// age_confirmed_at is set to now() only when age_confirmed_over_18 is true
// (the only case CreateUser is ever called with, in practice — the service
// layer rejects false before reaching here) — never backdated, never set
// for a false confirmation.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (AuthUser, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.LinkedinSub,
		arg.FullName,
		arg.ProfilePhotoUrl,
		arg.Headline,
		arg.TrustLevel,
		arg.AgeConfirmedOver18,
	)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.LinkedinSub,
		&i.FullName,
		&i.ProfilePhotoUrl,
		&i.Headline,
		&i.TrustLevel,
		&i.AccountStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhoneNumber,
		&i.PersonalEmail,
		&i.LegalName,
		&i.Address,
		&i.CompanyDomain,
		&i.WorkEmailVerified,
		&i.WorkEmailVerifiedAt,
		&i.AgeConfirmedOver18,
		&i.AgeConfirmedAt,
		&i.WorkEmailHash,
		&i.RatingAverage,
		&i.RatingCount,
		&i.RatingUpdatedAt,
		&i.LastLocationLat,
		&i.LastLocationLng,
		&i.LastLocationUpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, linkedin_sub, full_name, profile_photo_url, headline, trust_level, account_status, created_at, updated_at, phone_number, personal_email, legal_name, address, company_domain, work_email_verified, work_email_verified_at, age_confirmed_over_18, age_confirmed_at, work_email_hash, rating_average, rating_count, rating_updated_at, last_location_lat, last_location_lng, last_location_updated_at FROM auth.users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.LinkedinSub,
		&i.FullName,
		&i.ProfilePhotoUrl,
		&i.Headline,
		&i.TrustLevel,
		&i.AccountStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhoneNumber,
		&i.PersonalEmail,
		&i.LegalName,
		&i.Address,
		&i.CompanyDomain,
		&i.WorkEmailVerified,
		&i.WorkEmailVerifiedAt,
		&i.AgeConfirmedOver18,
		&i.AgeConfirmedAt,
		&i.WorkEmailHash,
		&i.RatingAverage,
		&i.RatingCount,
		&i.RatingUpdatedAt,
		&i.LastLocationLat,
		&i.LastLocationLng,
		&i.LastLocationUpdatedAt,
	)
	return i, err
}

const getUserByLinkedInSub = `-- name: GetUserByLinkedInSub :one
SELECT id, linkedin_sub, full_name, profile_photo_url, headline, trust_level, account_status, created_at, updated_at, phone_number, personal_email, legal_name, address, company_domain, work_email_verified, work_email_verified_at, age_confirmed_over_18, age_confirmed_at, work_email_hash, rating_average, rating_count, rating_updated_at, last_location_lat, last_location_lng, last_location_updated_at FROM auth.users WHERE linkedin_sub = $1
`

func (q *Queries) GetUserByLinkedInSub(ctx context.Context, linkedinSub pgtype.Text) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getUserByLinkedInSub, linkedinSub)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.LinkedinSub,
		&i.FullName,
		&i.ProfilePhotoUrl,
		&i.Headline,
		&i.TrustLevel,
		&i.AccountStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhoneNumber,
		&i.PersonalEmail,
		&i.LegalName,
		&i.Address,
		&i.CompanyDomain,
		&i.WorkEmailVerified,
		&i.WorkEmailVerifiedAt,
		&i.AgeConfirmedOver18,
		&i.AgeConfirmedAt,
		&i.WorkEmailHash,
		&i.RatingAverage,
		&i.RatingCount,
		&i.RatingUpdatedAt,
		&i.LastLocationLat,
		&i.LastLocationLng,
		&i.LastLocationUpdatedAt,
	)
	return i, err
}

const getUserByPersonalEmail = `-- name: GetUserByPersonalEmail :one
SELECT id, linkedin_sub, full_name, profile_photo_url, headline, trust_level, account_status, created_at, updated_at, phone_number, personal_email, legal_name, address, company_domain, work_email_verified, work_email_verified_at, age_confirmed_over_18, age_confirmed_at, work_email_hash, rating_average, rating_count, rating_updated_at, last_location_lat, last_location_lng, last_location_updated_at FROM auth.users WHERE personal_email = $1
`

// personal_email's mere presence already means "verified" in this schema
// (same "presence IS the signal" convention as linkedin_sub/phone_number —
// it's only ever written via UpdateUserPersonalEmail, which only runs
// after a successful OTP check) — no separate boolean to check here.
// Used by SignUpOrRecoverWithEmail (ADR-014 decision #3, passwordless as
// of ADR-019 §1) to detect the recovery case: an email-OTP signup against
// an address that's already someone's verified personal_email.
func (q *Queries) GetUserByPersonalEmail(ctx context.Context, personalEmail pgtype.Text) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getUserByPersonalEmail, personalEmail)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.LinkedinSub,
		&i.FullName,
		&i.ProfilePhotoUrl,
		&i.Headline,
		&i.TrustLevel,
		&i.AccountStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhoneNumber,
		&i.PersonalEmail,
		&i.LegalName,
		&i.Address,
		&i.CompanyDomain,
		&i.WorkEmailVerified,
		&i.WorkEmailVerifiedAt,
		&i.AgeConfirmedOver18,
		&i.AgeConfirmedAt,
		&i.WorkEmailHash,
		&i.RatingAverage,
		&i.RatingCount,
		&i.RatingUpdatedAt,
		&i.LastLocationLat,
		&i.LastLocationLng,
		&i.LastLocationUpdatedAt,
	)
	return i, err
}

const getUserByWorkEmailHash = `-- name: GetUserByWorkEmailHash :one
SELECT id, linkedin_sub, full_name, profile_photo_url, headline, trust_level, account_status, created_at, updated_at, phone_number, personal_email, legal_name, address, company_domain, work_email_verified, work_email_verified_at, age_confirmed_over_18, age_confirmed_at, work_email_hash, rating_average, rating_count, rating_updated_at, last_location_lat, last_location_lng, last_location_updated_at FROM auth.users WHERE work_email_hash = $1
`

// Reuse-abuse check (ADR-019 §3) — called before committing a corporate-
// email verification to detect whether this exact mailbox already
// verified a DIFFERENT account. Returns apperror.ErrNotFound (wrapped) if
// no user has this hash yet.
func (q *Queries) GetUserByWorkEmailHash(ctx context.Context, workEmailHash pgtype.Text) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getUserByWorkEmailHash, workEmailHash)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.LinkedinSub,
		&i.FullName,
		&i.ProfilePhotoUrl,
		&i.Headline,
		&i.TrustLevel,
		&i.AccountStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhoneNumber,
		&i.PersonalEmail,
		&i.LegalName,
		&i.Address,
		&i.CompanyDomain,
		&i.WorkEmailVerified,
		&i.WorkEmailVerifiedAt,
		&i.AgeConfirmedOver18,
		&i.AgeConfirmedAt,
		&i.WorkEmailHash,
		&i.RatingAverage,
		&i.RatingCount,
		&i.RatingUpdatedAt,
		&i.LastLocationLat,
		&i.LastLocationLng,
		&i.LastLocationUpdatedAt,
	)
	return i, err
}

const updateUserFullName = `-- name: UpdateUserFullName :one
UPDATE auth.users SET full_name = $2 WHERE id = $1 RETURNING id, linkedin_sub, full_name, profile_photo_url, headline, trust_level, account_status, created_at, updated_at, phone_number, personal_email, legal_name, address, company_domain, work_email_verified, work_email_verified_at, age_confirmed_over_18, age_confirmed_at, work_email_hash, rating_average, rating_count, rating_updated_at, last_location_lat, last_location_lng, last_location_updated_at
`

type UpdateUserFullNameParams struct {
	ID       uuid.UUID `json:"id"`
	FullName string    `json:"full_name"`
}

// ADR-019 §2's post-auth profile-completion screen — CompleteProfileSetup
// is the only caller. fullName is always required there, unlike every
// other field on this table.
func (q *Queries) UpdateUserFullName(ctx context.Context, arg UpdateUserFullNameParams) (AuthUser, error) {
	row := q.db.QueryRow(ctx, updateUserFullName, arg.ID, arg.FullName)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.LinkedinSub,
		&i.FullName,
		&i.ProfilePhotoUrl,
		&i.Headline,
		&i.TrustLevel,
		&i.AccountStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhoneNumber,
		&i.PersonalEmail,
		&i.LegalName,
		&i.Address,
		&i.CompanyDomain,
		&i.WorkEmailVerified,
		&i.WorkEmailVerifiedAt,
		&i.AgeConfirmedOver18,
		&i.AgeConfirmedAt,
		&i.WorkEmailHash,
		&i.RatingAverage,
		&i.RatingCount,
		&i.RatingUpdatedAt,
		&i.LastLocationLat,
		&i.LastLocationLng,
		&i.LastLocationUpdatedAt,
	)
	return i, err
}

const updateUserLastKnownLocation = `-- name: UpdateUserLastKnownLocation :one
UPDATE auth.users SET last_location_lat = $2, last_location_lng = $3, last_location_updated_at = now()
WHERE id = $1 RETURNING id, linkedin_sub, full_name, profile_photo_url, headline, trust_level, account_status, created_at, updated_at, phone_number, personal_email, legal_name, address, company_domain, work_email_verified, work_email_verified_at, age_confirmed_over_18, age_confirmed_at, work_email_hash, rating_average, rating_count, rating_updated_at, last_location_lat, last_location_lng, last_location_updated_at
`

type UpdateUserLastKnownLocationParams struct {
	ID              uuid.UUID     `json:"id"`
	LastLocationLat pgtype.Float8 `json:"last_location_lat"`
	LastLocationLng pgtype.Float8 `json:"last_location_lng"`
}

// 40km geo-visibility (ADR-021 §4) — the browse screen's on-demand
// location read is the only call site for this; no trust-level bump, no
// other side effect. Plain unconditional UPDATE, not order-guarded: unlike
// the event-consumer upserts elsewhere, this is a direct RPC write from the
// same user's own device in request order, not a redelivered/out-of-order
// Pub/Sub message.
func (q *Queries) UpdateUserLastKnownLocation(ctx context.Context, arg UpdateUserLastKnownLocationParams) (AuthUser, error) {
	row := q.db.QueryRow(ctx, updateUserLastKnownLocation, arg.ID, arg.LastLocationLat, arg.LastLocationLng)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.LinkedinSub,
		&i.FullName,
		&i.ProfilePhotoUrl,
		&i.Headline,
		&i.TrustLevel,
		&i.AccountStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhoneNumber,
		&i.PersonalEmail,
		&i.LegalName,
		&i.Address,
		&i.CompanyDomain,
		&i.WorkEmailVerified,
		&i.WorkEmailVerifiedAt,
		&i.AgeConfirmedOver18,
		&i.AgeConfirmedAt,
		&i.WorkEmailHash,
		&i.RatingAverage,
		&i.RatingCount,
		&i.RatingUpdatedAt,
		&i.LastLocationLat,
		&i.LastLocationLng,
		&i.LastLocationUpdatedAt,
	)
	return i, err
}

const updateUserLinkedInSub = `-- name: UpdateUserLinkedInSub :one
UPDATE auth.users SET linkedin_sub = $2, trust_level = $3 WHERE id = $1 RETURNING id, linkedin_sub, full_name, profile_photo_url, headline, trust_level, account_status, created_at, updated_at, phone_number, personal_email, legal_name, address, company_domain, work_email_verified, work_email_verified_at, age_confirmed_over_18, age_confirmed_at, work_email_hash, rating_average, rating_count, rating_updated_at, last_location_lat, last_location_lng, last_location_updated_at
`

type UpdateUserLinkedInSubParams struct {
	ID          uuid.UUID   `json:"id"`
	LinkedinSub pgtype.Text `json:"linkedin_sub"`
	TrustLevel  int16       `json:"trust_level"`
}

// The LinkedIn branch of LinkIdentityToUser (ADR-014) — links LinkedIn to
// an already-authenticated Level 0+ account (Profile's "Connect LinkedIn").
// Direct LinkedIn signup (CompleteLinkedInOnboarding, unchanged by this
// slice) still creates accounts via CreateUser directly; this query is
// only for the linking-to-an-existing-account path. The partial unique
// index idx_users_linkedin_sub (migration 0001) is what actually rejects
// linking a LinkedIn subject already claimed by a different user — the
// caller (internal/service) maps that 23505 into apperror.ErrConflict,
// same pattern as UpdateUserPhoneNumber/UpdateUserPersonalEmail below.
func (q *Queries) UpdateUserLinkedInSub(ctx context.Context, arg UpdateUserLinkedInSubParams) (AuthUser, error) {
	row := q.db.QueryRow(ctx, updateUserLinkedInSub, arg.ID, arg.LinkedinSub, arg.TrustLevel)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.LinkedinSub,
		&i.FullName,
		&i.ProfilePhotoUrl,
		&i.Headline,
		&i.TrustLevel,
		&i.AccountStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhoneNumber,
		&i.PersonalEmail,
		&i.LegalName,
		&i.Address,
		&i.CompanyDomain,
		&i.WorkEmailVerified,
		&i.WorkEmailVerifiedAt,
		&i.AgeConfirmedOver18,
		&i.AgeConfirmedAt,
		&i.WorkEmailHash,
		&i.RatingAverage,
		&i.RatingCount,
		&i.RatingUpdatedAt,
		&i.LastLocationLat,
		&i.LastLocationLng,
		&i.LastLocationUpdatedAt,
	)
	return i, err
}

const updateUserPersonalDetails = `-- name: UpdateUserPersonalDetails :one
UPDATE auth.users SET legal_name = $2, address = $3, trust_level = $4 WHERE id = $1 RETURNING id, linkedin_sub, full_name, profile_photo_url, headline, trust_level, account_status, created_at, updated_at, phone_number, personal_email, legal_name, address, company_domain, work_email_verified, work_email_verified_at, age_confirmed_over_18, age_confirmed_at, work_email_hash, rating_average, rating_count, rating_updated_at, last_location_lat, last_location_lng, last_location_updated_at
`

type UpdateUserPersonalDetailsParams struct {
	ID         uuid.UUID   `json:"id"`
	LegalName  pgtype.Text `json:"legal_name"`
	Address    pgtype.Text `json:"address"`
	TrustLevel int16       `json:"trust_level"`
}

func (q *Queries) UpdateUserPersonalDetails(ctx context.Context, arg UpdateUserPersonalDetailsParams) (AuthUser, error) {
	row := q.db.QueryRow(ctx, updateUserPersonalDetails,
		arg.ID,
		arg.LegalName,
		arg.Address,
		arg.TrustLevel,
	)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.LinkedinSub,
		&i.FullName,
		&i.ProfilePhotoUrl,
		&i.Headline,
		&i.TrustLevel,
		&i.AccountStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhoneNumber,
		&i.PersonalEmail,
		&i.LegalName,
		&i.Address,
		&i.CompanyDomain,
		&i.WorkEmailVerified,
		&i.WorkEmailVerifiedAt,
		&i.AgeConfirmedOver18,
		&i.AgeConfirmedAt,
		&i.WorkEmailHash,
		&i.RatingAverage,
		&i.RatingCount,
		&i.RatingUpdatedAt,
		&i.LastLocationLat,
		&i.LastLocationLng,
		&i.LastLocationUpdatedAt,
	)
	return i, err
}

const updateUserPersonalEmail = `-- name: UpdateUserPersonalEmail :one
UPDATE auth.users SET personal_email = $2, trust_level = $3 WHERE id = $1 RETURNING id, linkedin_sub, full_name, profile_photo_url, headline, trust_level, account_status, created_at, updated_at, phone_number, personal_email, legal_name, address, company_domain, work_email_verified, work_email_verified_at, age_confirmed_over_18, age_confirmed_at, work_email_hash, rating_average, rating_count, rating_updated_at, last_location_lat, last_location_lng, last_location_updated_at
`

type UpdateUserPersonalEmailParams struct {
	ID            uuid.UUID   `json:"id"`
	PersonalEmail pgtype.Text `json:"personal_email"`
	TrustLevel    int16       `json:"trust_level"`
}

func (q *Queries) UpdateUserPersonalEmail(ctx context.Context, arg UpdateUserPersonalEmailParams) (AuthUser, error) {
	row := q.db.QueryRow(ctx, updateUserPersonalEmail, arg.ID, arg.PersonalEmail, arg.TrustLevel)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.LinkedinSub,
		&i.FullName,
		&i.ProfilePhotoUrl,
		&i.Headline,
		&i.TrustLevel,
		&i.AccountStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhoneNumber,
		&i.PersonalEmail,
		&i.LegalName,
		&i.Address,
		&i.CompanyDomain,
		&i.WorkEmailVerified,
		&i.WorkEmailVerifiedAt,
		&i.AgeConfirmedOver18,
		&i.AgeConfirmedAt,
		&i.WorkEmailHash,
		&i.RatingAverage,
		&i.RatingCount,
		&i.RatingUpdatedAt,
		&i.LastLocationLat,
		&i.LastLocationLng,
		&i.LastLocationUpdatedAt,
	)
	return i, err
}

const updateUserPhoneNumber = `-- name: UpdateUserPhoneNumber :one

UPDATE auth.users SET phone_number = $2, trust_level = $3 WHERE id = $1 RETURNING id, linkedin_sub, full_name, profile_photo_url, headline, trust_level, account_status, created_at, updated_at, phone_number, personal_email, legal_name, address, company_domain, work_email_verified, work_email_verified_at, age_confirmed_over_18, age_confirmed_at, work_email_hash, rating_average, rating_count, rating_updated_at, last_location_lat, last_location_lng, last_location_updated_at
`

type UpdateUserPhoneNumberParams struct {
	ID          uuid.UUID   `json:"id"`
	PhoneNumber pgtype.Text `json:"phone_number"`
	TrustLevel  int16       `json:"trust_level"`
}

// Level 2/3 verification (ADR-012, backend/PLAN.md's matching addendum).
// Each mutation also writes trust_level in the same statement — the caller
// (internal/service) computes the new value via computeTrustLevel before
// calling these, so the row is never left with a stale trust_level between
// the field write and a separate recompute step.
func (q *Queries) UpdateUserPhoneNumber(ctx context.Context, arg UpdateUserPhoneNumberParams) (AuthUser, error) {
	row := q.db.QueryRow(ctx, updateUserPhoneNumber, arg.ID, arg.PhoneNumber, arg.TrustLevel)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.LinkedinSub,
		&i.FullName,
		&i.ProfilePhotoUrl,
		&i.Headline,
		&i.TrustLevel,
		&i.AccountStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhoneNumber,
		&i.PersonalEmail,
		&i.LegalName,
		&i.Address,
		&i.CompanyDomain,
		&i.WorkEmailVerified,
		&i.WorkEmailVerifiedAt,
		&i.AgeConfirmedOver18,
		&i.AgeConfirmedAt,
		&i.WorkEmailHash,
		&i.RatingAverage,
		&i.RatingCount,
		&i.RatingUpdatedAt,
		&i.LastLocationLat,
		&i.LastLocationLng,
		&i.LastLocationUpdatedAt,
	)
	return i, err
}

const updateUserWorkEmailVerified = `-- name: UpdateUserWorkEmailVerified :one
UPDATE auth.users SET company_domain = $2, work_email_verified = $3, work_email_verified_at = $4, work_email_hash = $5, trust_level = $6
WHERE id = $1 RETURNING id, linkedin_sub, full_name, profile_photo_url, headline, trust_level, account_status, created_at, updated_at, phone_number, personal_email, legal_name, address, company_domain, work_email_verified, work_email_verified_at, age_confirmed_over_18, age_confirmed_at, work_email_hash, rating_average, rating_count, rating_updated_at, last_location_lat, last_location_lng, last_location_updated_at
`

type UpdateUserWorkEmailVerifiedParams struct {
	ID                  uuid.UUID          `json:"id"`
	CompanyDomain       pgtype.Text        `json:"company_domain"`
	WorkEmailVerified   bool               `json:"work_email_verified"`
	WorkEmailVerifiedAt pgtype.Timestamptz `json:"work_email_verified_at"`
	WorkEmailHash       pgtype.Text        `json:"work_email_hash"`
	TrustLevel          int16              `json:"trust_level"`
}

// work_email_hash is set alongside company_domain/work_email_verified
// (ADR-019 §3) — a keyed HMAC of the normalized raw address, the reuse-
// abuse check's UNIQUE anchor (GetUserByWorkEmailHash below is what
// detects a collision BEFORE this runs; the UNIQUE constraint here is the
// last-resort race guard, same pattern as phone_number/personal_email).
func (q *Queries) UpdateUserWorkEmailVerified(ctx context.Context, arg UpdateUserWorkEmailVerifiedParams) (AuthUser, error) {
	row := q.db.QueryRow(ctx, updateUserWorkEmailVerified,
		arg.ID,
		arg.CompanyDomain,
		arg.WorkEmailVerified,
		arg.WorkEmailVerifiedAt,
		arg.WorkEmailHash,
		arg.TrustLevel,
	)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.LinkedinSub,
		&i.FullName,
		&i.ProfilePhotoUrl,
		&i.Headline,
		&i.TrustLevel,
		&i.AccountStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhoneNumber,
		&i.PersonalEmail,
		&i.LegalName,
		&i.Address,
		&i.CompanyDomain,
		&i.WorkEmailVerified,
		&i.WorkEmailVerifiedAt,
		&i.AgeConfirmedOver18,
		&i.AgeConfirmedAt,
		&i.WorkEmailHash,
		&i.RatingAverage,
		&i.RatingCount,
		&i.RatingUpdatedAt,
		&i.LastLocationLat,
		&i.LastLocationLng,
		&i.LastLocationUpdatedAt,
	)
	return i, err
}

const upsertUserRatingCache = `-- name: UpsertUserRatingCache :execrows
UPDATE auth.users
SET rating_average = $1,
    rating_count = $2,
    rating_updated_at = $3
WHERE id = $4
  AND (rating_updated_at IS NULL OR $3::timestamptz > rating_updated_at)
`

type UpsertUserRatingCacheParams struct {
	RatingAverage pgtype.Numeric     `json:"rating_average"`
	RatingCount   int32              `json:"rating_count"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
	UserID        uuid.UUID          `json:"user_id"`
}

// The rating-updated consumer's idempotent, order-guarded upsert (ADR-018
// Decision 2, ADR-017's addendum Step 5b) — users.rating_average/
// rating_count are a read-only cache of what services/meetup owns as of
// this migration, written only from here. The WHERE clause is the
// ordering guard: applies unconditionally the first time (rating_updated_at
// still NULL from auth/0004's ALTER TABLE default), otherwise only if this
// event is strictly newer than whatever's already stored — an
// out-of-order redelivery of an older event is a no-op, not a regression.
// Rows affected (0 or 1) tells the caller whether the guard actually
// skipped a stale event, purely for logging.
func (q *Queries) UpsertUserRatingCache(ctx context.Context, arg UpsertUserRatingCacheParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertUserRatingCache,
		arg.RatingAverage,
		arg.RatingCount,
		arg.OccurredAt,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
