// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verification_codes.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteVerificationCode = `-- name: DeleteVerificationCode :exec
DELETE FROM auth.verification_codes WHERE user_id = $1 AND purpose = $2
`

type DeleteVerificationCodeParams struct {
	UserID  pgtype.UUID             `json:"user_id"`
	Purpose AuthVerificationPurpose `json:"purpose"`
}

func (q *Queries) DeleteVerificationCode(ctx context.Context, arg DeleteVerificationCodeParams) error {
	_, err := q.db.Exec(ctx, deleteVerificationCode, arg.UserID, arg.Purpose)
	return err
}

const deleteVerificationCodeByTarget = `-- name: DeleteVerificationCodeByTarget :exec
DELETE FROM auth.verification_codes WHERE user_id IS NULL AND purpose = $1 AND target = $2
`

type DeleteVerificationCodeByTargetParams struct {
	Purpose AuthVerificationPurpose `json:"purpose"`
	Target  string                  `json:"target"`
}

func (q *Queries) DeleteVerificationCodeByTarget(ctx context.Context, arg DeleteVerificationCodeByTargetParams) error {
	_, err := q.db.Exec(ctx, deleteVerificationCodeByTarget, arg.Purpose, arg.Target)
	return err
}

const getVerificationCode = `-- name: GetVerificationCode :one
SELECT id, user_id, purpose, target, code_hash, attempts, expires_at, created_at FROM auth.verification_codes WHERE user_id = $1 AND purpose = $2
`

type GetVerificationCodeParams struct {
	UserID  pgtype.UUID             `json:"user_id"`
	Purpose AuthVerificationPurpose `json:"purpose"`
}

func (q *Queries) GetVerificationCode(ctx context.Context, arg GetVerificationCodeParams) (AuthVerificationCode, error) {
	row := q.db.QueryRow(ctx, getVerificationCode, arg.UserID, arg.Purpose)
	var i AuthVerificationCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.Target,
		&i.CodeHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getVerificationCodeByTarget = `-- name: GetVerificationCodeByTarget :one
SELECT id, user_id, purpose, target, code_hash, attempts, expires_at, created_at FROM auth.verification_codes WHERE user_id IS NULL AND purpose = $1 AND target = $2
`

type GetVerificationCodeByTargetParams struct {
	Purpose AuthVerificationPurpose `json:"purpose"`
	Target  string                  `json:"target"`
}

func (q *Queries) GetVerificationCodeByTarget(ctx context.Context, arg GetVerificationCodeByTargetParams) (AuthVerificationCode, error) {
	row := q.db.QueryRow(ctx, getVerificationCodeByTarget, arg.Purpose, arg.Target)
	var i AuthVerificationCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.Target,
		&i.CodeHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementVerificationAttempts = `-- name: IncrementVerificationAttempts :one
UPDATE auth.verification_codes SET attempts = attempts + 1
WHERE user_id = $1 AND purpose = $2
RETURNING id, user_id, purpose, target, code_hash, attempts, expires_at, created_at
`

type IncrementVerificationAttemptsParams struct {
	UserID  pgtype.UUID             `json:"user_id"`
	Purpose AuthVerificationPurpose `json:"purpose"`
}

func (q *Queries) IncrementVerificationAttempts(ctx context.Context, arg IncrementVerificationAttemptsParams) (AuthVerificationCode, error) {
	row := q.db.QueryRow(ctx, incrementVerificationAttempts, arg.UserID, arg.Purpose)
	var i AuthVerificationCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.Target,
		&i.CodeHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementVerificationAttemptsByTarget = `-- name: IncrementVerificationAttemptsByTarget :one
UPDATE auth.verification_codes SET attempts = attempts + 1
WHERE user_id IS NULL AND purpose = $1 AND target = $2
RETURNING id, user_id, purpose, target, code_hash, attempts, expires_at, created_at
`

type IncrementVerificationAttemptsByTargetParams struct {
	Purpose AuthVerificationPurpose `json:"purpose"`
	Target  string                  `json:"target"`
}

func (q *Queries) IncrementVerificationAttemptsByTarget(ctx context.Context, arg IncrementVerificationAttemptsByTargetParams) (AuthVerificationCode, error) {
	row := q.db.QueryRow(ctx, incrementVerificationAttemptsByTarget, arg.Purpose, arg.Target)
	var i AuthVerificationCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.Target,
		&i.CodeHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertVerificationCode = `-- name: UpsertVerificationCode :one
INSERT INTO auth.verification_codes (user_id, purpose, target, code_hash, expires_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, purpose)
DO UPDATE SET target = $3, code_hash = $4, attempts = 0, expires_at = $5, created_at = now()
RETURNING id, user_id, purpose, target, code_hash, attempts, expires_at, created_at
`

type UpsertVerificationCodeParams struct {
	UserID    pgtype.UUID             `json:"user_id"`
	Purpose   AuthVerificationPurpose `json:"purpose"`
	Target    string                  `json:"target"`
	CodeHash  string                  `json:"code_hash"`
	ExpiresAt pgtype.Timestamptz      `json:"expires_at"`
}

// One pending code per (user_id, purpose) — a resend overwrites the
// existing row (including resetting attempts and created_at) rather than
// stacking a second one.
func (q *Queries) UpsertVerificationCode(ctx context.Context, arg UpsertVerificationCodeParams) (AuthVerificationCode, error) {
	row := q.db.QueryRow(ctx, upsertVerificationCode,
		arg.UserID,
		arg.Purpose,
		arg.Target,
		arg.CodeHash,
		arg.ExpiresAt,
	)
	var i AuthVerificationCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.Target,
		&i.CodeHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertVerificationCodeForSignup = `-- name: UpsertVerificationCodeForSignup :one

INSERT INTO auth.verification_codes (user_id, purpose, target, code_hash, expires_at)
VALUES (NULL, $1, $2, $3, $4)
ON CONFLICT (purpose, target) WHERE user_id IS NULL
DO UPDATE SET code_hash = $3, attempts = 0, expires_at = $4, created_at = now()
RETURNING id, user_id, purpose, target, code_hash, attempts, expires_at, created_at
`

type UpsertVerificationCodeForSignupParams struct {
	Purpose   AuthVerificationPurpose `json:"purpose"`
	Target    string                  `json:"target"`
	CodeHash  string                  `json:"code_hash"`
	ExpiresAt pgtype.Timestamptz      `json:"expires_at"`
}

// Email-OTP signup (ADR-014 decision #2, migration 0004; passwordless as
// of ADR-019 §1) — the account may not exist yet at OTP-send time (see
// SignUpOrRecoverWithEmail's recovery path), so these four mirror the
// four above exactly except keyed by (purpose, target) instead of
// (user_id, purpose), via idx_verification_codes_signup_target. Used for
// both VERIFICATION_PURPOSE_EMAIL_SIGNUP and VERIFICATION_PURPOSE_EMAIL_LOGIN
// (migration 0006, ADR-019 §1) — user_id is always NULL on these rows.
func (q *Queries) UpsertVerificationCodeForSignup(ctx context.Context, arg UpsertVerificationCodeForSignupParams) (AuthVerificationCode, error) {
	row := q.db.QueryRow(ctx, upsertVerificationCodeForSignup,
		arg.Purpose,
		arg.Target,
		arg.CodeHash,
		arg.ExpiresAt,
	)
	var i AuthVerificationCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.Target,
		&i.CodeHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
