// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: meetup/v1/meetup.proto

package meetupv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MeetupService_CreateMeetup_FullMethodName               = "/meetup.v1.MeetupService/CreateMeetup"
	MeetupService_ListOpenMeetups_FullMethodName            = "/meetup.v1.MeetupService/ListOpenMeetups"
	MeetupService_GetMeetup_FullMethodName                  = "/meetup.v1.MeetupService/GetMeetup"
	MeetupService_ListMyMeetups_FullMethodName              = "/meetup.v1.MeetupService/ListMyMeetups"
	MeetupService_ListActiveMeetups_FullMethodName          = "/meetup.v1.MeetupService/ListActiveMeetups"
	MeetupService_ListMeetupRequests_FullMethodName         = "/meetup.v1.MeetupService/ListMeetupRequests"
	MeetupService_RequestToJoin_FullMethodName              = "/meetup.v1.MeetupService/RequestToJoin"
	MeetupService_WithdrawRequest_FullMethodName            = "/meetup.v1.MeetupService/WithdrawRequest"
	MeetupService_RespondToRequest_FullMethodName           = "/meetup.v1.MeetupService/RespondToRequest"
	MeetupService_RegisterDeviceToken_FullMethodName        = "/meetup.v1.MeetupService/RegisterDeviceToken"
	MeetupService_GetSafetyState_FullMethodName             = "/meetup.v1.MeetupService/GetSafetyState"
	MeetupService_AcknowledgeSafetyChecklist_FullMethodName = "/meetup.v1.MeetupService/AcknowledgeSafetyChecklist"
	MeetupService_SetLiveLocationOptIn_FullMethodName       = "/meetup.v1.MeetupService/SetLiveLocationOptIn"
	MeetupService_ShareWithContacts_FullMethodName          = "/meetup.v1.MeetupService/ShareWithContacts"
	MeetupService_CheckIn_FullMethodName                    = "/meetup.v1.MeetupService/CheckIn"
	MeetupService_DeclineCheckIn_FullMethodName             = "/meetup.v1.MeetupService/DeclineCheckIn"
	MeetupService_SubmitMeetupFeedback_FullMethodName       = "/meetup.v1.MeetupService/SubmitMeetupFeedback"
	MeetupService_ListRatableParticipants_FullMethodName    = "/meetup.v1.MeetupService/ListRatableParticipants"
	MeetupService_SubmitRating_FullMethodName               = "/meetup.v1.MeetupService/SubmitRating"
	MeetupService_CloseMeetup_FullMethodName                = "/meetup.v1.MeetupService/CloseMeetup"
	MeetupService_CancelMeetup_FullMethodName               = "/meetup.v1.MeetupService/CancelMeetup"
)

// MeetupServiceClient is the client API for MeetupService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MeetupService is the meetup module's half of the gateway<->monolith gRPC
// contract (ADR-001 §1) — never exposed directly to clients. Registered on
// the same server and the same port as AuthService, so the shared-secret
// interceptor (internal/platform/internalauth, wired at the server level in
// cmd/monolith) already authenticates every RPC below without any
// per-service wiring.
//
// Ported unchanged from ../Professional-Meetups/backend/proto/meetup/v1 —
// unlike auth.proto, this contract needed no ADR-001 §6-style adjustment:
// nothing here mints or carries a session token.
//
// Every RPC below takes the caller's identity (user_id, and trust_level
// where the RPC needs it) as explicit fields set by the gateway from the
// verified JWT — never a client-supplied value (same pattern as
// AuthService's Level 2/3 verification RPCs). Viewing open meetups needs no
// trust-level gate (ADR-013 § 2 — Level 1 still unlocks browsing); creating
// one or requesting to join does.
type MeetupServiceClient interface {
	// Creates a Meetup. Rejects with PermissionDenied if host_trust_level is
	// below the per-intent floor (ADR-013 § 2: ride_share/dating need 4,
	// everything else needs 2) — checked server-side regardless of what the
	// client's UI already gates on.
	CreateMeetup(ctx context.Context, in *CreateMeetupRequest, opts ...grpc.CallOption) (*MeetupResponse, error)
	// Lists open meetups for intent, cursor-paginated. No trust-level gate on
	// browsing itself — Level 1 users can browse (ADR-013 § 2). As of ADR-028,
	// each returned meetup's sensitive fields (host name/photo, location,
	// time window) are redacted server-side when the viewer is below that
	// meetup's own required trust level — see MeetupResponse.locked_for_viewer.
	ListOpenMeetups(ctx context.Context, in *ListOpenMeetupsRequest, opts ...grpc.CallOption) (*ListOpenMeetupsResponse, error)
	// Returns a single meetup. No gate on being able to call this at all
	// (same as ListOpenMeetups), but as of ADR-028 (round-5 hardening) the
	// response is redacted the same way ListOpenMeetups's own entries are
	// when the viewer is below the meetup's required trust level — see
	// MeetupResponse.locked_for_viewer.
	GetMeetup(ctx context.Context, in *GetMeetupRequest, opts ...grpc.CallOption) (*MeetupResponse, error)
	// Returns the meetups user_id hosts and the ones they've requested to
	// join, separately — the "My Meetups" view.
	ListMyMeetups(ctx context.Context, in *ListMyMeetupsRequest, opts ...grpc.CallOption) (*ListMyMeetupsResponse, error)
	// ListActiveMeetups (ADR-025 §2) merges "I'm host" and "I'm an accepted
	// participant" into one server-sorted (soonest window_start first) list,
	// scoped to status IN ('open','full') AND window_end >= now(). Backs the
	// HomePage "Active Meetups" section and the persistent current-meetup
	// card — which meetup(s) get the big card treatment is a presentational
	// decision made client-side from window_start/window_end, not a second
	// authorization decision.
	ListActiveMeetups(ctx context.Context, in *ListActiveMeetupsRequest, opts ...grpc.CallOption) (*ListActiveMeetupsResponse, error)
	// Returns every request (any status) on a meetup, with requester display
	// info — the host's request-management view (frontend/meetup-scheduling-
	// PLAN.md Step 8). Host-only — verified against meetups.host_user_id,
	// same as RespondToRequest.
	ListMeetupRequests(ctx context.Context, in *ListMeetupRequestsRequest, opts ...grpc.CallOption) (*ListMeetupRequestsResponse, error)
	// Requests to join a meetup. Rejects with PermissionDenied below the
	// intent's trust floor, Conflict if the meetup is full/
	// cancelled/completed or the requester is the host, AlreadyExists if a
	// pending/accepted request from this requester already exists.
	RequestToJoin(ctx context.Context, in *RequestToJoinRequest, opts ...grpc.CallOption) (*MeetupRequestResponse, error)
	// Withdraws a pending or already-accepted request, with an optional note
	// (ADR-020 §4 — widened from pending-only: a requester backing out after
	// being accepted is exactly the case the withdrawal-rating path below
	// exists for). Requester-only — verified against requester_id, not just
	// that *a* valid token was presented. Notifies the host, and unlocks a
	// new rating-eligibility path letting the host rate this requester once
	// (independent of the meetup's own eventual status — this is per-request,
	// not per-meetup).
	WithdrawRequest(ctx context.Context, in *WithdrawRequestRequest, opts ...grpc.CallOption) (*WithdrawRequestResponse, error)
	// Host accepts or rejects a single request. Host-only — verified against
	// meetups.host_user_id. Accepting runs the capacity check + auto-reject
	// transition inside one DB transaction with row locking (backend/
	// meetup-scheduling-PLAN.md Step B) — a race between two near-simultaneous
	// accept calls must resolve to exactly one winner, never a double-accept
	// past capacity.
	RespondToRequest(ctx context.Context, in *RespondToRequestRequest, opts ...grpc.CallOption) (*MeetupRequestResponse, error)
	// Registers (or re-registers, on rotation) an FCM device token for push
	// delivery (ADR-013 § 6). Upserts by token, not by user — a token
	// identifies one physical device install.
	RegisterDeviceToken(ctx context.Context, in *RegisterDeviceTokenRequest, opts ...grpc.CallOption) (*RegisterDeviceTokenResponse, error)
	// Safety Gate sub-flow (ADR-013 § 3, Safety UX Flows.md): checklist
	// acknowledgment, live-location opt-in, check-in, post-meetup feedback.
	// Available once a meetup has at least one accepted request.
	//
	// Returns NotFound if the meetup has no Safety Gate state yet (no
	// accepted request) — distinct from a zero-value SafetyStateResponse, so
	// a client reopening this meetup later can tell "not started" from
	// "started, nothing acknowledged yet."
	GetSafetyState(ctx context.Context, in *GetSafetyStateRequest, opts ...grpc.CallOption) (*SafetyStateResponse, error)
	AcknowledgeSafetyChecklist(ctx context.Context, in *AcknowledgeSafetyChecklistRequest, opts ...grpc.CallOption) (*SafetyStateResponse, error)
	SetLiveLocationOptIn(ctx context.Context, in *SetLiveLocationOptInRequest, opts ...grpc.CallOption) (*SafetyStateResponse, error)
	// ShareWithContacts texts/emails the caller's CHOSEN trusted contacts the
	// meetup's window and place. The message body is built server-side from
	// the meetup row — the client supplies only which of its own contacts to
	// tell (see meetup/safety.go's ShareWithContacts).
	ShareWithContacts(ctx context.Context, in *ShareWithContactsRequest, opts ...grpc.CallOption) (*SafetyStateResponse, error)
	// Rejects with Conflict if the checklist hasn't been
	// acknowledged yet — checklist before check-in is the Safety UX Flows.md
	// step order, enforced server-side, not just by the client's own step
	// sequencing. Also rejects with Conflict if the caller already declined
	// (ADR-024 § 4) — mutually exclusive terminal states.
	CheckIn(ctx context.Context, in *CheckInRequest, opts ...grpc.CallOption) (*SafetyStateResponse, error)
	// DeclineCheckIn (ADR-024 § 4) — reason is required (rejected if empty).
	// Rejects with Conflict if the caller already checked in. Notifies the
	// host on success.
	DeclineCheckIn(ctx context.Context, in *DeclineCheckInRequest, opts ...grpc.CallOption) (*SafetyStateResponse, error)
	SubmitMeetupFeedback(ctx context.Context, in *SubmitMeetupFeedbackRequest, opts ...grpc.CallOption) (*SubmitMeetupFeedbackResponse, error)
	// Post-meetup star ratings (ADR-015, docs/02-domain/domain-model.md §
	// Rating). Returns the caller's other participants on meetup_id (host +
	// accepted requesters, excluding self), each flagged with whether the
	// caller already rated them. Empty (not an error) if the caller isn't a
	// participant.
	ListRatableParticipants(ctx context.Context, in *ListRatableParticipantsRequest, opts ...grpc.CallOption) (*ListRatableParticipantsResponse, error)
	// Records rater_user_id's score for rated_user_id on meetup_id. Rejects
	// with Forbidden if rater_user_id isn't a participant of meetup_id, or
	// fails all three rating-eligibility branches (ADR-015's original
	// happened-based one, plus ADR-020's two new ones): confirmed
	// (SubmitMeetupFeedback, happened=true) that the meetup happened; an
	// accepted requester rating the host of a meetup that was cancelled; or
	// the host rating a requester whose request was withdrawn. Rejects with
	// Conflict on a duplicate (meetup_id, rater_user_id, rated_user_id)
	// submission, InvalidArgument on a self-rating attempt or an
	// out-of-range score. All three branches write into the exact same
	// rating pool — never a separate one per trigger.
	SubmitRating(ctx context.Context, in *SubmitRatingRequest, opts ...grpc.CallOption) (*SubmitRatingResponse, error)
	// Host-only "meetup is done" action (ADR-016), reviving meetup_status's
	// previously-unused COMPLETED value. Rejects with Forbidden if the
	// caller isn't the host or the window hasn't started yet
	// (now() >= window_start), Conflict if the meetup is already closed/
	// cancelled. Explicitly independent of rating eligibility — closing a
	// meetup has zero effect on who can rate whom, that's still gated on
	// each participant's own meetup_feedback.happened (ADR-015, unchanged).
	CloseMeetup(ctx context.Context, in *CloseMeetupRequest, opts ...grpc.CallOption) (*CloseMeetupResponse, error)
	// Host-only, with a required reason (ADR-020 §3 — previously rejected
	// outright once any request was accepted; now allowed with a mandatory
	// reason instead). Notifies every currently-accepted requester, and
	// unlocks a new rating-eligibility path letting each of them rate the
	// host once.
	CancelMeetup(ctx context.Context, in *CancelMeetupRequest, opts ...grpc.CallOption) (*CancelMeetupResponse, error)
}

type meetupServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMeetupServiceClient(cc grpc.ClientConnInterface) MeetupServiceClient {
	return &meetupServiceClient{cc}
}

func (c *meetupServiceClient) CreateMeetup(ctx context.Context, in *CreateMeetupRequest, opts ...grpc.CallOption) (*MeetupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MeetupResponse)
	err := c.cc.Invoke(ctx, MeetupService_CreateMeetup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetupServiceClient) ListOpenMeetups(ctx context.Context, in *ListOpenMeetupsRequest, opts ...grpc.CallOption) (*ListOpenMeetupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOpenMeetupsResponse)
	err := c.cc.Invoke(ctx, MeetupService_ListOpenMeetups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetupServiceClient) GetMeetup(ctx context.Context, in *GetMeetupRequest, opts ...grpc.CallOption) (*MeetupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MeetupResponse)
	err := c.cc.Invoke(ctx, MeetupService_GetMeetup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetupServiceClient) ListMyMeetups(ctx context.Context, in *ListMyMeetupsRequest, opts ...grpc.CallOption) (*ListMyMeetupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMyMeetupsResponse)
	err := c.cc.Invoke(ctx, MeetupService_ListMyMeetups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetupServiceClient) ListActiveMeetups(ctx context.Context, in *ListActiveMeetupsRequest, opts ...grpc.CallOption) (*ListActiveMeetupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListActiveMeetupsResponse)
	err := c.cc.Invoke(ctx, MeetupService_ListActiveMeetups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetupServiceClient) ListMeetupRequests(ctx context.Context, in *ListMeetupRequestsRequest, opts ...grpc.CallOption) (*ListMeetupRequestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMeetupRequestsResponse)
	err := c.cc.Invoke(ctx, MeetupService_ListMeetupRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetupServiceClient) RequestToJoin(ctx context.Context, in *RequestToJoinRequest, opts ...grpc.CallOption) (*MeetupRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MeetupRequestResponse)
	err := c.cc.Invoke(ctx, MeetupService_RequestToJoin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetupServiceClient) WithdrawRequest(ctx context.Context, in *WithdrawRequestRequest, opts ...grpc.CallOption) (*WithdrawRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WithdrawRequestResponse)
	err := c.cc.Invoke(ctx, MeetupService_WithdrawRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetupServiceClient) RespondToRequest(ctx context.Context, in *RespondToRequestRequest, opts ...grpc.CallOption) (*MeetupRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MeetupRequestResponse)
	err := c.cc.Invoke(ctx, MeetupService_RespondToRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetupServiceClient) RegisterDeviceToken(ctx context.Context, in *RegisterDeviceTokenRequest, opts ...grpc.CallOption) (*RegisterDeviceTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterDeviceTokenResponse)
	err := c.cc.Invoke(ctx, MeetupService_RegisterDeviceToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetupServiceClient) GetSafetyState(ctx context.Context, in *GetSafetyStateRequest, opts ...grpc.CallOption) (*SafetyStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SafetyStateResponse)
	err := c.cc.Invoke(ctx, MeetupService_GetSafetyState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetupServiceClient) AcknowledgeSafetyChecklist(ctx context.Context, in *AcknowledgeSafetyChecklistRequest, opts ...grpc.CallOption) (*SafetyStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SafetyStateResponse)
	err := c.cc.Invoke(ctx, MeetupService_AcknowledgeSafetyChecklist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetupServiceClient) SetLiveLocationOptIn(ctx context.Context, in *SetLiveLocationOptInRequest, opts ...grpc.CallOption) (*SafetyStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SafetyStateResponse)
	err := c.cc.Invoke(ctx, MeetupService_SetLiveLocationOptIn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetupServiceClient) ShareWithContacts(ctx context.Context, in *ShareWithContactsRequest, opts ...grpc.CallOption) (*SafetyStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SafetyStateResponse)
	err := c.cc.Invoke(ctx, MeetupService_ShareWithContacts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetupServiceClient) CheckIn(ctx context.Context, in *CheckInRequest, opts ...grpc.CallOption) (*SafetyStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SafetyStateResponse)
	err := c.cc.Invoke(ctx, MeetupService_CheckIn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetupServiceClient) DeclineCheckIn(ctx context.Context, in *DeclineCheckInRequest, opts ...grpc.CallOption) (*SafetyStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SafetyStateResponse)
	err := c.cc.Invoke(ctx, MeetupService_DeclineCheckIn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetupServiceClient) SubmitMeetupFeedback(ctx context.Context, in *SubmitMeetupFeedbackRequest, opts ...grpc.CallOption) (*SubmitMeetupFeedbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitMeetupFeedbackResponse)
	err := c.cc.Invoke(ctx, MeetupService_SubmitMeetupFeedback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetupServiceClient) ListRatableParticipants(ctx context.Context, in *ListRatableParticipantsRequest, opts ...grpc.CallOption) (*ListRatableParticipantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRatableParticipantsResponse)
	err := c.cc.Invoke(ctx, MeetupService_ListRatableParticipants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetupServiceClient) SubmitRating(ctx context.Context, in *SubmitRatingRequest, opts ...grpc.CallOption) (*SubmitRatingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitRatingResponse)
	err := c.cc.Invoke(ctx, MeetupService_SubmitRating_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetupServiceClient) CloseMeetup(ctx context.Context, in *CloseMeetupRequest, opts ...grpc.CallOption) (*CloseMeetupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseMeetupResponse)
	err := c.cc.Invoke(ctx, MeetupService_CloseMeetup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetupServiceClient) CancelMeetup(ctx context.Context, in *CancelMeetupRequest, opts ...grpc.CallOption) (*CancelMeetupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelMeetupResponse)
	err := c.cc.Invoke(ctx, MeetupService_CancelMeetup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MeetupServiceServer is the server API for MeetupService service.
// All implementations must embed UnimplementedMeetupServiceServer
// for forward compatibility.
//
// MeetupService is the meetup module's half of the gateway<->monolith gRPC
// contract (ADR-001 §1) — never exposed directly to clients. Registered on
// the same server and the same port as AuthService, so the shared-secret
// interceptor (internal/platform/internalauth, wired at the server level in
// cmd/monolith) already authenticates every RPC below without any
// per-service wiring.
//
// Ported unchanged from ../Professional-Meetups/backend/proto/meetup/v1 —
// unlike auth.proto, this contract needed no ADR-001 §6-style adjustment:
// nothing here mints or carries a session token.
//
// Every RPC below takes the caller's identity (user_id, and trust_level
// where the RPC needs it) as explicit fields set by the gateway from the
// verified JWT — never a client-supplied value (same pattern as
// AuthService's Level 2/3 verification RPCs). Viewing open meetups needs no
// trust-level gate (ADR-013 § 2 — Level 1 still unlocks browsing); creating
// one or requesting to join does.
type MeetupServiceServer interface {
	// Creates a Meetup. Rejects with PermissionDenied if host_trust_level is
	// below the per-intent floor (ADR-013 § 2: ride_share/dating need 4,
	// everything else needs 2) — checked server-side regardless of what the
	// client's UI already gates on.
	CreateMeetup(context.Context, *CreateMeetupRequest) (*MeetupResponse, error)
	// Lists open meetups for intent, cursor-paginated. No trust-level gate on
	// browsing itself — Level 1 users can browse (ADR-013 § 2). As of ADR-028,
	// each returned meetup's sensitive fields (host name/photo, location,
	// time window) are redacted server-side when the viewer is below that
	// meetup's own required trust level — see MeetupResponse.locked_for_viewer.
	ListOpenMeetups(context.Context, *ListOpenMeetupsRequest) (*ListOpenMeetupsResponse, error)
	// Returns a single meetup. No gate on being able to call this at all
	// (same as ListOpenMeetups), but as of ADR-028 (round-5 hardening) the
	// response is redacted the same way ListOpenMeetups's own entries are
	// when the viewer is below the meetup's required trust level — see
	// MeetupResponse.locked_for_viewer.
	GetMeetup(context.Context, *GetMeetupRequest) (*MeetupResponse, error)
	// Returns the meetups user_id hosts and the ones they've requested to
	// join, separately — the "My Meetups" view.
	ListMyMeetups(context.Context, *ListMyMeetupsRequest) (*ListMyMeetupsResponse, error)
	// ListActiveMeetups (ADR-025 §2) merges "I'm host" and "I'm an accepted
	// participant" into one server-sorted (soonest window_start first) list,
	// scoped to status IN ('open','full') AND window_end >= now(). Backs the
	// HomePage "Active Meetups" section and the persistent current-meetup
	// card — which meetup(s) get the big card treatment is a presentational
	// decision made client-side from window_start/window_end, not a second
	// authorization decision.
	ListActiveMeetups(context.Context, *ListActiveMeetupsRequest) (*ListActiveMeetupsResponse, error)
	// Returns every request (any status) on a meetup, with requester display
	// info — the host's request-management view (frontend/meetup-scheduling-
	// PLAN.md Step 8). Host-only — verified against meetups.host_user_id,
	// same as RespondToRequest.
	ListMeetupRequests(context.Context, *ListMeetupRequestsRequest) (*ListMeetupRequestsResponse, error)
	// Requests to join a meetup. Rejects with PermissionDenied below the
	// intent's trust floor, Conflict if the meetup is full/
	// cancelled/completed or the requester is the host, AlreadyExists if a
	// pending/accepted request from this requester already exists.
	RequestToJoin(context.Context, *RequestToJoinRequest) (*MeetupRequestResponse, error)
	// Withdraws a pending or already-accepted request, with an optional note
	// (ADR-020 §4 — widened from pending-only: a requester backing out after
	// being accepted is exactly the case the withdrawal-rating path below
	// exists for). Requester-only — verified against requester_id, not just
	// that *a* valid token was presented. Notifies the host, and unlocks a
	// new rating-eligibility path letting the host rate this requester once
	// (independent of the meetup's own eventual status — this is per-request,
	// not per-meetup).
	WithdrawRequest(context.Context, *WithdrawRequestRequest) (*WithdrawRequestResponse, error)
	// Host accepts or rejects a single request. Host-only — verified against
	// meetups.host_user_id. Accepting runs the capacity check + auto-reject
	// transition inside one DB transaction with row locking (backend/
	// meetup-scheduling-PLAN.md Step B) — a race between two near-simultaneous
	// accept calls must resolve to exactly one winner, never a double-accept
	// past capacity.
	RespondToRequest(context.Context, *RespondToRequestRequest) (*MeetupRequestResponse, error)
	// Registers (or re-registers, on rotation) an FCM device token for push
	// delivery (ADR-013 § 6). Upserts by token, not by user — a token
	// identifies one physical device install.
	RegisterDeviceToken(context.Context, *RegisterDeviceTokenRequest) (*RegisterDeviceTokenResponse, error)
	// Safety Gate sub-flow (ADR-013 § 3, Safety UX Flows.md): checklist
	// acknowledgment, live-location opt-in, check-in, post-meetup feedback.
	// Available once a meetup has at least one accepted request.
	//
	// Returns NotFound if the meetup has no Safety Gate state yet (no
	// accepted request) — distinct from a zero-value SafetyStateResponse, so
	// a client reopening this meetup later can tell "not started" from
	// "started, nothing acknowledged yet."
	GetSafetyState(context.Context, *GetSafetyStateRequest) (*SafetyStateResponse, error)
	AcknowledgeSafetyChecklist(context.Context, *AcknowledgeSafetyChecklistRequest) (*SafetyStateResponse, error)
	SetLiveLocationOptIn(context.Context, *SetLiveLocationOptInRequest) (*SafetyStateResponse, error)
	// ShareWithContacts texts/emails the caller's CHOSEN trusted contacts the
	// meetup's window and place. The message body is built server-side from
	// the meetup row — the client supplies only which of its own contacts to
	// tell (see meetup/safety.go's ShareWithContacts).
	ShareWithContacts(context.Context, *ShareWithContactsRequest) (*SafetyStateResponse, error)
	// Rejects with Conflict if the checklist hasn't been
	// acknowledged yet — checklist before check-in is the Safety UX Flows.md
	// step order, enforced server-side, not just by the client's own step
	// sequencing. Also rejects with Conflict if the caller already declined
	// (ADR-024 § 4) — mutually exclusive terminal states.
	CheckIn(context.Context, *CheckInRequest) (*SafetyStateResponse, error)
	// DeclineCheckIn (ADR-024 § 4) — reason is required (rejected if empty).
	// Rejects with Conflict if the caller already checked in. Notifies the
	// host on success.
	DeclineCheckIn(context.Context, *DeclineCheckInRequest) (*SafetyStateResponse, error)
	SubmitMeetupFeedback(context.Context, *SubmitMeetupFeedbackRequest) (*SubmitMeetupFeedbackResponse, error)
	// Post-meetup star ratings (ADR-015, docs/02-domain/domain-model.md §
	// Rating). Returns the caller's other participants on meetup_id (host +
	// accepted requesters, excluding self), each flagged with whether the
	// caller already rated them. Empty (not an error) if the caller isn't a
	// participant.
	ListRatableParticipants(context.Context, *ListRatableParticipantsRequest) (*ListRatableParticipantsResponse, error)
	// Records rater_user_id's score for rated_user_id on meetup_id. Rejects
	// with Forbidden if rater_user_id isn't a participant of meetup_id, or
	// fails all three rating-eligibility branches (ADR-015's original
	// happened-based one, plus ADR-020's two new ones): confirmed
	// (SubmitMeetupFeedback, happened=true) that the meetup happened; an
	// accepted requester rating the host of a meetup that was cancelled; or
	// the host rating a requester whose request was withdrawn. Rejects with
	// Conflict on a duplicate (meetup_id, rater_user_id, rated_user_id)
	// submission, InvalidArgument on a self-rating attempt or an
	// out-of-range score. All three branches write into the exact same
	// rating pool — never a separate one per trigger.
	SubmitRating(context.Context, *SubmitRatingRequest) (*SubmitRatingResponse, error)
	// Host-only "meetup is done" action (ADR-016), reviving meetup_status's
	// previously-unused COMPLETED value. Rejects with Forbidden if the
	// caller isn't the host or the window hasn't started yet
	// (now() >= window_start), Conflict if the meetup is already closed/
	// cancelled. Explicitly independent of rating eligibility — closing a
	// meetup has zero effect on who can rate whom, that's still gated on
	// each participant's own meetup_feedback.happened (ADR-015, unchanged).
	CloseMeetup(context.Context, *CloseMeetupRequest) (*CloseMeetupResponse, error)
	// Host-only, with a required reason (ADR-020 §3 — previously rejected
	// outright once any request was accepted; now allowed with a mandatory
	// reason instead). Notifies every currently-accepted requester, and
	// unlocks a new rating-eligibility path letting each of them rate the
	// host once.
	CancelMeetup(context.Context, *CancelMeetupRequest) (*CancelMeetupResponse, error)
	mustEmbedUnimplementedMeetupServiceServer()
}

// UnimplementedMeetupServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMeetupServiceServer struct{}

func (UnimplementedMeetupServiceServer) CreateMeetup(context.Context, *CreateMeetupRequest) (*MeetupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMeetup not implemented")
}
func (UnimplementedMeetupServiceServer) ListOpenMeetups(context.Context, *ListOpenMeetupsRequest) (*ListOpenMeetupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOpenMeetups not implemented")
}
func (UnimplementedMeetupServiceServer) GetMeetup(context.Context, *GetMeetupRequest) (*MeetupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMeetup not implemented")
}
func (UnimplementedMeetupServiceServer) ListMyMeetups(context.Context, *ListMyMeetupsRequest) (*ListMyMeetupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMyMeetups not implemented")
}
func (UnimplementedMeetupServiceServer) ListActiveMeetups(context.Context, *ListActiveMeetupsRequest) (*ListActiveMeetupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListActiveMeetups not implemented")
}
func (UnimplementedMeetupServiceServer) ListMeetupRequests(context.Context, *ListMeetupRequestsRequest) (*ListMeetupRequestsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMeetupRequests not implemented")
}
func (UnimplementedMeetupServiceServer) RequestToJoin(context.Context, *RequestToJoinRequest) (*MeetupRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestToJoin not implemented")
}
func (UnimplementedMeetupServiceServer) WithdrawRequest(context.Context, *WithdrawRequestRequest) (*WithdrawRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WithdrawRequest not implemented")
}
func (UnimplementedMeetupServiceServer) RespondToRequest(context.Context, *RespondToRequestRequest) (*MeetupRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RespondToRequest not implemented")
}
func (UnimplementedMeetupServiceServer) RegisterDeviceToken(context.Context, *RegisterDeviceTokenRequest) (*RegisterDeviceTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterDeviceToken not implemented")
}
func (UnimplementedMeetupServiceServer) GetSafetyState(context.Context, *GetSafetyStateRequest) (*SafetyStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSafetyState not implemented")
}
func (UnimplementedMeetupServiceServer) AcknowledgeSafetyChecklist(context.Context, *AcknowledgeSafetyChecklistRequest) (*SafetyStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcknowledgeSafetyChecklist not implemented")
}
func (UnimplementedMeetupServiceServer) SetLiveLocationOptIn(context.Context, *SetLiveLocationOptInRequest) (*SafetyStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetLiveLocationOptIn not implemented")
}
func (UnimplementedMeetupServiceServer) ShareWithContacts(context.Context, *ShareWithContactsRequest) (*SafetyStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ShareWithContacts not implemented")
}
func (UnimplementedMeetupServiceServer) CheckIn(context.Context, *CheckInRequest) (*SafetyStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckIn not implemented")
}
func (UnimplementedMeetupServiceServer) DeclineCheckIn(context.Context, *DeclineCheckInRequest) (*SafetyStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeclineCheckIn not implemented")
}
func (UnimplementedMeetupServiceServer) SubmitMeetupFeedback(context.Context, *SubmitMeetupFeedbackRequest) (*SubmitMeetupFeedbackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitMeetupFeedback not implemented")
}
func (UnimplementedMeetupServiceServer) ListRatableParticipants(context.Context, *ListRatableParticipantsRequest) (*ListRatableParticipantsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRatableParticipants not implemented")
}
func (UnimplementedMeetupServiceServer) SubmitRating(context.Context, *SubmitRatingRequest) (*SubmitRatingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitRating not implemented")
}
func (UnimplementedMeetupServiceServer) CloseMeetup(context.Context, *CloseMeetupRequest) (*CloseMeetupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseMeetup not implemented")
}
func (UnimplementedMeetupServiceServer) CancelMeetup(context.Context, *CancelMeetupRequest) (*CancelMeetupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelMeetup not implemented")
}
func (UnimplementedMeetupServiceServer) mustEmbedUnimplementedMeetupServiceServer() {}
func (UnimplementedMeetupServiceServer) testEmbeddedByValue()                       {}

// UnsafeMeetupServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MeetupServiceServer will
// result in compilation errors.
type UnsafeMeetupServiceServer interface {
	mustEmbedUnimplementedMeetupServiceServer()
}

func RegisterMeetupServiceServer(s grpc.ServiceRegistrar, srv MeetupServiceServer) {
	// If the following call panics, it indicates UnimplementedMeetupServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MeetupService_ServiceDesc, srv)
}

func _MeetupService_CreateMeetup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMeetupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetupServiceServer).CreateMeetup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetupService_CreateMeetup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetupServiceServer).CreateMeetup(ctx, req.(*CreateMeetupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetupService_ListOpenMeetups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOpenMeetupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetupServiceServer).ListOpenMeetups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetupService_ListOpenMeetups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetupServiceServer).ListOpenMeetups(ctx, req.(*ListOpenMeetupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetupService_GetMeetup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMeetupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetupServiceServer).GetMeetup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetupService_GetMeetup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetupServiceServer).GetMeetup(ctx, req.(*GetMeetupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetupService_ListMyMeetups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyMeetupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetupServiceServer).ListMyMeetups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetupService_ListMyMeetups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetupServiceServer).ListMyMeetups(ctx, req.(*ListMyMeetupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetupService_ListActiveMeetups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActiveMeetupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetupServiceServer).ListActiveMeetups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetupService_ListActiveMeetups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetupServiceServer).ListActiveMeetups(ctx, req.(*ListActiveMeetupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetupService_ListMeetupRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMeetupRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetupServiceServer).ListMeetupRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetupService_ListMeetupRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetupServiceServer).ListMeetupRequests(ctx, req.(*ListMeetupRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetupService_RequestToJoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestToJoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetupServiceServer).RequestToJoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetupService_RequestToJoin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetupServiceServer).RequestToJoin(ctx, req.(*RequestToJoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetupService_WithdrawRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetupServiceServer).WithdrawRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetupService_WithdrawRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetupServiceServer).WithdrawRequest(ctx, req.(*WithdrawRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetupService_RespondToRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RespondToRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetupServiceServer).RespondToRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetupService_RespondToRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetupServiceServer).RespondToRequest(ctx, req.(*RespondToRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetupService_RegisterDeviceToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDeviceTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetupServiceServer).RegisterDeviceToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetupService_RegisterDeviceToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetupServiceServer).RegisterDeviceToken(ctx, req.(*RegisterDeviceTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetupService_GetSafetyState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSafetyStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetupServiceServer).GetSafetyState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetupService_GetSafetyState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetupServiceServer).GetSafetyState(ctx, req.(*GetSafetyStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetupService_AcknowledgeSafetyChecklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcknowledgeSafetyChecklistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetupServiceServer).AcknowledgeSafetyChecklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetupService_AcknowledgeSafetyChecklist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetupServiceServer).AcknowledgeSafetyChecklist(ctx, req.(*AcknowledgeSafetyChecklistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetupService_SetLiveLocationOptIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetLiveLocationOptInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetupServiceServer).SetLiveLocationOptIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetupService_SetLiveLocationOptIn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetupServiceServer).SetLiveLocationOptIn(ctx, req.(*SetLiveLocationOptInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetupService_ShareWithContacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareWithContactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetupServiceServer).ShareWithContacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetupService_ShareWithContacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetupServiceServer).ShareWithContacts(ctx, req.(*ShareWithContactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetupService_CheckIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetupServiceServer).CheckIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetupService_CheckIn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetupServiceServer).CheckIn(ctx, req.(*CheckInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetupService_DeclineCheckIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeclineCheckInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetupServiceServer).DeclineCheckIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetupService_DeclineCheckIn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetupServiceServer).DeclineCheckIn(ctx, req.(*DeclineCheckInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetupService_SubmitMeetupFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitMeetupFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetupServiceServer).SubmitMeetupFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetupService_SubmitMeetupFeedback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetupServiceServer).SubmitMeetupFeedback(ctx, req.(*SubmitMeetupFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetupService_ListRatableParticipants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRatableParticipantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetupServiceServer).ListRatableParticipants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetupService_ListRatableParticipants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetupServiceServer).ListRatableParticipants(ctx, req.(*ListRatableParticipantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetupService_SubmitRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitRatingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetupServiceServer).SubmitRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetupService_SubmitRating_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetupServiceServer).SubmitRating(ctx, req.(*SubmitRatingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetupService_CloseMeetup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseMeetupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetupServiceServer).CloseMeetup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetupService_CloseMeetup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetupServiceServer).CloseMeetup(ctx, req.(*CloseMeetupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeetupService_CancelMeetup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelMeetupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetupServiceServer).CancelMeetup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeetupService_CancelMeetup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetupServiceServer).CancelMeetup(ctx, req.(*CancelMeetupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MeetupService_ServiceDesc is the grpc.ServiceDesc for MeetupService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MeetupService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "meetup.v1.MeetupService",
	HandlerType: (*MeetupServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMeetup",
			Handler:    _MeetupService_CreateMeetup_Handler,
		},
		{
			MethodName: "ListOpenMeetups",
			Handler:    _MeetupService_ListOpenMeetups_Handler,
		},
		{
			MethodName: "GetMeetup",
			Handler:    _MeetupService_GetMeetup_Handler,
		},
		{
			MethodName: "ListMyMeetups",
			Handler:    _MeetupService_ListMyMeetups_Handler,
		},
		{
			MethodName: "ListActiveMeetups",
			Handler:    _MeetupService_ListActiveMeetups_Handler,
		},
		{
			MethodName: "ListMeetupRequests",
			Handler:    _MeetupService_ListMeetupRequests_Handler,
		},
		{
			MethodName: "RequestToJoin",
			Handler:    _MeetupService_RequestToJoin_Handler,
		},
		{
			MethodName: "WithdrawRequest",
			Handler:    _MeetupService_WithdrawRequest_Handler,
		},
		{
			MethodName: "RespondToRequest",
			Handler:    _MeetupService_RespondToRequest_Handler,
		},
		{
			MethodName: "RegisterDeviceToken",
			Handler:    _MeetupService_RegisterDeviceToken_Handler,
		},
		{
			MethodName: "GetSafetyState",
			Handler:    _MeetupService_GetSafetyState_Handler,
		},
		{
			MethodName: "AcknowledgeSafetyChecklist",
			Handler:    _MeetupService_AcknowledgeSafetyChecklist_Handler,
		},
		{
			MethodName: "SetLiveLocationOptIn",
			Handler:    _MeetupService_SetLiveLocationOptIn_Handler,
		},
		{
			MethodName: "ShareWithContacts",
			Handler:    _MeetupService_ShareWithContacts_Handler,
		},
		{
			MethodName: "CheckIn",
			Handler:    _MeetupService_CheckIn_Handler,
		},
		{
			MethodName: "DeclineCheckIn",
			Handler:    _MeetupService_DeclineCheckIn_Handler,
		},
		{
			MethodName: "SubmitMeetupFeedback",
			Handler:    _MeetupService_SubmitMeetupFeedback_Handler,
		},
		{
			MethodName: "ListRatableParticipants",
			Handler:    _MeetupService_ListRatableParticipants_Handler,
		},
		{
			MethodName: "SubmitRating",
			Handler:    _MeetupService_SubmitRating_Handler,
		},
		{
			MethodName: "CloseMeetup",
			Handler:    _MeetupService_CloseMeetup_Handler,
		},
		{
			MethodName: "CancelMeetup",
			Handler:    _MeetupService_CancelMeetup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "meetup/v1/meetup.proto",
}
