// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device_tokens.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const deleteDeviceToken = `-- name: DeleteDeviceToken :exec
DELETE FROM meetup.device_tokens WHERE fcm_token = $1
`

// Removes a device token FCM has reported as permanently unregistered
// (docs/plans/03-hardening-pass.md §E2c) — app uninstalled, token rotated,
// or wrong Firebase project. Keyed by the token itself, not by user: the
// token identifies one physical device install, and it is the device that
// is gone.
//
// Idempotent: deleting a token that is already gone affects zero rows and is
// not an error. Two concurrent deliveries can both learn the same token is
// dead, and neither should fail because the other got there first.
func (q *Queries) DeleteDeviceToken(ctx context.Context, fcmToken string) error {
	_, err := q.db.Exec(ctx, deleteDeviceToken, fcmToken)
	return err
}

const listDeviceTokensForUser = `-- name: ListDeviceTokensForUser :many
SELECT id, user_id, fcm_token, created_at, updated_at FROM meetup.device_tokens WHERE user_id = $1
`

func (q *Queries) ListDeviceTokensForUser(ctx context.Context, userID uuid.UUID) ([]MeetupDeviceToken, error) {
	rows, err := q.db.Query(ctx, listDeviceTokensForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MeetupDeviceToken
	for rows.Next() {
		var i MeetupDeviceToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FcmToken,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeviceTokensForUsers = `-- name: ListDeviceTokensForUsers :many
SELECT id, user_id, fcm_token, created_at, updated_at FROM meetup.device_tokens WHERE user_id = ANY($1::uuid[])
`

// Batched form of ListDeviceTokensForUser (2026-08-31 round-3 hardening,
// internal/notifications.BatchSender) — one query for all of a fan-out's
// recipients instead of one per recipient. user_id is part of the SELECT
// list (not just fcm_token) so the caller can group rows back by user
// without a second lookup.
func (q *Queries) ListDeviceTokensForUsers(ctx context.Context, userIds []uuid.UUID) ([]MeetupDeviceToken, error) {
	rows, err := q.db.Query(ctx, listDeviceTokensForUsers, userIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MeetupDeviceToken
	for rows.Next() {
		var i MeetupDeviceToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FcmToken,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDeviceToken = `-- name: UpsertDeviceToken :one
INSERT INTO meetup.device_tokens (user_id, fcm_token)
VALUES ($1, $2)
ON CONFLICT (fcm_token) DO UPDATE SET user_id = $1, updated_at = now()
RETURNING id, user_id, fcm_token, created_at, updated_at
`

type UpsertDeviceTokenParams struct {
	UserID   uuid.UUID `json:"user_id"`
	FcmToken string    `json:"fcm_token"`
}

// Upserts by token, not by user — a token identifies one physical device
// install; re-registering it under a different account reassigns
// ownership rather than leaving a stale row.
func (q *Queries) UpsertDeviceToken(ctx context.Context, arg UpsertDeviceTokenParams) (MeetupDeviceToken, error) {
	row := q.db.QueryRow(ctx, upsertDeviceToken, arg.UserID, arg.FcmToken)
	var i MeetupDeviceToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FcmToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
