// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feedback.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const upsertMeetupFeedback = `-- name: UpsertMeetupFeedback :one
INSERT INTO meetup.meetup_feedback (meetup_id, user_id, happened, felt_safe, profile_accurate, would_meet_again, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (meetup_id, user_id) DO UPDATE SET
  happened = $3, felt_safe = $4, profile_accurate = $5, would_meet_again = $6, notes = $7, submitted_at = now()
RETURNING meetup_id, user_id, happened, felt_safe, profile_accurate, would_meet_again, submitted_at, notes
`

type UpsertMeetupFeedbackParams struct {
	MeetupID        uuid.UUID   `json:"meetup_id"`
	UserID          uuid.UUID   `json:"user_id"`
	Happened        bool        `json:"happened"`
	FeltSafe        pgtype.Bool `json:"felt_safe"`
	ProfileAccurate pgtype.Bool `json:"profile_accurate"`
	WouldMeetAgain  pgtype.Bool `json:"would_meet_again"`
	Notes           pgtype.Text `json:"notes"`
}

func (q *Queries) UpsertMeetupFeedback(ctx context.Context, arg UpsertMeetupFeedbackParams) (MeetupMeetupFeedback, error) {
	row := q.db.QueryRow(ctx, upsertMeetupFeedback,
		arg.MeetupID,
		arg.UserID,
		arg.Happened,
		arg.FeltSafe,
		arg.ProfileAccurate,
		arg.WouldMeetAgain,
		arg.Notes,
	)
	var i MeetupMeetupFeedback
	err := row.Scan(
		&i.MeetupID,
		&i.UserID,
		&i.Happened,
		&i.FeltSafe,
		&i.ProfileAccurate,
		&i.WouldMeetAgain,
		&i.SubmittedAt,
		&i.Notes,
	)
	return i, err
}
