// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feedback.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getMeetupFeedback = `-- name: GetMeetupFeedback :one
SELECT meetup_id, user_id, happened, felt_safe, profile_accurate, would_meet_again, submitted_at, notes, overall_score, review_completed_at FROM meetup.meetup_feedback WHERE meetup_id = $1 AND user_id = $2
`

type GetMeetupFeedbackParams struct {
	MeetupID uuid.UUID `json:"meetup_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) GetMeetupFeedback(ctx context.Context, arg GetMeetupFeedbackParams) (MeetupMeetupFeedback, error) {
	row := q.db.QueryRow(ctx, getMeetupFeedback, arg.MeetupID, arg.UserID)
	var i MeetupMeetupFeedback
	err := row.Scan(
		&i.MeetupID,
		&i.UserID,
		&i.Happened,
		&i.FeltSafe,
		&i.ProfileAccurate,
		&i.WouldMeetAgain,
		&i.SubmittedAt,
		&i.Notes,
		&i.OverallScore,
		&i.ReviewCompletedAt,
	)
	return i, err
}

const listMeetupIDsAwaitingReview = `-- name: ListMeetupIDsAwaitingReview :many
SELECT m.id
FROM meetup.meetups m
LEFT JOIN meetup.meetup_feedback f ON f.meetup_id = m.id AND f.user_id = $1
WHERE m.window_end <= now()
  AND m.window_end > $2
  AND m.status <> 'cancelled'
  AND f.review_completed_at IS NULL
  AND (
    m.host_user_id = $1
    OR EXISTS (
      SELECT 1 FROM meetup.meetup_requests r
      WHERE r.meetup_id = m.id AND r.requester_id = $1 AND r.status = 'accepted'
    )
  )
`

type ListMeetupIDsAwaitingReviewParams struct {
	UserID uuid.UUID          `json:"user_id"`
	Cutoff pgtype.Timestamptz `json:"cutoff"`
}

// Meetups this user took part in whose window has ended and which they have
// not finished reviewing. Bounded by a cutoff so an ignored review does not
// sit on Home forever (see service.reviewWindow).
func (q *Queries) ListMeetupIDsAwaitingReview(ctx context.Context, arg ListMeetupIDsAwaitingReviewParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listMeetupIDsAwaitingReview, arg.UserID, arg.Cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMeetupOverallReview = `-- name: SetMeetupOverallReview :one
INSERT INTO meetup.meetup_feedback (meetup_id, user_id, happened, overall_score, notes, review_completed_at)
VALUES ($1, $2, true, $3, $4, now())
ON CONFLICT (meetup_id, user_id) DO UPDATE SET
  happened = true,
  overall_score = $3,
  notes = COALESCE($4, meetup.meetup_feedback.notes),
  review_completed_at = now(),
  submitted_at = now()
RETURNING meetup_id, user_id, happened, felt_safe, profile_accurate, would_meet_again, submitted_at, notes, overall_score, review_completed_at
`

type SetMeetupOverallReviewParams struct {
	MeetupID     uuid.UUID   `json:"meetup_id"`
	UserID       uuid.UUID   `json:"user_id"`
	OverallScore pgtype.Int2 `json:"overall_score"`
	Notes        pgtype.Text `json:"notes"`
}

// The review flow's own write: the overall 1-5 for the meetup plus the
// optional note, and the completion stamp. Separate from
// UpsertMeetupFeedback (the safety questions) because the two are answered
// at different moments by different screens, and a review must never
// silently clear a felt_safe answer given earlier.
//
// happened is forced true: reaching the end of the review flow IS the
// statement that it happened, and leaving it null would make the row fail
// HasConfirmedMeetupHappened and so refuse the very ratings being submitted
// alongside it.
func (q *Queries) SetMeetupOverallReview(ctx context.Context, arg SetMeetupOverallReviewParams) (MeetupMeetupFeedback, error) {
	row := q.db.QueryRow(ctx, setMeetupOverallReview,
		arg.MeetupID,
		arg.UserID,
		arg.OverallScore,
		arg.Notes,
	)
	var i MeetupMeetupFeedback
	err := row.Scan(
		&i.MeetupID,
		&i.UserID,
		&i.Happened,
		&i.FeltSafe,
		&i.ProfileAccurate,
		&i.WouldMeetAgain,
		&i.SubmittedAt,
		&i.Notes,
		&i.OverallScore,
		&i.ReviewCompletedAt,
	)
	return i, err
}

const upsertMeetupFeedback = `-- name: UpsertMeetupFeedback :one
INSERT INTO meetup.meetup_feedback (meetup_id, user_id, happened, felt_safe, profile_accurate, would_meet_again, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (meetup_id, user_id) DO UPDATE SET
  happened = $3, felt_safe = $4, profile_accurate = $5, would_meet_again = $6, notes = $7, submitted_at = now()
RETURNING meetup_id, user_id, happened, felt_safe, profile_accurate, would_meet_again, submitted_at, notes, overall_score, review_completed_at
`

type UpsertMeetupFeedbackParams struct {
	MeetupID        uuid.UUID   `json:"meetup_id"`
	UserID          uuid.UUID   `json:"user_id"`
	Happened        bool        `json:"happened"`
	FeltSafe        pgtype.Bool `json:"felt_safe"`
	ProfileAccurate pgtype.Bool `json:"profile_accurate"`
	WouldMeetAgain  pgtype.Bool `json:"would_meet_again"`
	Notes           pgtype.Text `json:"notes"`
}

func (q *Queries) UpsertMeetupFeedback(ctx context.Context, arg UpsertMeetupFeedbackParams) (MeetupMeetupFeedback, error) {
	row := q.db.QueryRow(ctx, upsertMeetupFeedback,
		arg.MeetupID,
		arg.UserID,
		arg.Happened,
		arg.FeltSafe,
		arg.ProfileAccurate,
		arg.WouldMeetAgain,
		arg.Notes,
	)
	var i MeetupMeetupFeedback
	err := row.Scan(
		&i.MeetupID,
		&i.UserID,
		&i.Happened,
		&i.FeltSafe,
		&i.ProfileAccurate,
		&i.WouldMeetAgain,
		&i.SubmittedAt,
		&i.Notes,
		&i.OverallScore,
		&i.ReviewCompletedAt,
	)
	return i, err
}
