// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: meetups_completed_outbox.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimMeetupsCompletedOutboxBatch = `-- name: ClaimMeetupsCompletedOutboxBatch :many
UPDATE meetup.meetups_completed_outbox
SET attempts = attempts + 1,
    next_attempt_at = now() + $1::interval
WHERE id IN (
  SELECT id FROM meetup.meetups_completed_outbox
  WHERE processed_at IS NULL
    AND dead_lettered_at IS NULL
    AND next_attempt_at <= now()
  ORDER BY next_attempt_at
  LIMIT $2
  FOR UPDATE SKIP LOCKED
)
RETURNING id, meetup_ids, attempts
`

type ClaimMeetupsCompletedOutboxBatchParams struct {
	VisibilityTimeout pgtype.Interval `json:"visibility_timeout"`
	BatchSize         int32           `json:"batch_size"`
}

type ClaimMeetupsCompletedOutboxBatchRow struct {
	ID        uuid.UUID   `json:"id"`
	MeetupIds []uuid.UUID `json:"meetup_ids"`
	Attempts  int32       `json:"attempts"`
}

// Claims up to batch_size due rows. Deliberately IDENTICAL in shape to
// ClaimNotificationOutboxBatch — the proven claiming strategy, not a second
// design.
//
// It is an UPDATE rather than a SELECT ... FOR UPDATE SKIP LOCKED held for
// the duration of processing, for the same reason as the notification
// version: stamping next_attempt_at into the future gives each claimed row a
// VISIBILITY TIMEOUT, so it leaves the claimable set the instant this
// commits and a second poller skips it without needing to know who is
// working on it. Crash recovery follows for free — a claimer that dies
// records no outcome, and the row becomes due again when the timeout lapses.
// No lease table, no stuck-claim reaper.
//
// (The notification version's stronger motivation — never hold a Postgres
// transaction open across a third-party HTTP call — does not apply here,
// since this processing is database-only. The pattern is kept anyway: the
// concurrency guarantees are the ones that matter, an earlier draft of the
// notification query that released the lock WITHOUT the stamp was caught by
// its concurrency test claiming rows two and three times, and having one
// claiming strategy in this codebase rather than two is worth more than
// micro-optimising the second one.)
//
// attempts is incremented at CLAIM time, not on failure, so a row that
// crashes its claimer mid-flight still counts against the retry ceiling
// instead of being retried forever. MarkMeetupsCompletedFailed therefore
// sets the backoff deadline without incrementing again.
//
// ORDER BY next_attempt_at matches idx_meetups_completed_outbox_claimable.
func (q *Queries) ClaimMeetupsCompletedOutboxBatch(ctx context.Context, arg ClaimMeetupsCompletedOutboxBatchParams) ([]ClaimMeetupsCompletedOutboxBatchRow, error) {
	rows, err := q.db.Query(ctx, claimMeetupsCompletedOutboxBatch, arg.VisibilityTimeout, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimMeetupsCompletedOutboxBatchRow
	for rows.Next() {
		var i ClaimMeetupsCompletedOutboxBatchRow
		if err := rows.Scan(&i.ID, &i.MeetupIds, &i.Attempts); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countPendingMeetupsCompleted = `-- name: CountPendingMeetupsCompleted :one
SELECT count(*) FROM meetup.meetups_completed_outbox
WHERE processed_at IS NULL AND dead_lettered_at IS NULL
`

// Backs the pending gauge. Same predicate as the claimable partial index, so
// it is an index-only scan over the pending set rather than a table scan.
func (q *Queries) CountPendingMeetupsCompleted(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingMeetupsCompleted)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteDeadLetteredMeetupsCompleted = `-- name: DeleteDeadLetteredMeetupsCompleted :execrows
DELETE FROM meetup.meetups_completed_outbox
WHERE id IN (
  SELECT id FROM meetup.meetups_completed_outbox
  WHERE dead_lettered_at IS NOT NULL AND dead_lettered_at < $1::timestamptz
  LIMIT $2
)
`

type DeleteDeadLetteredMeetupsCompletedParams struct {
	OlderThan pgtype.Timestamptz `json:"older_than"`
	BatchSize int32              `json:"batch_size"`
}

// Retention for dead-lettered rows, kept longer than successes on purpose.
func (q *Queries) DeleteDeadLetteredMeetupsCompleted(ctx context.Context, arg DeleteDeadLetteredMeetupsCompletedParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDeadLetteredMeetupsCompleted, arg.OlderThan, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProcessedMeetupsCompleted = `-- name: DeleteProcessedMeetupsCompleted :execrows
DELETE FROM meetup.meetups_completed_outbox
WHERE id IN (
  SELECT id FROM meetup.meetups_completed_outbox
  WHERE processed_at IS NOT NULL AND processed_at < $1::timestamptz
  LIMIT $2
)
`

type DeleteProcessedMeetupsCompletedParams struct {
	OlderThan pgtype.Timestamptz `json:"older_than"`
	BatchSize int32              `json:"batch_size"`
}

// Retention for done rows, batched via the id subquery rather than one
// unbounded DELETE — same reasoning as DeleteProcessedNotifications. The
// caller loops until a batch comes back short.
func (q *Queries) DeleteProcessedMeetupsCompleted(ctx context.Context, arg DeleteProcessedMeetupsCompletedParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProcessedMeetupsCompleted, arg.OlderThan, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enqueueMeetupsCompleted = `-- name: EnqueueMeetupsCompleted :exec
INSERT INTO meetup.meetups_completed_outbox (meetup_ids)
VALUES ($1::uuid[])
`

// The outbox insert, executed on the SAME transaction handle as the close or
// the auto-close claim it accompanies. That co-location is the entire point,
// exactly as with EnqueueNotification: the completion and the record of
// "someone must recompute totals for these" either both commit or neither
// does. There is no window in which a meetup is completed but its recompute
// was never scheduled.
//
// Cheap by construction — one INSERT of an array of ids — which is what
// takes the expensive recompute off the closing transaction.
func (q *Queries) EnqueueMeetupsCompleted(ctx context.Context, meetupIds []uuid.UUID) error {
	_, err := q.db.Exec(ctx, enqueueMeetupsCompleted, meetupIds)
	return err
}

const markMeetupsCompletedDeadLettered = `-- name: MarkMeetupsCompletedDeadLettered :exec
UPDATE meetup.meetups_completed_outbox
SET dead_lettered_at = now(),
    last_error = $1
WHERE id = $2
`

type MarkMeetupsCompletedDeadLetteredParams struct {
	LastError pgtype.Text `json:"last_error"`
	ID        uuid.UUID   `json:"id"`
}

// Terminal. Leaves the claimable partial index and is never attempted again,
// but the row is kept: a permanent failure here means some users' profile
// counts are silently stale, which is exactly the thing someone should be
// able to find and fix.
func (q *Queries) MarkMeetupsCompletedDeadLettered(ctx context.Context, arg MarkMeetupsCompletedDeadLetteredParams) error {
	_, err := q.db.Exec(ctx, markMeetupsCompletedDeadLettered, arg.LastError, arg.ID)
	return err
}

const markMeetupsCompletedFailed = `-- name: MarkMeetupsCompletedFailed :exec
UPDATE meetup.meetups_completed_outbox
SET next_attempt_at = $1::timestamptz,
    last_error = $2
WHERE id = $3
`

type MarkMeetupsCompletedFailedParams struct {
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	LastError     pgtype.Text        `json:"last_error"`
	ID            uuid.UUID          `json:"id"`
}

// A retryable failure: pull next_attempt_at back from the visibility timeout
// to the real backoff deadline and record why. processed_at is untouched, so
// the row stays pending by construction. attempts is NOT incremented here —
// the claim already did that.
func (q *Queries) MarkMeetupsCompletedFailed(ctx context.Context, arg MarkMeetupsCompletedFailedParams) error {
	_, err := q.db.Exec(ctx, markMeetupsCompletedFailed, arg.NextAttemptAt, arg.LastError, arg.ID)
	return err
}

const markMeetupsCompletedProcessed = `-- name: MarkMeetupsCompletedProcessed :exec
UPDATE meetup.meetups_completed_outbox
SET processed_at = now(), last_error = NULL
WHERE id = $1
`

// The only statement that ever writes processed_at.
func (q *Queries) MarkMeetupsCompletedProcessed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markMeetupsCompletedProcessed, id)
	return err
}
