// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: meetups.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelMeetup = `-- name: CancelMeetup :one
UPDATE meetup.meetups SET status = 'cancelled', cancelled_at = now(), cancellation_reason = $2
WHERE id = $1 AND host_user_id = $3
RETURNING id, host_user_id, intent, location_lat, location_lng, location_label, capacity, status, created_at, cancelled_at, window_start, window_end, closed_at, cancellation_reason, starting_soon_notified_at, location
`

type CancelMeetupParams struct {
	ID                 uuid.UUID   `json:"id"`
	CancellationReason pgtype.Text `json:"cancellation_reason"`
	HostUserID         uuid.UUID   `json:"host_user_id"`
}

// reason is required (validated by the service layer, ADR-020 §3) —
// accepted participants are notified and gain a new rating-eligibility
// path against the host, both handled in the service layer after this
// write commits. host_user_id scoping (Round 11, docs/00-project/
// action-tracker.md § 4b-26) is defense-in-depth alongside the existing
// Go-level ownership check in service.go's CancelMeetup — mirrors
// CloseMeetup's own ownership clause exactly; the Go-level check stays,
// this doesn't replace it.
func (q *Queries) CancelMeetup(ctx context.Context, arg CancelMeetupParams) (MeetupMeetup, error) {
	row := q.db.QueryRow(ctx, cancelMeetup, arg.ID, arg.CancellationReason, arg.HostUserID)
	var i MeetupMeetup
	err := row.Scan(
		&i.ID,
		&i.HostUserID,
		&i.Intent,
		&i.LocationLat,
		&i.LocationLng,
		&i.LocationLabel,
		&i.Capacity,
		&i.Status,
		&i.CreatedAt,
		&i.CancelledAt,
		&i.WindowStart,
		&i.WindowEnd,
		&i.ClosedAt,
		&i.CancellationReason,
		&i.StartingSoonNotifiedAt,
		&i.Location,
	)
	return i, err
}

const claimMeetupsStartingSoon = `-- name: ClaimMeetupsStartingSoon :many
UPDATE meetup.meetups SET starting_soon_notified_at = now()
WHERE id IN (
  SELECT id FROM meetup.meetups
  WHERE status IN ('open', 'full')
    AND window_start - now() <= interval '30 minutes'
    AND window_start > now()
    AND starting_soon_notified_at IS NULL
  ORDER BY window_start
  LIMIT $1
  FOR UPDATE SKIP LOCKED
)
RETURNING id, host_user_id, intent, location_lat, location_lng, location_label, capacity, status, created_at, cancelled_at, window_start, window_end, closed_at, cancellation_reason, starting_soon_notified_at, location
`

// The lifecycle poller's starting-soon sweep (ADR-025 §4), reshaped into an
// atomic CLAIM (docs/plans/03-hardening-pass.md §C2).
//
// WHAT CHANGED AND WHY: this used to be a plain SELECT of candidates, with
// the de-dup guard (starting_soon_notified_at) set afterwards, per row, once
// the notification had been sent. That is correct for exactly one poller. It
// is not correct for two — and horizontally scaling cmd/monolith for
// throughput is a realistic near-term move. Two pollers ticking within the
// same window would both SELECT the same rows before either wrote the guard,
// and every host and participant would get the reminder twice.
//
// Selecting and marking in ONE statement removes that window entirely: the
// inner SELECT takes row locks with FOR UPDATE SKIP LOCKED, so a second
// poller running concurrently skips the locked rows rather than waiting for
// them and then re-processing, and the UPDATE stamps the guard before the
// transaction that claimed them can be observed by anyone else. RETURNING
// hands back exactly the rows this caller now owns.
//
// The trade-off this makes deliberately: the guard is set BEFORE the
// notification is composed rather than after, so a crash between claim and
// notify loses that reminder. That is acceptable precisely because the
// caller enqueues the notification into meetup.notification_outbox inside
// THIS SAME TRANSACTION (§F3) — the claim and the queued notification commit
// together, so there is no state where a meetup is marked notified but the
// notification does not exist.
func (q *Queries) ClaimMeetupsStartingSoon(ctx context.Context, batchSize int32) ([]MeetupMeetup, error) {
	rows, err := q.db.Query(ctx, claimMeetupsStartingSoon, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MeetupMeetup
	for rows.Next() {
		var i MeetupMeetup
		if err := rows.Scan(
			&i.ID,
			&i.HostUserID,
			&i.Intent,
			&i.LocationLat,
			&i.LocationLng,
			&i.LocationLabel,
			&i.Capacity,
			&i.Status,
			&i.CreatedAt,
			&i.CancelledAt,
			&i.WindowStart,
			&i.WindowEnd,
			&i.ClosedAt,
			&i.CancellationReason,
			&i.StartingSoonNotifiedAt,
			&i.Location,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimMeetupsToAutoClose = `-- name: ClaimMeetupsToAutoClose :many
UPDATE meetup.meetups
SET status = 'completed', closed_at = now()
WHERE id IN (
  SELECT id FROM meetup.meetups
  WHERE status IN ('open', 'full') AND now() >= window_end
  ORDER BY window_end
  LIMIT $1
  FOR UPDATE SKIP LOCKED
)
RETURNING id, host_user_id, intent, location_lat, location_lng, location_label, capacity, status, created_at, cancelled_at, window_start, window_end, closed_at, cancellation_reason, starting_soon_notified_at, location
`

// The lifecycle poller's auto-close sweep (ADR-025 §4), same reshaping and
// the same reasoning as ClaimMeetupsStartingSoon above (§C2).
//
// The previous shape (SELECT candidates, then a per-row conditional UPDATE)
// already prevented double-CLOSING — the UPDATE's own WHERE clause re-checked
// eligibility, so a second closer simply affected zero rows. What it did NOT
// prevent was duplicate NOTIFICATION: both pollers read the same candidate,
// both then went on to notify the host and every participant, and only one
// of them lost the race on the UPDATE it had already sent pushes for. Claiming
// with FOR UPDATE SKIP LOCKED means the second poller never sees the row at
// all.
//
// status/window_end are still both re-checked here rather than trusted from
// a prior read, so a concurrent manual CloseMeetup on the same row is
// resolved by the database rather than by ordering assumptions.
func (q *Queries) ClaimMeetupsToAutoClose(ctx context.Context, batchSize int32) ([]MeetupMeetup, error) {
	rows, err := q.db.Query(ctx, claimMeetupsToAutoClose, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MeetupMeetup
	for rows.Next() {
		var i MeetupMeetup
		if err := rows.Scan(
			&i.ID,
			&i.HostUserID,
			&i.Intent,
			&i.LocationLat,
			&i.LocationLng,
			&i.LocationLabel,
			&i.Capacity,
			&i.Status,
			&i.CreatedAt,
			&i.CancelledAt,
			&i.WindowStart,
			&i.WindowEnd,
			&i.ClosedAt,
			&i.CancellationReason,
			&i.StartingSoonNotifiedAt,
			&i.Location,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const closeMeetup = `-- name: CloseMeetup :one
UPDATE meetup.meetups
SET status = 'completed', closed_at = now()
WHERE id = $1 AND host_user_id = $2 AND status IN ('open', 'full') AND now() >= window_start
RETURNING id, host_user_id, intent, location_lat, location_lng, location_label, capacity, status, created_at, cancelled_at, window_start, window_end, closed_at, cancellation_reason, starting_soon_notified_at, location
`

type CloseMeetupParams struct {
	ID         uuid.UUID `json:"id"`
	HostUserID uuid.UUID `json:"host_user_id"`
}

// The WHERE clause's four conditions (right meetup, right host, currently
// open-ish, window actually started) are the *entire* authorization and
// precondition check — done in the query itself so there's no window
// between "check" and "act" for a concurrent request to slip through
// (ADR-016). Zero rows updated (vs. an error) means one of those four
// failed; the service layer re-fetches to distinguish which for a useful
// error message.
func (q *Queries) CloseMeetup(ctx context.Context, arg CloseMeetupParams) (MeetupMeetup, error) {
	row := q.db.QueryRow(ctx, closeMeetup, arg.ID, arg.HostUserID)
	var i MeetupMeetup
	err := row.Scan(
		&i.ID,
		&i.HostUserID,
		&i.Intent,
		&i.LocationLat,
		&i.LocationLng,
		&i.LocationLabel,
		&i.Capacity,
		&i.Status,
		&i.CreatedAt,
		&i.CancelledAt,
		&i.WindowStart,
		&i.WindowEnd,
		&i.ClosedAt,
		&i.CancellationReason,
		&i.StartingSoonNotifiedAt,
		&i.Location,
	)
	return i, err
}

const createMeetup = `-- name: CreateMeetup :one
INSERT INTO meetup.meetups (host_user_id, intent, window_start, window_end, location_lat, location_lng, location_label, capacity)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, host_user_id, intent, location_lat, location_lng, location_label, capacity, status, created_at, cancelled_at, window_start, window_end, closed_at, cancellation_reason, starting_soon_notified_at, location
`

type CreateMeetupParams struct {
	HostUserID    uuid.UUID          `json:"host_user_id"`
	Intent        MeetupIntentType   `json:"intent"`
	WindowStart   pgtype.Timestamptz `json:"window_start"`
	WindowEnd     pgtype.Timestamptz `json:"window_end"`
	LocationLat   float64            `json:"location_lat"`
	LocationLng   float64            `json:"location_lng"`
	LocationLabel string             `json:"location_label"`
	Capacity      int16              `json:"capacity"`
}

func (q *Queries) CreateMeetup(ctx context.Context, arg CreateMeetupParams) (MeetupMeetup, error) {
	row := q.db.QueryRow(ctx, createMeetup,
		arg.HostUserID,
		arg.Intent,
		arg.WindowStart,
		arg.WindowEnd,
		arg.LocationLat,
		arg.LocationLng,
		arg.LocationLabel,
		arg.Capacity,
	)
	var i MeetupMeetup
	err := row.Scan(
		&i.ID,
		&i.HostUserID,
		&i.Intent,
		&i.LocationLat,
		&i.LocationLng,
		&i.LocationLabel,
		&i.Capacity,
		&i.Status,
		&i.CreatedAt,
		&i.CancelledAt,
		&i.WindowStart,
		&i.WindowEnd,
		&i.ClosedAt,
		&i.CancellationReason,
		&i.StartingSoonNotifiedAt,
		&i.Location,
	)
	return i, err
}

const getMeetupByID = `-- name: GetMeetupByID :one
SELECT
  m.id, m.host_user_id, m.intent, m.location_lat, m.location_lng, m.location_label, m.capacity, m.status, m.created_at, m.cancelled_at, m.window_start, m.window_end, m.closed_at, m.cancellation_reason, m.starting_soon_notified_at, m.location,
  COALESCE(u.full_name, '') AS host_full_name,
  u.profile_photo_url AS host_profile_photo_url,
  COALESCE(u.trust_level, 0) AS host_trust_level,
  COALESCE(ratings.rating_average, 0)::numeric(3,2) AS host_rating_average,
  COALESCE(ratings.rating_count, 0)::int AS host_rating_count,
  (SELECT count(*) FROM meetup.meetup_requests r2 WHERE r2.meetup_id = m.id AND r2.status = 'accepted') AS accepted_count,
  r.status AS my_request_status,
  -- Added for the requester-side withdraw action (ADR-020 §4) — WithdrawRequest
  -- takes a request id, and this was the only Meetup-shaped query the
  -- viewer's own request id wasn't already available on for free (it's
  -- just r.id, the same LEFT JOINed row my_request_status already reads).
  r.id AS my_request_id
FROM meetup.meetups m
LEFT JOIN meetup.user_display_cache u ON u.user_id = m.host_user_id
LEFT JOIN LATERAL (
  SELECT ROUND(AVG(score), 2) AS rating_average, count(*) AS rating_count
  FROM meetup.meetup_user_ratings mr WHERE mr.rated_user_id = m.host_user_id
) ratings ON true
LEFT JOIN meetup.meetup_requests r ON r.meetup_id = m.id AND r.requester_id = $2
WHERE m.id = $1
ORDER BY r.created_at DESC NULLS LAST
LIMIT 1
`

type GetMeetupByIDParams struct {
	ID          uuid.UUID `json:"id"`
	RequesterID uuid.UUID `json:"requester_id"`
}

type GetMeetupByIDRow struct {
	ID                     uuid.UUID                     `json:"id"`
	HostUserID             uuid.UUID                     `json:"host_user_id"`
	Intent                 MeetupIntentType              `json:"intent"`
	LocationLat            float64                       `json:"location_lat"`
	LocationLng            float64                       `json:"location_lng"`
	LocationLabel          string                        `json:"location_label"`
	Capacity               int16                         `json:"capacity"`
	Status                 MeetupMeetupStatus            `json:"status"`
	CreatedAt              pgtype.Timestamptz            `json:"created_at"`
	CancelledAt            pgtype.Timestamptz            `json:"cancelled_at"`
	WindowStart            pgtype.Timestamptz            `json:"window_start"`
	WindowEnd              pgtype.Timestamptz            `json:"window_end"`
	ClosedAt               pgtype.Timestamptz            `json:"closed_at"`
	CancellationReason     pgtype.Text                   `json:"cancellation_reason"`
	StartingSoonNotifiedAt pgtype.Timestamptz            `json:"starting_soon_notified_at"`
	Location               interface{}                   `json:"location"`
	HostFullName           string                        `json:"host_full_name"`
	HostProfilePhotoUrl    pgtype.Text                   `json:"host_profile_photo_url"`
	HostTrustLevel         int16                         `json:"host_trust_level"`
	HostRatingAverage      pgtype.Numeric                `json:"host_rating_average"`
	HostRatingCount        int32                         `json:"host_rating_count"`
	AcceptedCount          int64                         `json:"accepted_count"`
	MyRequestStatus        NullMeetupMeetupRequestStatus `json:"my_request_status"`
	MyRequestID            pgtype.UUID                   `json:"my_request_id"`
}

// my_request_status is the *latest* request this specific user (viewerID)
// has made on this meetup, or NULL if they never requested — the frontend
// uses this to render "REQUEST TO JOIN" vs. the request's current status
// (frontend/meetup-scheduling-PLAN.md Step 3). Plain LEFT JOIN + ORDER BY
// ... LIMIT 1, not a scalar subquery or LEFT JOIN LATERAL in the SELECT
// list — sqlc's nullability analysis correctly infers a plain LEFT JOIN
// column as nullable (NullMeetupRequestStatus); both of the other two forms
// were confirmed (by generating each and inspecting the output) to produce
// a non-nullable Go type that would panic scanning a real NULL row — a
// viewer who's never requested to join, the common browsing case.
//
// Host display info comes from user_display_cache, not a live JOIN users
// (ADR-017's addendum — users is a different database now). LEFT JOIN, not
// JOIN — deliberately, a deviation from the plan's literal "same shape":
// user_display_cache has no FK to enforce a row exists, and is populated
// asynchronously by a Pub/Sub consumer (Step 6), so a meetup hosted by a
// just-onboarded user could briefly have no cache row yet. An inner JOIN
// would make such a meetup vanish from GetMeetupByID/listings entirely
// until the consumer catches up; LEFT JOIN + COALESCE just shows blank
// display fields for that brief window instead — the meetup itself is
// never at risk of disappearing due to eventual-consistency lag.
//
// rating_average/rating_count are a live aggregate over this service's own
// meetup_user_ratings, not a cached column (Step 4's note: "meetup already
// has them locally... nothing to cache back to itself") — cross-joined via
// a LATERAL subquery so an unrated host correctly gets 0/0 rather than
// disappearing from a plain JOIN.
func (q *Queries) GetMeetupByID(ctx context.Context, arg GetMeetupByIDParams) (GetMeetupByIDRow, error) {
	row := q.db.QueryRow(ctx, getMeetupByID, arg.ID, arg.RequesterID)
	var i GetMeetupByIDRow
	err := row.Scan(
		&i.ID,
		&i.HostUserID,
		&i.Intent,
		&i.LocationLat,
		&i.LocationLng,
		&i.LocationLabel,
		&i.Capacity,
		&i.Status,
		&i.CreatedAt,
		&i.CancelledAt,
		&i.WindowStart,
		&i.WindowEnd,
		&i.ClosedAt,
		&i.CancellationReason,
		&i.StartingSoonNotifiedAt,
		&i.Location,
		&i.HostFullName,
		&i.HostProfilePhotoUrl,
		&i.HostTrustLevel,
		&i.HostRatingAverage,
		&i.HostRatingCount,
		&i.AcceptedCount,
		&i.MyRequestStatus,
		&i.MyRequestID,
	)
	return i, err
}

const getMeetupByIDForUpdate = `-- name: GetMeetupByIDForUpdate :one
SELECT id, host_user_id, intent, location_lat, location_lng, location_label, capacity, status, created_at, cancelled_at, window_start, window_end, closed_at, cancellation_reason, starting_soon_notified_at, location FROM meetup.meetups WHERE id = $1 FOR UPDATE
`

// Plain, no join — used only inside AcceptRequest's transaction to lock the
// row and re-check status/capacity, host display info is irrelevant there.
func (q *Queries) GetMeetupByIDForUpdate(ctx context.Context, id uuid.UUID) (MeetupMeetup, error) {
	row := q.db.QueryRow(ctx, getMeetupByIDForUpdate, id)
	var i MeetupMeetup
	err := row.Scan(
		&i.ID,
		&i.HostUserID,
		&i.Intent,
		&i.LocationLat,
		&i.LocationLng,
		&i.LocationLabel,
		&i.Capacity,
		&i.Status,
		&i.CreatedAt,
		&i.CancelledAt,
		&i.WindowStart,
		&i.WindowEnd,
		&i.ClosedAt,
		&i.CancellationReason,
		&i.StartingSoonNotifiedAt,
		&i.Location,
	)
	return i, err
}

const listMeetupsByHostAfterCursor = `-- name: ListMeetupsByHostAfterCursor :many
SELECT
  m.id, m.host_user_id, m.intent, m.location_lat, m.location_lng, m.location_label, m.capacity, m.status, m.created_at, m.cancelled_at, m.window_start, m.window_end, m.closed_at, m.cancellation_reason, m.starting_soon_notified_at, m.location,
  COALESCE(u.full_name, '') AS host_full_name,
  u.profile_photo_url AS host_profile_photo_url,
  COALESCE(u.trust_level, 0) AS host_trust_level,
  COALESCE(ratings.rating_average, 0)::numeric(3,2) AS host_rating_average,
  COALESCE(ratings.rating_count, 0)::int AS host_rating_count,
  (SELECT count(*) FROM meetup.meetup_requests r WHERE r.meetup_id = m.id AND r.status = 'accepted') AS accepted_count
FROM meetup.meetups m
LEFT JOIN meetup.user_display_cache u ON u.user_id = m.host_user_id
LEFT JOIN LATERAL (
  SELECT ROUND(AVG(score), 2) AS rating_average, count(*) AS rating_count
  FROM meetup.meetup_user_ratings mr WHERE mr.rated_user_id = m.host_user_id
) ratings ON true
WHERE m.host_user_id = $1
  AND (m.created_at, m.id) < ($3::timestamptz, $4::uuid)
ORDER BY m.created_at DESC, m.id DESC
LIMIT $2
`

type ListMeetupsByHostAfterCursorParams struct {
	HostUserID      uuid.UUID          `json:"host_user_id"`
	Limit           int32              `json:"limit"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        uuid.UUID          `json:"cursor_id"`
}

type ListMeetupsByHostAfterCursorRow struct {
	ID                     uuid.UUID          `json:"id"`
	HostUserID             uuid.UUID          `json:"host_user_id"`
	Intent                 MeetupIntentType   `json:"intent"`
	LocationLat            float64            `json:"location_lat"`
	LocationLng            float64            `json:"location_lng"`
	LocationLabel          string             `json:"location_label"`
	Capacity               int16              `json:"capacity"`
	Status                 MeetupMeetupStatus `json:"status"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	CancelledAt            pgtype.Timestamptz `json:"cancelled_at"`
	WindowStart            pgtype.Timestamptz `json:"window_start"`
	WindowEnd              pgtype.Timestamptz `json:"window_end"`
	ClosedAt               pgtype.Timestamptz `json:"closed_at"`
	CancellationReason     pgtype.Text        `json:"cancellation_reason"`
	StartingSoonNotifiedAt pgtype.Timestamptz `json:"starting_soon_notified_at"`
	Location               interface{}        `json:"location"`
	HostFullName           string             `json:"host_full_name"`
	HostProfilePhotoUrl    pgtype.Text        `json:"host_profile_photo_url"`
	HostTrustLevel         int16              `json:"host_trust_level"`
	HostRatingAverage      pgtype.Numeric     `json:"host_rating_average"`
	HostRatingCount        int32              `json:"host_rating_count"`
	AcceptedCount          int64              `json:"accepted_count"`
}

// Keyset continuation of ListMeetupsByHostFirstPage — same
// (created_at, id) < (cursor) shape as
// ListOpenMeetupsByIntentAfterCursor.
func (q *Queries) ListMeetupsByHostAfterCursor(ctx context.Context, arg ListMeetupsByHostAfterCursorParams) ([]ListMeetupsByHostAfterCursorRow, error) {
	rows, err := q.db.Query(ctx, listMeetupsByHostAfterCursor,
		arg.HostUserID,
		arg.Limit,
		arg.CursorCreatedAt,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMeetupsByHostAfterCursorRow
	for rows.Next() {
		var i ListMeetupsByHostAfterCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.HostUserID,
			&i.Intent,
			&i.LocationLat,
			&i.LocationLng,
			&i.LocationLabel,
			&i.Capacity,
			&i.Status,
			&i.CreatedAt,
			&i.CancelledAt,
			&i.WindowStart,
			&i.WindowEnd,
			&i.ClosedAt,
			&i.CancellationReason,
			&i.StartingSoonNotifiedAt,
			&i.Location,
			&i.HostFullName,
			&i.HostProfilePhotoUrl,
			&i.HostTrustLevel,
			&i.HostRatingAverage,
			&i.HostRatingCount,
			&i.AcceptedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMeetupsByHostFirstPage = `-- name: ListMeetupsByHostFirstPage :many
SELECT
  m.id, m.host_user_id, m.intent, m.location_lat, m.location_lng, m.location_label, m.capacity, m.status, m.created_at, m.cancelled_at, m.window_start, m.window_end, m.closed_at, m.cancellation_reason, m.starting_soon_notified_at, m.location,
  COALESCE(u.full_name, '') AS host_full_name,
  u.profile_photo_url AS host_profile_photo_url,
  COALESCE(u.trust_level, 0) AS host_trust_level,
  COALESCE(ratings.rating_average, 0)::numeric(3,2) AS host_rating_average,
  COALESCE(ratings.rating_count, 0)::int AS host_rating_count,
  (SELECT count(*) FROM meetup.meetup_requests r WHERE r.meetup_id = m.id AND r.status = 'accepted') AS accepted_count
FROM meetup.meetups m
LEFT JOIN meetup.user_display_cache u ON u.user_id = m.host_user_id
LEFT JOIN LATERAL (
  SELECT ROUND(AVG(score), 2) AS rating_average, count(*) AS rating_count
  FROM meetup.meetup_user_ratings mr WHERE mr.rated_user_id = m.host_user_id
) ratings ON true
WHERE m.host_user_id = $1
ORDER BY m.created_at DESC, m.id DESC
LIMIT $2
`

type ListMeetupsByHostFirstPageParams struct {
	HostUserID uuid.UUID `json:"host_user_id"`
	Limit      int32     `json:"limit"`
}

type ListMeetupsByHostFirstPageRow struct {
	ID                     uuid.UUID          `json:"id"`
	HostUserID             uuid.UUID          `json:"host_user_id"`
	Intent                 MeetupIntentType   `json:"intent"`
	LocationLat            float64            `json:"location_lat"`
	LocationLng            float64            `json:"location_lng"`
	LocationLabel          string             `json:"location_label"`
	Capacity               int16              `json:"capacity"`
	Status                 MeetupMeetupStatus `json:"status"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	CancelledAt            pgtype.Timestamptz `json:"cancelled_at"`
	WindowStart            pgtype.Timestamptz `json:"window_start"`
	WindowEnd              pgtype.Timestamptz `json:"window_end"`
	ClosedAt               pgtype.Timestamptz `json:"closed_at"`
	CancellationReason     pgtype.Text        `json:"cancellation_reason"`
	StartingSoonNotifiedAt pgtype.Timestamptz `json:"starting_soon_notified_at"`
	Location               interface{}        `json:"location"`
	HostFullName           string             `json:"host_full_name"`
	HostProfilePhotoUrl    pgtype.Text        `json:"host_profile_photo_url"`
	HostTrustLevel         int16              `json:"host_trust_level"`
	HostRatingAverage      pgtype.Numeric     `json:"host_rating_average"`
	HostRatingCount        int32              `json:"host_rating_count"`
	AcceptedCount          int64              `json:"accepted_count"`
}

// Real cursor pagination (2026-08-31 round-3 hardening), replacing round
// 2's flat LIMIT 200 — that fix closed the unbounded-memory risk but left
// a hard completeness ceiling: a host past 200 meetups had no way to
// reach the rest. Mirrors ListOpenMeetupsByIntentFirstPage's keyset shape
// exactly (fetch limit+1 in Go, ORDER BY created_at DESC, id DESC for a
// stable sort a plain created_at DESC alone doesn't guarantee when two
// rows share a timestamp).
func (q *Queries) ListMeetupsByHostFirstPage(ctx context.Context, arg ListMeetupsByHostFirstPageParams) ([]ListMeetupsByHostFirstPageRow, error) {
	rows, err := q.db.Query(ctx, listMeetupsByHostFirstPage, arg.HostUserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMeetupsByHostFirstPageRow
	for rows.Next() {
		var i ListMeetupsByHostFirstPageRow
		if err := rows.Scan(
			&i.ID,
			&i.HostUserID,
			&i.Intent,
			&i.LocationLat,
			&i.LocationLng,
			&i.LocationLabel,
			&i.Capacity,
			&i.Status,
			&i.CreatedAt,
			&i.CancelledAt,
			&i.WindowStart,
			&i.WindowEnd,
			&i.ClosedAt,
			&i.CancellationReason,
			&i.StartingSoonNotifiedAt,
			&i.Location,
			&i.HostFullName,
			&i.HostProfilePhotoUrl,
			&i.HostTrustLevel,
			&i.HostRatingAverage,
			&i.HostRatingCount,
			&i.AcceptedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMeetupsRequestedByUserAfterCursor = `-- name: ListMeetupsRequestedByUserAfterCursor :many
WITH latest_request AS (
  SELECT DISTINCT ON (meetup_id) id, meetup_id, requester_id, status, auto_rejected, created_at, resolved_at, withdrawal_note
  FROM meetup.meetup_requests
  WHERE meetup.meetup_requests.requester_id = $1
  ORDER BY meetup_id, created_at DESC
)
SELECT
  m.id, m.host_user_id, m.intent, m.location_lat, m.location_lng, m.location_label, m.capacity, m.status, m.created_at, m.cancelled_at, m.window_start, m.window_end, m.closed_at, m.cancellation_reason, m.starting_soon_notified_at, m.location,
  COALESCE(u.full_name, '') AS host_full_name,
  u.profile_photo_url AS host_profile_photo_url,
  COALESCE(u.trust_level, 0) AS host_trust_level,
  COALESCE(ratings.rating_average, 0)::numeric(3,2) AS host_rating_average,
  COALESCE(ratings.rating_count, 0)::int AS host_rating_count,
  (SELECT count(*) FROM meetup.meetup_requests r2 WHERE r2.meetup_id = m.id AND r2.status = 'accepted') AS accepted_count,
  lr.status AS my_request_status,
  lr.auto_rejected AS my_request_auto_rejected
FROM latest_request lr
JOIN meetup.meetups m ON m.id = lr.meetup_id
LEFT JOIN meetup.user_display_cache u ON u.user_id = m.host_user_id
LEFT JOIN LATERAL (
  SELECT ROUND(AVG(score), 2) AS rating_average, count(*) AS rating_count
  FROM meetup.meetup_user_ratings mr WHERE mr.rated_user_id = m.host_user_id
) ratings ON true
WHERE (m.created_at, m.id) < ($3::timestamptz, $4::uuid)
ORDER BY m.created_at DESC, m.id DESC
LIMIT $2
`

type ListMeetupsRequestedByUserAfterCursorParams struct {
	RequesterID     uuid.UUID          `json:"requester_id"`
	Limit           int32              `json:"limit"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        uuid.UUID          `json:"cursor_id"`
}

type ListMeetupsRequestedByUserAfterCursorRow struct {
	ID                     uuid.UUID                 `json:"id"`
	HostUserID             uuid.UUID                 `json:"host_user_id"`
	Intent                 MeetupIntentType          `json:"intent"`
	LocationLat            float64                   `json:"location_lat"`
	LocationLng            float64                   `json:"location_lng"`
	LocationLabel          string                    `json:"location_label"`
	Capacity               int16                     `json:"capacity"`
	Status                 MeetupMeetupStatus        `json:"status"`
	CreatedAt              pgtype.Timestamptz        `json:"created_at"`
	CancelledAt            pgtype.Timestamptz        `json:"cancelled_at"`
	WindowStart            pgtype.Timestamptz        `json:"window_start"`
	WindowEnd              pgtype.Timestamptz        `json:"window_end"`
	ClosedAt               pgtype.Timestamptz        `json:"closed_at"`
	CancellationReason     pgtype.Text               `json:"cancellation_reason"`
	StartingSoonNotifiedAt pgtype.Timestamptz        `json:"starting_soon_notified_at"`
	Location               interface{}               `json:"location"`
	HostFullName           string                    `json:"host_full_name"`
	HostProfilePhotoUrl    pgtype.Text               `json:"host_profile_photo_url"`
	HostTrustLevel         int16                     `json:"host_trust_level"`
	HostRatingAverage      pgtype.Numeric            `json:"host_rating_average"`
	HostRatingCount        int32                     `json:"host_rating_count"`
	AcceptedCount          int64                     `json:"accepted_count"`
	MyRequestStatus        MeetupMeetupRequestStatus `json:"my_request_status"`
	MyRequestAutoRejected  bool                      `json:"my_request_auto_rejected"`
}

// Keyset continuation of ListMeetupsRequestedByUserFirstPage.
func (q *Queries) ListMeetupsRequestedByUserAfterCursor(ctx context.Context, arg ListMeetupsRequestedByUserAfterCursorParams) ([]ListMeetupsRequestedByUserAfterCursorRow, error) {
	rows, err := q.db.Query(ctx, listMeetupsRequestedByUserAfterCursor,
		arg.RequesterID,
		arg.Limit,
		arg.CursorCreatedAt,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMeetupsRequestedByUserAfterCursorRow
	for rows.Next() {
		var i ListMeetupsRequestedByUserAfterCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.HostUserID,
			&i.Intent,
			&i.LocationLat,
			&i.LocationLng,
			&i.LocationLabel,
			&i.Capacity,
			&i.Status,
			&i.CreatedAt,
			&i.CancelledAt,
			&i.WindowStart,
			&i.WindowEnd,
			&i.ClosedAt,
			&i.CancellationReason,
			&i.StartingSoonNotifiedAt,
			&i.Location,
			&i.HostFullName,
			&i.HostProfilePhotoUrl,
			&i.HostTrustLevel,
			&i.HostRatingAverage,
			&i.HostRatingCount,
			&i.AcceptedCount,
			&i.MyRequestStatus,
			&i.MyRequestAutoRejected,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMeetupsRequestedByUserFirstPage = `-- name: ListMeetupsRequestedByUserFirstPage :many
WITH latest_request AS (
  SELECT DISTINCT ON (meetup_id) id, meetup_id, requester_id, status, auto_rejected, created_at, resolved_at, withdrawal_note
  FROM meetup.meetup_requests
  WHERE meetup.meetup_requests.requester_id = $1
  ORDER BY meetup_id, created_at DESC
)
SELECT
  m.id, m.host_user_id, m.intent, m.location_lat, m.location_lng, m.location_label, m.capacity, m.status, m.created_at, m.cancelled_at, m.window_start, m.window_end, m.closed_at, m.cancellation_reason, m.starting_soon_notified_at, m.location,
  COALESCE(u.full_name, '') AS host_full_name,
  u.profile_photo_url AS host_profile_photo_url,
  COALESCE(u.trust_level, 0) AS host_trust_level,
  COALESCE(ratings.rating_average, 0)::numeric(3,2) AS host_rating_average,
  COALESCE(ratings.rating_count, 0)::int AS host_rating_count,
  (SELECT count(*) FROM meetup.meetup_requests r2 WHERE r2.meetup_id = m.id AND r2.status = 'accepted') AS accepted_count,
  lr.status AS my_request_status,
  lr.auto_rejected AS my_request_auto_rejected
FROM latest_request lr
JOIN meetup.meetups m ON m.id = lr.meetup_id
LEFT JOIN meetup.user_display_cache u ON u.user_id = m.host_user_id
LEFT JOIN LATERAL (
  SELECT ROUND(AVG(score), 2) AS rating_average, count(*) AS rating_count
  FROM meetup.meetup_user_ratings mr WHERE mr.rated_user_id = m.host_user_id
) ratings ON true
ORDER BY m.created_at DESC, m.id DESC
LIMIT $2
`

type ListMeetupsRequestedByUserFirstPageParams struct {
	RequesterID uuid.UUID `json:"requester_id"`
	Limit       int32     `json:"limit"`
}

type ListMeetupsRequestedByUserFirstPageRow struct {
	ID                     uuid.UUID                 `json:"id"`
	HostUserID             uuid.UUID                 `json:"host_user_id"`
	Intent                 MeetupIntentType          `json:"intent"`
	LocationLat            float64                   `json:"location_lat"`
	LocationLng            float64                   `json:"location_lng"`
	LocationLabel          string                    `json:"location_label"`
	Capacity               int16                     `json:"capacity"`
	Status                 MeetupMeetupStatus        `json:"status"`
	CreatedAt              pgtype.Timestamptz        `json:"created_at"`
	CancelledAt            pgtype.Timestamptz        `json:"cancelled_at"`
	WindowStart            pgtype.Timestamptz        `json:"window_start"`
	WindowEnd              pgtype.Timestamptz        `json:"window_end"`
	ClosedAt               pgtype.Timestamptz        `json:"closed_at"`
	CancellationReason     pgtype.Text               `json:"cancellation_reason"`
	StartingSoonNotifiedAt pgtype.Timestamptz        `json:"starting_soon_notified_at"`
	Location               interface{}               `json:"location"`
	HostFullName           string                    `json:"host_full_name"`
	HostProfilePhotoUrl    pgtype.Text               `json:"host_profile_photo_url"`
	HostTrustLevel         int16                     `json:"host_trust_level"`
	HostRatingAverage      pgtype.Numeric            `json:"host_rating_average"`
	HostRatingCount        int32                     `json:"host_rating_count"`
	AcceptedCount          int64                     `json:"accepted_count"`
	MyRequestStatus        MeetupMeetupRequestStatus `json:"my_request_status"`
	MyRequestAutoRejected  bool                      `json:"my_request_auto_rejected"`
}

// One row per meetup, carrying the requester's *latest* request status for
// it (a requester can have multiple historical rows for the same meetup —
// e.g. rejected, then withdrawn, then a fresh pending one — the UNIQUE
// constraint is per (meetup_id, requester_id, status), not per
// (meetup_id, requester_id) alone).
//
// Real cursor pagination (2026-08-31 round-3 hardening) — same fix and
// reasoning as ListMeetupsByHostFirstPage above, applied to the
// requested-meetups side of the same pre-existing completeness ceiling.
func (q *Queries) ListMeetupsRequestedByUserFirstPage(ctx context.Context, arg ListMeetupsRequestedByUserFirstPageParams) ([]ListMeetupsRequestedByUserFirstPageRow, error) {
	rows, err := q.db.Query(ctx, listMeetupsRequestedByUserFirstPage, arg.RequesterID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMeetupsRequestedByUserFirstPageRow
	for rows.Next() {
		var i ListMeetupsRequestedByUserFirstPageRow
		if err := rows.Scan(
			&i.ID,
			&i.HostUserID,
			&i.Intent,
			&i.LocationLat,
			&i.LocationLng,
			&i.LocationLabel,
			&i.Capacity,
			&i.Status,
			&i.CreatedAt,
			&i.CancelledAt,
			&i.WindowStart,
			&i.WindowEnd,
			&i.ClosedAt,
			&i.CancellationReason,
			&i.StartingSoonNotifiedAt,
			&i.Location,
			&i.HostFullName,
			&i.HostProfilePhotoUrl,
			&i.HostTrustLevel,
			&i.HostRatingAverage,
			&i.HostRatingCount,
			&i.AcceptedCount,
			&i.MyRequestStatus,
			&i.MyRequestAutoRejected,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenMeetupsAfterCursor = `-- name: ListOpenMeetupsAfterCursor :many
WITH deduped AS (
  SELECT DISTINCT ON (m.id)
    m.id, m.host_user_id, m.intent, m.location_lat, m.location_lng, m.location_label, m.capacity, m.status, m.created_at, m.cancelled_at, m.window_start, m.window_end, m.closed_at, m.cancellation_reason, m.starting_soon_notified_at, m.location,
    COALESCE(u.full_name, '') AS host_full_name,
    u.profile_photo_url AS host_profile_photo_url,
    COALESCE(u.trust_level, 0) AS host_trust_level,
    COALESCE(ratings.rating_average, 0)::numeric(3,2) AS host_rating_average,
    COALESCE(ratings.rating_count, 0)::int AS host_rating_count,
    (SELECT count(*) FROM meetup.meetup_requests r2 WHERE r2.meetup_id = m.id AND r2.status = 'accepted') AS accepted_count,
    r.status AS my_request_status
  FROM meetup.meetups m
  LEFT JOIN meetup.user_display_cache u ON u.user_id = m.host_user_id
  LEFT JOIN LATERAL (
    SELECT ROUND(AVG(score), 2) AS rating_average, count(*) AS rating_count
    FROM meetup.meetup_user_ratings mr WHERE mr.rated_user_id = m.host_user_id
  ) ratings ON true
  LEFT JOIN meetup.meetup_requests r ON r.meetup_id = m.id AND r.requester_id = $4
  WHERE m.status = 'open'
    -- Both filters below are OPTIONAL and default to today's exact
    -- behaviour when unset, so every pre-existing caller is unaffected.
    --
    -- intent NULL = every intent (the home screen's "All" chip). Expressed
    -- as a NULL check rather than a separate query so there is one place
    -- where "which open meetups is this viewer allowed to see" is decided —
    -- a second near-identical query is how the ST_DWithin exemption below
    -- would eventually drift between them.
    AND ($5::meetup.intent_type IS NULL OR m.intent = $5::meetup.intent_type)
    -- within_days 0 = unrestricted. > 0 caps how far out window_start may
    -- be, which is what makes a "Happening Soon" view possible; nothing in
    -- this module supported a date-range filter before.
    AND ($6::int = 0
         OR m.window_start <= now() + ($6::int * INTERVAL '1 day'))
    AND (
      m.host_user_id = $4
      OR ST_DWithin(
        m.location,
        ST_SetSRID(ST_MakePoint($7::float8, $8::float8), 4326)::geography,
        40000
      )
    )
  ORDER BY m.id, r.created_at DESC NULLS LAST
)
SELECT id, host_user_id, intent, location_lat, location_lng, location_label, capacity, status, created_at, cancelled_at, window_start, window_end, closed_at, cancellation_reason, starting_soon_notified_at, location, host_full_name, host_profile_photo_url, host_trust_level, host_rating_average, host_rating_count, accepted_count, my_request_status FROM deduped
WHERE (created_at, id) < ($1::timestamptz, $2::uuid)
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListOpenMeetupsAfterCursorParams struct {
	CursorCreatedAt pgtype.Timestamptz   `json:"cursor_created_at"`
	CursorID        uuid.UUID            `json:"cursor_id"`
	PageLimit       int32                `json:"page_limit"`
	RequesterID     uuid.UUID            `json:"requester_id"`
	Intent          NullMeetupIntentType `json:"intent"`
	WithinDays      int32                `json:"within_days"`
	ViewerLng       float64              `json:"viewer_lng"`
	ViewerLat       float64              `json:"viewer_lat"`
}

type ListOpenMeetupsAfterCursorRow struct {
	ID                     uuid.UUID                     `json:"id"`
	HostUserID             uuid.UUID                     `json:"host_user_id"`
	Intent                 MeetupIntentType              `json:"intent"`
	LocationLat            float64                       `json:"location_lat"`
	LocationLng            float64                       `json:"location_lng"`
	LocationLabel          string                        `json:"location_label"`
	Capacity               int16                         `json:"capacity"`
	Status                 MeetupMeetupStatus            `json:"status"`
	CreatedAt              pgtype.Timestamptz            `json:"created_at"`
	CancelledAt            pgtype.Timestamptz            `json:"cancelled_at"`
	WindowStart            pgtype.Timestamptz            `json:"window_start"`
	WindowEnd              pgtype.Timestamptz            `json:"window_end"`
	ClosedAt               pgtype.Timestamptz            `json:"closed_at"`
	CancellationReason     pgtype.Text                   `json:"cancellation_reason"`
	StartingSoonNotifiedAt pgtype.Timestamptz            `json:"starting_soon_notified_at"`
	Location               interface{}                   `json:"location"`
	HostFullName           string                        `json:"host_full_name"`
	HostProfilePhotoUrl    pgtype.Text                   `json:"host_profile_photo_url"`
	HostTrustLevel         int16                         `json:"host_trust_level"`
	HostRatingAverage      pgtype.Numeric                `json:"host_rating_average"`
	HostRatingCount        int32                         `json:"host_rating_count"`
	AcceptedCount          int64                         `json:"accepted_count"`
	MyRequestStatus        NullMeetupMeetupRequestStatus `json:"my_request_status"`
}

// Keyset pagination on (created_at, id) — cursorCreatedAt/cursorID are the
// last row of the previous page, so this resumes strictly after it. Row
// comparison (a, b) < (c, d) is a single index-friendly condition, not a
// chain of ORs. Same DISTINCT-then-re-sort shape as the first-page query
// above, for the same reason. See that query's comment for the
// ST_DWithin condition below, and for why the viewer's own hosted meetups
// (m.host_user_id = requester_id) are exempt from the 40km radius — the exemption
// must stay identical in both queries, or a host's own out-of-range meetup
// would appear on page 1 and then vanish from page 2 onward.
func (q *Queries) ListOpenMeetupsAfterCursor(ctx context.Context, arg ListOpenMeetupsAfterCursorParams) ([]ListOpenMeetupsAfterCursorRow, error) {
	rows, err := q.db.Query(ctx, listOpenMeetupsAfterCursor,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
		arg.RequesterID,
		arg.Intent,
		arg.WithinDays,
		arg.ViewerLng,
		arg.ViewerLat,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenMeetupsAfterCursorRow
	for rows.Next() {
		var i ListOpenMeetupsAfterCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.HostUserID,
			&i.Intent,
			&i.LocationLat,
			&i.LocationLng,
			&i.LocationLabel,
			&i.Capacity,
			&i.Status,
			&i.CreatedAt,
			&i.CancelledAt,
			&i.WindowStart,
			&i.WindowEnd,
			&i.ClosedAt,
			&i.CancellationReason,
			&i.StartingSoonNotifiedAt,
			&i.Location,
			&i.HostFullName,
			&i.HostProfilePhotoUrl,
			&i.HostTrustLevel,
			&i.HostRatingAverage,
			&i.HostRatingCount,
			&i.AcceptedCount,
			&i.MyRequestStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenMeetupsFirstPage = `-- name: ListOpenMeetupsFirstPage :many
WITH deduped AS (
  SELECT DISTINCT ON (m.id)
    m.id, m.host_user_id, m.intent, m.location_lat, m.location_lng, m.location_label, m.capacity, m.status, m.created_at, m.cancelled_at, m.window_start, m.window_end, m.closed_at, m.cancellation_reason, m.starting_soon_notified_at, m.location,
    COALESCE(u.full_name, '') AS host_full_name,
    u.profile_photo_url AS host_profile_photo_url,
    COALESCE(u.trust_level, 0) AS host_trust_level,
    COALESCE(ratings.rating_average, 0)::numeric(3,2) AS host_rating_average,
    COALESCE(ratings.rating_count, 0)::int AS host_rating_count,
    (SELECT count(*) FROM meetup.meetup_requests r2 WHERE r2.meetup_id = m.id AND r2.status = 'accepted') AS accepted_count,
    r.status AS my_request_status
  FROM meetup.meetups m
  LEFT JOIN meetup.user_display_cache u ON u.user_id = m.host_user_id
  LEFT JOIN LATERAL (
    SELECT ROUND(AVG(score), 2) AS rating_average, count(*) AS rating_count
    FROM meetup.meetup_user_ratings mr WHERE mr.rated_user_id = m.host_user_id
  ) ratings ON true
  LEFT JOIN meetup.meetup_requests r ON r.meetup_id = m.id AND r.requester_id = $2
  WHERE m.status = 'open'
    -- Both filters below are OPTIONAL and default to today's exact
    -- behaviour when unset, so every pre-existing caller is unaffected.
    --
    -- intent NULL = every intent (the home screen's "All" chip). Expressed
    -- as a NULL check rather than a separate query so there is one place
    -- where "which open meetups is this viewer allowed to see" is decided —
    -- a second near-identical query is how the ST_DWithin exemption below
    -- would eventually drift between them.
    AND ($3::meetup.intent_type IS NULL OR m.intent = $3::meetup.intent_type)
    -- within_days 0 = unrestricted. > 0 caps how far out window_start may
    -- be, which is what makes a "Happening Soon" view possible; nothing in
    -- this module supported a date-range filter before.
    AND ($4::int = 0
         OR m.window_start <= now() + ($4::int * INTERVAL '1 day'))
    AND (
      m.host_user_id = $2
      OR ST_DWithin(
        m.location,
        ST_SetSRID(ST_MakePoint($5::float8, $6::float8), 4326)::geography,
        40000
      )
    )
  ORDER BY m.id, r.created_at DESC NULLS LAST
)
SELECT id, host_user_id, intent, location_lat, location_lng, location_label, capacity, status, created_at, cancelled_at, window_start, window_end, closed_at, cancellation_reason, starting_soon_notified_at, location, host_full_name, host_profile_photo_url, host_trust_level, host_rating_average, host_rating_count, accepted_count, my_request_status FROM deduped
ORDER BY created_at DESC, id DESC
LIMIT $1
`

type ListOpenMeetupsFirstPageParams struct {
	PageLimit   int32                `json:"page_limit"`
	RequesterID uuid.UUID            `json:"requester_id"`
	Intent      NullMeetupIntentType `json:"intent"`
	WithinDays  int32                `json:"within_days"`
	ViewerLng   float64              `json:"viewer_lng"`
	ViewerLat   float64              `json:"viewer_lat"`
}

type ListOpenMeetupsFirstPageRow struct {
	ID                     uuid.UUID                     `json:"id"`
	HostUserID             uuid.UUID                     `json:"host_user_id"`
	Intent                 MeetupIntentType              `json:"intent"`
	LocationLat            float64                       `json:"location_lat"`
	LocationLng            float64                       `json:"location_lng"`
	LocationLabel          string                        `json:"location_label"`
	Capacity               int16                         `json:"capacity"`
	Status                 MeetupMeetupStatus            `json:"status"`
	CreatedAt              pgtype.Timestamptz            `json:"created_at"`
	CancelledAt            pgtype.Timestamptz            `json:"cancelled_at"`
	WindowStart            pgtype.Timestamptz            `json:"window_start"`
	WindowEnd              pgtype.Timestamptz            `json:"window_end"`
	ClosedAt               pgtype.Timestamptz            `json:"closed_at"`
	CancellationReason     pgtype.Text                   `json:"cancellation_reason"`
	StartingSoonNotifiedAt pgtype.Timestamptz            `json:"starting_soon_notified_at"`
	Location               interface{}                   `json:"location"`
	HostFullName           string                        `json:"host_full_name"`
	HostProfilePhotoUrl    pgtype.Text                   `json:"host_profile_photo_url"`
	HostTrustLevel         int16                         `json:"host_trust_level"`
	HostRatingAverage      pgtype.Numeric                `json:"host_rating_average"`
	HostRatingCount        int32                         `json:"host_rating_count"`
	AcceptedCount          int64                         `json:"accepted_count"`
	MyRequestStatus        NullMeetupMeetupRequestStatus `json:"my_request_status"`
}

// DISTINCT ON (m.id) + a wrapping SELECT to re-sort by recency: DISTINCT ON
// requires its own ORDER BY to start with the same expression(s), which
// would otherwise force sorting this page by id instead of created_at —
// the inner query dedupes (a requester can have multiple historical
// meetup_requests rows for the same meetup, see ListMeetupsRequestedByUser
// above), the outer one restores the intended pagination order. Plain LEFT
// JOIN (not LATERAL/a scalar subquery) for my_request_status, same
// nullability reasoning as GetMeetupByID above. See GetMeetupByID for why
// user_display_cache/meetup_user_ratings are both LEFT JOINed.
//
// The ST_DWithin distance condition in WHERE (ADR-021 §2 originally,
// rewritten from a plain haversine expression to real PostGIS per
// ADR-027) runs alongside idx_meetups_intent_status's own narrowing of
// m.status/m.intent — the two conditions each use their own index
// (idx_meetups_intent_status, idx_meetups_location_gist), not one
// replacing the other. 40000 = 40km in meters (ST_DWithin on geography
// takes meters, not degrees).
//
// The viewer's OWN hosted meetups are exempt from that radius: a host who
// scheduled a meetup outside their own current 40km bubble (travelling, or
// scheduling somewhere they'll be later) otherwise couldn't see their own
// meetup on the browse feed at all, even though _MeetupCard already has a
// "YOU'RE HOSTING" state ready for exactly that row. This deliberately
// reuses sqlc.arg(requester_id) — already bound to the viewer's id for the my_request_status
// LEFT JOIN below — rather than adding a new bound parameter, so no
// caller/param struct changes: the same value simply does double duty.
// Scoped to hosts only; a meetup the viewer merely has an accepted request
// for is NOT exempted here (it already surfaces distance-unfiltered via
// "Your Meetups"/Active Meetups).
func (q *Queries) ListOpenMeetupsFirstPage(ctx context.Context, arg ListOpenMeetupsFirstPageParams) ([]ListOpenMeetupsFirstPageRow, error) {
	rows, err := q.db.Query(ctx, listOpenMeetupsFirstPage,
		arg.PageLimit,
		arg.RequesterID,
		arg.Intent,
		arg.WithinDays,
		arg.ViewerLng,
		arg.ViewerLat,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenMeetupsFirstPageRow
	for rows.Next() {
		var i ListOpenMeetupsFirstPageRow
		if err := rows.Scan(
			&i.ID,
			&i.HostUserID,
			&i.Intent,
			&i.LocationLat,
			&i.LocationLng,
			&i.LocationLabel,
			&i.Capacity,
			&i.Status,
			&i.CreatedAt,
			&i.CancelledAt,
			&i.WindowStart,
			&i.WindowEnd,
			&i.ClosedAt,
			&i.CancellationReason,
			&i.StartingSoonNotifiedAt,
			&i.Location,
			&i.HostFullName,
			&i.HostProfilePhotoUrl,
			&i.HostTrustLevel,
			&i.HostRatingAverage,
			&i.HostRatingCount,
			&i.AcceptedCount,
			&i.MyRequestStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMeetupFull = `-- name: MarkMeetupFull :exec
UPDATE meetup.meetups SET status = 'full' WHERE id = $1
`

func (q *Queries) MarkMeetupFull(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markMeetupFull, id)
	return err
}

const recomputeMeetupsCompletedForParticipants = `-- name: RecomputeMeetupsCompletedForParticipants :many
WITH participants AS (
    SELECT m.host_user_id AS user_id
      FROM meetup.meetups m
     WHERE m.id = ANY($1::uuid[])
    UNION
    SELECT r.requester_id AS user_id
      FROM meetup.meetup_requests r
     WHERE r.meetup_id = ANY($1::uuid[])
       AND r.status = 'accepted'
)
SELECT p.user_id,
       (
           SELECT count(*)
             FROM meetup.meetups done
            WHERE done.status = 'completed'
              AND (
                  done.host_user_id = p.user_id
                  OR EXISTS (
                      SELECT 1
                        FROM meetup.meetup_requests dr
                       WHERE dr.meetup_id = done.id
                         AND dr.requester_id = p.user_id
                         AND dr.status = 'accepted'
                  )
              )
       )::bigint AS meetups_completed
  FROM participants p
`

type RecomputeMeetupsCompletedForParticipantsRow struct {
	UserID           uuid.UUID `json:"user_id"`
	MeetupsCompleted int64     `json:"meetups_completed"`
}

// Everyone whose "meetups completed" total is changed by the meetups in
// meetup_ids having just completed, together with each one's NEW total.
//
// Runs inside the same transaction that completed those meetups, so the
// counts already include them — that is what lets the event carry an
// absolute figure rather than a delta, and absolute is what makes the auth
// module's consumer idempotent under redelivery (see auth/0005).
//
// PARTICIPANT = the host, plus every requester whose request is 'accepted'.
// Deliberately NOT gated on the Safety Gate check-in: check-in is a safety
// affordance people can legitimately skip, and someone who attended but
// never opened the checklist has still completed a meetup. The same
// definition IsParticipant uses everywhere else in this module.
//
// One statement rather than "list participants, then count per participant":
// the fan-out is small (a meetup's capacity), but the 1+N version would run
// inside the close transaction and hold it open for the round trips.
func (q *Queries) RecomputeMeetupsCompletedForParticipants(ctx context.Context, meetupIds []uuid.UUID) ([]RecomputeMeetupsCompletedForParticipantsRow, error) {
	rows, err := q.db.Query(ctx, recomputeMeetupsCompletedForParticipants, meetupIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecomputeMeetupsCompletedForParticipantsRow
	for rows.Next() {
		var i RecomputeMeetupsCompletedForParticipantsRow
		if err := rows.Scan(&i.UserID, &i.MeetupsCompleted); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
