// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: meetup_requests.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acceptMeetupRequest = `-- name: AcceptMeetupRequest :one
UPDATE meetup.meetup_requests SET status = 'accepted', resolved_at = now()
WHERE meetup.meetup_requests.id = $1 AND meetup.meetup_requests.meetup_id IN (SELECT m.id FROM meetup.meetups m WHERE m.host_user_id = $2)
RETURNING id, meetup_id, requester_id, status, auto_rejected, created_at, resolved_at, withdrawal_note
`

type AcceptMeetupRequestParams struct {
	ID         uuid.UUID `json:"id"`
	HostUserID uuid.UUID `json:"host_user_id"`
}

// host_user_id scoping (Round 11, docs/00-project/action-tracker.md
// § 4b-26) is defense-in-depth alongside the existing Go-level ownership
// check in RespondToRequest/acceptRequest — meetup_requests has no
// host_user_id column of its own, so this goes through a subquery against
// meetups, the same relationship the Go check already enforces. The
// Go-level check stays, this doesn't replace it.
func (q *Queries) AcceptMeetupRequest(ctx context.Context, arg AcceptMeetupRequestParams) (MeetupMeetupRequest, error) {
	row := q.db.QueryRow(ctx, acceptMeetupRequest, arg.ID, arg.HostUserID)
	var i MeetupMeetupRequest
	err := row.Scan(
		&i.ID,
		&i.MeetupID,
		&i.RequesterID,
		&i.Status,
		&i.AutoRejected,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.WithdrawalNote,
	)
	return i, err
}

const autoRejectPendingRequestsForMeetup = `-- name: AutoRejectPendingRequestsForMeetup :many
UPDATE meetup.meetup_requests SET status = 'rejected', resolved_at = now(), auto_rejected = true
WHERE meetup_id = $1 AND status = 'pending'
RETURNING id, meetup_id, requester_id, status, auto_rejected, created_at, resolved_at, withdrawal_note
`

// Returns the rejected rows so the caller can notify each requester
// (backend/meetup-scheduling-PLAN.md Step E).
func (q *Queries) AutoRejectPendingRequestsForMeetup(ctx context.Context, meetupID uuid.UUID) ([]MeetupMeetupRequest, error) {
	rows, err := q.db.Query(ctx, autoRejectPendingRequestsForMeetup, meetupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MeetupMeetupRequest
	for rows.Next() {
		var i MeetupMeetupRequest
		if err := rows.Scan(
			&i.ID,
			&i.MeetupID,
			&i.RequesterID,
			&i.Status,
			&i.AutoRejected,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.WithdrawalNote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAcceptedRequests = `-- name: CountAcceptedRequests :one
SELECT count(*) FROM meetup.meetup_requests WHERE meetup_id = $1 AND status = 'accepted'
`

func (q *Queries) CountAcceptedRequests(ctx context.Context, meetupID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAcceptedRequests, meetupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMeetupRequest = `-- name: CreateMeetupRequest :one
INSERT INTO meetup.meetup_requests (meetup_id, requester_id)
VALUES ($1, $2)
RETURNING id, meetup_id, requester_id, status, auto_rejected, created_at, resolved_at, withdrawal_note
`

type CreateMeetupRequestParams struct {
	MeetupID    uuid.UUID `json:"meetup_id"`
	RequesterID uuid.UUID `json:"requester_id"`
}

func (q *Queries) CreateMeetupRequest(ctx context.Context, arg CreateMeetupRequestParams) (MeetupMeetupRequest, error) {
	row := q.db.QueryRow(ctx, createMeetupRequest, arg.MeetupID, arg.RequesterID)
	var i MeetupMeetupRequest
	err := row.Scan(
		&i.ID,
		&i.MeetupID,
		&i.RequesterID,
		&i.Status,
		&i.AutoRejected,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.WithdrawalNote,
	)
	return i, err
}

const getMeetupRequestByID = `-- name: GetMeetupRequestByID :one
SELECT id, meetup_id, requester_id, status, auto_rejected, created_at, resolved_at, withdrawal_note FROM meetup.meetup_requests WHERE id = $1
`

// Plain, no join — used inside Accept's transaction where requester
// display info is irrelevant, and as the base row write queries (Accept/
// Reject/Withdraw) RETURNING against. Callers needing display info should
// use GetMeetupRequestWithRequesterInfoByID instead.
func (q *Queries) GetMeetupRequestByID(ctx context.Context, id uuid.UUID) (MeetupMeetupRequest, error) {
	row := q.db.QueryRow(ctx, getMeetupRequestByID, id)
	var i MeetupMeetupRequest
	err := row.Scan(
		&i.ID,
		&i.MeetupID,
		&i.RequesterID,
		&i.Status,
		&i.AutoRejected,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.WithdrawalNote,
	)
	return i, err
}

const getMeetupRequestWithRequesterInfoByID = `-- name: GetMeetupRequestWithRequesterInfoByID :one
SELECT
  r.id, r.meetup_id, r.requester_id, r.status, r.auto_rejected, r.created_at, r.resolved_at, r.withdrawal_note,
  COALESCE(u.full_name, '') AS requester_full_name,
  u.profile_photo_url AS requester_profile_photo_url,
  COALESCE(u.trust_level, 0) AS requester_trust_level,
  COALESCE(ratings.rating_average, 0)::numeric(3,2) AS requester_rating_average,
  COALESCE(ratings.rating_count, 0)::int AS requester_rating_count
FROM meetup.meetup_requests r
LEFT JOIN meetup.user_display_cache u ON u.user_id = r.requester_id
LEFT JOIN LATERAL (
  SELECT ROUND(AVG(score), 2) AS rating_average, count(*) AS rating_count
  FROM meetup.meetup_user_ratings mr WHERE mr.rated_user_id = r.requester_id
) ratings ON true
WHERE r.id = $1
`

type GetMeetupRequestWithRequesterInfoByIDRow struct {
	ID                       uuid.UUID                 `json:"id"`
	MeetupID                 uuid.UUID                 `json:"meetup_id"`
	RequesterID              uuid.UUID                 `json:"requester_id"`
	Status                   MeetupMeetupRequestStatus `json:"status"`
	AutoRejected             bool                      `json:"auto_rejected"`
	CreatedAt                pgtype.Timestamptz        `json:"created_at"`
	ResolvedAt               pgtype.Timestamptz        `json:"resolved_at"`
	WithdrawalNote           pgtype.Text               `json:"withdrawal_note"`
	RequesterFullName        string                    `json:"requester_full_name"`
	RequesterProfilePhotoUrl pgtype.Text               `json:"requester_profile_photo_url"`
	RequesterTrustLevel      int16                     `json:"requester_trust_level"`
	RequesterRatingAverage   pgtype.Numeric            `json:"requester_rating_average"`
	RequesterRatingCount     int32                     `json:"requester_rating_count"`
}

// See meetup.meetups.sql's GetMeetupByID for why user_display_cache/
// meetup_user_ratings are both LEFT JOINed (not JOIN) here.
func (q *Queries) GetMeetupRequestWithRequesterInfoByID(ctx context.Context, id uuid.UUID) (GetMeetupRequestWithRequesterInfoByIDRow, error) {
	row := q.db.QueryRow(ctx, getMeetupRequestWithRequesterInfoByID, id)
	var i GetMeetupRequestWithRequesterInfoByIDRow
	err := row.Scan(
		&i.ID,
		&i.MeetupID,
		&i.RequesterID,
		&i.Status,
		&i.AutoRejected,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.WithdrawalNote,
		&i.RequesterFullName,
		&i.RequesterProfilePhotoUrl,
		&i.RequesterTrustLevel,
		&i.RequesterRatingAverage,
		&i.RequesterRatingCount,
	)
	return i, err
}

const listRequestsForMeetup = `-- name: ListRequestsForMeetup :many
SELECT
  r.id, r.meetup_id, r.requester_id, r.status, r.auto_rejected, r.created_at, r.resolved_at, r.withdrawal_note,
  COALESCE(u.full_name, '') AS requester_full_name,
  u.profile_photo_url AS requester_profile_photo_url,
  COALESCE(u.trust_level, 0) AS requester_trust_level,
  COALESCE(ratings.rating_average, 0)::numeric(3,2) AS requester_rating_average,
  COALESCE(ratings.rating_count, 0)::int AS requester_rating_count,
  safety.checked_in_at AS requester_checked_in_at,
  safety.declined_at AS requester_declined_at,
  safety.decline_reason AS requester_decline_reason
FROM meetup.meetup_requests r
LEFT JOIN meetup.user_display_cache u ON u.user_id = r.requester_id
LEFT JOIN LATERAL (
  SELECT ROUND(AVG(score), 2) AS rating_average, count(*) AS rating_count
  FROM meetup.meetup_user_ratings mr WHERE mr.rated_user_id = r.requester_id
) ratings ON true
LEFT JOIN meetup.safety_state safety
  ON safety.meetup_id = r.meetup_id AND safety.user_id = r.requester_id
WHERE r.meetup_id = $1
ORDER BY r.created_at ASC
`

type ListRequestsForMeetupRow struct {
	ID                       uuid.UUID                 `json:"id"`
	MeetupID                 uuid.UUID                 `json:"meetup_id"`
	RequesterID              uuid.UUID                 `json:"requester_id"`
	Status                   MeetupMeetupRequestStatus `json:"status"`
	AutoRejected             bool                      `json:"auto_rejected"`
	CreatedAt                pgtype.Timestamptz        `json:"created_at"`
	ResolvedAt               pgtype.Timestamptz        `json:"resolved_at"`
	WithdrawalNote           pgtype.Text               `json:"withdrawal_note"`
	RequesterFullName        string                    `json:"requester_full_name"`
	RequesterProfilePhotoUrl pgtype.Text               `json:"requester_profile_photo_url"`
	RequesterTrustLevel      int16                     `json:"requester_trust_level"`
	RequesterRatingAverage   pgtype.Numeric            `json:"requester_rating_average"`
	RequesterRatingCount     int32                     `json:"requester_rating_count"`
	RequesterCheckedInAt     pgtype.Timestamptz        `json:"requester_checked_in_at"`
	RequesterDeclinedAt      pgtype.Timestamptz        `json:"requester_declined_at"`
	RequesterDeclineReason   pgtype.Text               `json:"requester_decline_reason"`
}

// LEFT JOIN meetup.safety_state (ADR-024 §6) — host visibility into each
// accepted participant's check-in status, piggybacking on this query's
// existing host-only ListMeetupRequests call site rather than a new
// endpoint. A pending/rejected/withdrawn request never has a safety-state
// row (EnsureExists only ever runs at accept-time), so these columns are
// naturally NULL for anything that isn't accepted — no extra WHERE needed.
// One join, not a per-row follow-up query (avoids N+1).
func (q *Queries) ListRequestsForMeetup(ctx context.Context, meetupID uuid.UUID) ([]ListRequestsForMeetupRow, error) {
	rows, err := q.db.Query(ctx, listRequestsForMeetup, meetupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRequestsForMeetupRow
	for rows.Next() {
		var i ListRequestsForMeetupRow
		if err := rows.Scan(
			&i.ID,
			&i.MeetupID,
			&i.RequesterID,
			&i.Status,
			&i.AutoRejected,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.WithdrawalNote,
			&i.RequesterFullName,
			&i.RequesterProfilePhotoUrl,
			&i.RequesterTrustLevel,
			&i.RequesterRatingAverage,
			&i.RequesterRatingCount,
			&i.RequesterCheckedInAt,
			&i.RequesterDeclinedAt,
			&i.RequesterDeclineReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectMeetupRequest = `-- name: RejectMeetupRequest :one
UPDATE meetup.meetup_requests SET status = 'rejected', resolved_at = now()
WHERE meetup.meetup_requests.id = $1 AND meetup.meetup_requests.status = 'pending' AND meetup.meetup_requests.meetup_id IN (SELECT m.id FROM meetup.meetups m WHERE m.host_user_id = $2)
RETURNING id, meetup_id, requester_id, status, auto_rejected, created_at, resolved_at, withdrawal_note
`

type RejectMeetupRequestParams struct {
	ID         uuid.UUID `json:"id"`
	HostUserID uuid.UUID `json:"host_user_id"`
}

// WHERE status = 'pending' guards against rejecting an already-resolved
// request (double-tap, or a race with auto-reject) — zero rows affected
// (pgx.ErrNoRows) is the repository's signal to map to apperror.ErrConflict.
// host_user_id scoping (Round 11) added the same way as AcceptMeetupRequest
// above — defense-in-depth alongside the existing Go-level check.
func (q *Queries) RejectMeetupRequest(ctx context.Context, arg RejectMeetupRequestParams) (MeetupMeetupRequest, error) {
	row := q.db.QueryRow(ctx, rejectMeetupRequest, arg.ID, arg.HostUserID)
	var i MeetupMeetupRequest
	err := row.Scan(
		&i.ID,
		&i.MeetupID,
		&i.RequesterID,
		&i.Status,
		&i.AutoRejected,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.WithdrawalNote,
	)
	return i, err
}

const withdrawMeetupRequest = `-- name: WithdrawMeetupRequest :one
UPDATE meetup.meetup_requests SET status = 'withdrawn', resolved_at = now(), withdrawal_note = $2
WHERE id = $1 AND requester_id = $3 AND status IN ('pending', 'accepted')
RETURNING id, meetup_id, requester_id, status, auto_rejected, created_at, resolved_at, withdrawal_note
`

type WithdrawMeetupRequestParams struct {
	ID             uuid.UUID   `json:"id"`
	WithdrawalNote pgtype.Text `json:"withdrawal_note"`
	RequesterID    uuid.UUID   `json:"requester_id"`
}

// Both 'pending' and 'accepted' are withdrawable (ADR-020 §4) — widened
// from the original pending-only precondition: a requester backing out
// *after* being accepted is exactly the case the withdrawal-rating path
// exists for ("the meetup continues for everyone else," ADR-020's own
// framing — only meaningful if they'd actually been accepted into it).
// note is optional (may be NULL). Does not touch the meetup's own
// capacity/status — a freed-up slot on a full meetup reopening is a
// separate, not-yet-built concern. requester_id scoping (Round 11,
// docs/00-project/action-tracker.md § 4b-26) is defense-in-depth
// alongside the existing Go-level check in service.go's WithdrawRequest —
// scoped to the *requester*, not the host, unlike Accept/Reject/Cancel.
// The Go-level check stays, this doesn't replace it.
func (q *Queries) WithdrawMeetupRequest(ctx context.Context, arg WithdrawMeetupRequestParams) (MeetupMeetupRequest, error) {
	row := q.db.QueryRow(ctx, withdrawMeetupRequest, arg.ID, arg.WithdrawalNote, arg.RequesterID)
	var i MeetupMeetupRequest
	err := row.Scan(
		&i.ID,
		&i.MeetupID,
		&i.RequesterID,
		&i.Status,
		&i.AutoRejected,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.WithdrawalNote,
	)
	return i, err
}
