// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: member.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const canViewMemberProfile = `-- name: CanViewMemberProfile :one

SELECT
  $1::uuid = $2::uuid
  OR EXISTS (
    SELECT 1 FROM meetup.meetups m WHERE m.host_user_id = $2::uuid
  )
  OR EXISTS (
    SELECT 1
    FROM (
      SELECT m.id AS meetup_id, m.host_user_id AS user_id FROM meetup.meetups m
      UNION ALL
      SELECT r.meetup_id, r.requester_id FROM meetup.meetup_requests r WHERE r.status = 'accepted'
    ) a
    JOIN (
      SELECT m.id AS meetup_id, m.host_user_id AS user_id FROM meetup.meetups m
      UNION ALL
      SELECT r.meetup_id, r.requester_id FROM meetup.meetup_requests r WHERE r.status = 'accepted'
    ) b ON b.meetup_id = a.meetup_id
    WHERE a.user_id = $1::uuid AND b.user_id = $2::uuid
  ) AS can_view
`

type CanViewMemberProfileParams struct {
	ViewerID uuid.UUID `json:"viewer_id"`
	TargetID uuid.UUID `json:"target_id"`
}

// Queries behind another member's public profile (GET /v1/users/{id}).
// Every one takes the VIEWER as well as the target, because what is
// visible depends on what the two of them have shared — see
// member.go in the service layer for the rule.
// True when the viewer may open the target's profile: they are the same
// person; the target hosts (or has hosted) a meetup — a host is public by
// design, since you must be able to judge them before asking to join; or
// the two were both on one meetup as host/accepted. "Shared" deliberately
// counts past meetups: once you have sat at a table with someone, their
// profile stays open to you.
func (q *Queries) CanViewMemberProfile(ctx context.Context, arg CanViewMemberProfileParams) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, canViewMemberProfile, arg.ViewerID, arg.TargetID)
	var can_view pgtype.Bool
	err := row.Scan(&can_view)
	return can_view, err
}

const listMeetupReviewComments = `-- name: ListMeetupReviewComments :many
SELECT
  f.meetup_id,
  f.user_id AS author_id,
  COALESCE(u.full_name, '') AS author_name,
  f.notes,
  f.review_completed_at
FROM meetup.meetup_feedback f
LEFT JOIN meetup.user_display_cache u ON u.user_id = f.user_id
WHERE f.meetup_id = ANY($1::uuid[])
  AND f.notes IS NOT NULL AND btrim(f.notes) <> ''
ORDER BY f.meetup_id, f.review_completed_at
`

type ListMeetupReviewCommentsRow struct {
	MeetupID          uuid.UUID          `json:"meetup_id"`
	AuthorID          uuid.UUID          `json:"author_id"`
	AuthorName        string             `json:"author_name"`
	Notes             pgtype.Text        `json:"notes"`
	ReviewCompletedAt pgtype.Timestamptz `json:"review_completed_at"`
}

// The written comments on a set of meetups, oldest first within a meetup.
// The author's display name rides along; the service blanks it for a
// viewer who was not on that meetup.
func (q *Queries) ListMeetupReviewComments(ctx context.Context, meetupIds []uuid.UUID) ([]ListMeetupReviewCommentsRow, error) {
	rows, err := q.db.Query(ctx, listMeetupReviewComments, meetupIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMeetupReviewCommentsRow
	for rows.Next() {
		var i ListMeetupReviewCommentsRow
		if err := rows.Scan(
			&i.MeetupID,
			&i.AuthorID,
			&i.AuthorName,
			&i.Notes,
			&i.ReviewCompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentMeetupsForMember = `-- name: ListRecentMeetupsForMember :many
WITH membership AS (
  SELECT m.id AS meetup_id, m.host_user_id AS user_id, true AS is_host FROM meetup.meetups m
  UNION ALL
  SELECT r.meetup_id, r.requester_id, false FROM meetup.meetup_requests r WHERE r.status = 'accepted'
)
SELECT
  m.id,
  m.intent,
  m.status,
  m.window_start,
  m.window_end,
  m.location_label,
  tm.is_host AS target_is_host,
  (SELECT count(*) FROM membership c WHERE c.meetup_id = m.id)::int AS participant_count,
  COALESCE((SELECT avg(f.overall_score) FROM meetup.meetup_feedback f WHERE f.meetup_id = m.id AND f.overall_score IS NOT NULL), 0)::float8 AS overall_average,
  (SELECT count(*) FROM meetup.meetup_feedback f WHERE f.meetup_id = m.id AND f.overall_score IS NOT NULL)::int AS review_count,
  EXISTS (SELECT 1 FROM membership v WHERE v.meetup_id = m.id AND v.user_id = $1::uuid) AS viewer_was_in
FROM meetup.meetups m
JOIN membership tm ON tm.meetup_id = m.id AND tm.user_id = $2::uuid
WHERE m.status <> 'cancelled'
ORDER BY m.window_start DESC
LIMIT $3
`

type ListRecentMeetupsForMemberParams struct {
	ViewerID  uuid.UUID `json:"viewer_id"`
	TargetID  uuid.UUID `json:"target_id"`
	PageLimit int32     `json:"page_limit"`
}

type ListRecentMeetupsForMemberRow struct {
	ID               uuid.UUID          `json:"id"`
	Intent           MeetupIntentType   `json:"intent"`
	Status           MeetupMeetupStatus `json:"status"`
	WindowStart      pgtype.Timestamptz `json:"window_start"`
	WindowEnd        pgtype.Timestamptz `json:"window_end"`
	LocationLabel    string             `json:"location_label"`
	TargetIsHost     bool               `json:"target_is_host"`
	ParticipantCount int32              `json:"participant_count"`
	OverallAverage   float64            `json:"overall_average"`
	ReviewCount      int32              `json:"review_count"`
	ViewerWasIn      bool               `json:"viewer_was_in"`
}

// The target's last N meetups as host or accepted participant, newest
// window first, with the aggregate the profile shows per meetup and whether
// the VIEWER was on it too (which decides whether reviewer names below are
// shown or withheld).
func (q *Queries) ListRecentMeetupsForMember(ctx context.Context, arg ListRecentMeetupsForMemberParams) ([]ListRecentMeetupsForMemberRow, error) {
	rows, err := q.db.Query(ctx, listRecentMeetupsForMember, arg.ViewerID, arg.TargetID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentMeetupsForMemberRow
	for rows.Next() {
		var i ListRecentMeetupsForMemberRow
		if err := rows.Scan(
			&i.ID,
			&i.Intent,
			&i.Status,
			&i.WindowStart,
			&i.WindowEnd,
			&i.LocationLabel,
			&i.TargetIsHost,
			&i.ParticipantCount,
			&i.OverallAverage,
			&i.ReviewCount,
			&i.ViewerWasIn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
