// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_outbox.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimNotificationOutboxBatch = `-- name: ClaimNotificationOutboxBatch :many
UPDATE meetup.notification_outbox
SET attempts = attempts + 1,
    next_attempt_at = now() + $1::interval
WHERE id IN (
  SELECT id FROM meetup.notification_outbox
  WHERE processed_at IS NULL
    AND dead_lettered_at IS NULL
    AND next_attempt_at <= now()
  ORDER BY next_attempt_at
  LIMIT $2
  FOR UPDATE SKIP LOCKED
)
RETURNING id, fcm_tokens, title, body, data, attempts
`

type ClaimNotificationOutboxBatchParams struct {
	VisibilityTimeout pgtype.Interval `json:"visibility_timeout"`
	BatchSize         int32           `json:"batch_size"`
}

type ClaimNotificationOutboxBatchRow struct {
	ID        uuid.UUID `json:"id"`
	FcmTokens []string  `json:"fcm_tokens"`
	Title     string    `json:"title"`
	Body      string    `json:"body"`
	Data      []byte    `json:"data"`
	Attempts  int32     `json:"attempts"`
}

// Claims up to $1 due rows for delivery.
//
// THIS IS AN UPDATE, NOT A SELECT, AND THAT IS THE WHOLE POINT. The obvious
// implementation — SELECT ... FOR UPDATE SKIP LOCKED, then process, then
// record the outcome — only works if the lock is HELD for the whole of the
// caller's processing. It cannot be here: processing means an FCM round trip
// over the network, and holding a Postgres transaction open across a
// third-party HTTP call is how a slow vendor turns into an exhausted
// connection pool. A degraded FCM must not be able to take the database with
// it.
//
// So the claim has to survive the lock being released, which means writing
// something. Stamping next_attempt_at into the future gives each claimed row
// a VISIBILITY TIMEOUT: it leaves the claimable set the instant this
// statement commits, so a second poller (or the next tick of this one) skips
// it without needing to know anything about who is working on it. An earlier
// version of this query released the lock without the stamp, and the
// concurrency test caught the result immediately — with four concurrent
// claimers, rows were being claimed two and three times each, which in
// production is the same user receiving the same push two and three times.
//
// FOR UPDATE SKIP LOCKED in the subquery is still load-bearing: it is what
// makes two claimers running this statement at the same moment take DISJOINT
// rows rather than one blocking on the other.
//
// Crash recovery follows from the same stamp. A claimer that dies
// mid-delivery records no outcome, so its rows simply become due again once
// the visibility timeout lapses and the next poll picks them up. Nothing has
// to detect the crash, and there is no lease table or stuck-claim reaper to
// get wrong.
//
// attempts is incremented HERE, at claim time, rather than on failure. That
// is deliberate: a delivery that crashes the process mid-flight must still
// count against the retry ceiling, or a row that reliably kills its claimer
// is retried forever. Marking failed afterwards therefore sets the backoff
// deadline but does not increment again.
//
// ORDER BY next_attempt_at matches idx_notification_outbox_claimable exactly
// (see the migration) — ordering by created_at would force an unindexed sort
// that degrades as the pending set grows. Explicit column list rather than *.
func (q *Queries) ClaimNotificationOutboxBatch(ctx context.Context, arg ClaimNotificationOutboxBatchParams) ([]ClaimNotificationOutboxBatchRow, error) {
	rows, err := q.db.Query(ctx, claimNotificationOutboxBatch, arg.VisibilityTimeout, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimNotificationOutboxBatchRow
	for rows.Next() {
		var i ClaimNotificationOutboxBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.FcmTokens,
			&i.Title,
			&i.Body,
			&i.Data,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countPendingNotifications = `-- name: CountPendingNotifications :one
SELECT count(*) FROM meetup.notification_outbox
WHERE processed_at IS NULL AND dead_lettered_at IS NULL
`

// Backs the notification_outbox_pending gauge. Uses the same predicate as
// the claimable partial index so it is an index-only scan over the pending
// set, not a table scan.
func (q *Queries) CountPendingNotifications(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingNotifications)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteDeadLetteredNotifications = `-- name: DeleteDeadLetteredNotifications :execrows
DELETE FROM meetup.notification_outbox
WHERE id IN (
  SELECT id FROM meetup.notification_outbox
  WHERE dead_lettered_at IS NOT NULL AND dead_lettered_at < $1::timestamptz
  LIMIT $2
)
`

type DeleteDeadLetteredNotificationsParams struct {
	OlderThan pgtype.Timestamptz `json:"older_than"`
	BatchSize int32              `json:"batch_size"`
}

// Retention for dead-lettered rows (§F8), kept longer than successes on
// purpose — see MarkNotificationDeadLettered.
func (q *Queries) DeleteDeadLetteredNotifications(ctx context.Context, arg DeleteDeadLetteredNotificationsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDeadLetteredNotifications, arg.OlderThan, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProcessedNotifications = `-- name: DeleteProcessedNotifications :execrows
DELETE FROM meetup.notification_outbox
WHERE id IN (
  SELECT id FROM meetup.notification_outbox
  WHERE processed_at IS NOT NULL AND processed_at < $1::timestamptz
  LIMIT $2
)
`

type DeleteProcessedNotificationsParams struct {
	OlderThan pgtype.Timestamptz `json:"older_than"`
	BatchSize int32              `json:"batch_size"`
}

// Retention for delivered rows (§F8). Batched via the id subquery rather
// than one unbounded DELETE: the first run after this ships (or after the
// job has been off for a while) could face a large backlog, and a single
// statement would hold one long transaction and a correspondingly long lock.
// The caller loops until a batch comes back short.
func (q *Queries) DeleteProcessedNotifications(ctx context.Context, arg DeleteProcessedNotificationsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProcessedNotifications, arg.OlderThan, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enqueueNotification = `-- name: EnqueueNotification :exec
INSERT INTO meetup.notification_outbox (fcm_tokens, title, body, data)
VALUES ($1::text[], $2, $3, $4)
`

type EnqueueNotificationParams struct {
	FcmTokens []string `json:"fcm_tokens"`
	Title     string   `json:"title"`
	Body      string   `json:"body"`
	Data      []byte   `json:"data"`
}

// The outbox insert (§F3). Always executed on a transaction handle that is
// ALSO carrying the business write it accompanies — that co-location is the
// entire point: the accept/reject/cancel/close and the notification it
// implies either both commit or neither does. A crash between them is not a
// window that has to be tolerated; it is a state the database will not
// produce.
func (q *Queries) EnqueueNotification(ctx context.Context, arg EnqueueNotificationParams) error {
	_, err := q.db.Exec(ctx, enqueueNotification,
		arg.FcmTokens,
		arg.Title,
		arg.Body,
		arg.Data,
	)
	return err
}

const markNotificationDeadLettered = `-- name: MarkNotificationDeadLettered :exec
UPDATE meetup.notification_outbox
SET dead_lettered_at = now(),
    last_error = $1
WHERE id = $2
`

type MarkNotificationDeadLetteredParams struct {
	LastError pgtype.Text `json:"last_error"`
	ID        uuid.UUID   `json:"id"`
}

// Terminal. The row leaves the claimable partial index (which excludes
// dead_lettered_at IS NOT NULL) and is never attempted again, but is kept —
// a permanent delivery failure is evidence someone should look at, not
// something to erase on the spot. The retention job keeps these far longer
// than successes for exactly that reason.
func (q *Queries) MarkNotificationDeadLettered(ctx context.Context, arg MarkNotificationDeadLetteredParams) error {
	_, err := q.db.Exec(ctx, markNotificationDeadLettered, arg.LastError, arg.ID)
	return err
}

const markNotificationFailed = `-- name: MarkNotificationFailed :exec
UPDATE meetup.notification_outbox
SET next_attempt_at = $1::timestamptz,
    last_error = $2
WHERE id = $3
`

type MarkNotificationFailedParams struct {
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	LastError     pgtype.Text        `json:"last_error"`
	ID            uuid.UUID          `json:"id"`
}

// A retryable failure: pull the row's next attempt back from the visibility
// timeout to its real backoff deadline, and record why. processed_at is
// untouched, so the row stays pending by construction.
//
// attempts is NOT incremented here — ClaimNotificationOutboxBatch already
// did that when it handed the row out. Incrementing in both places would
// double-count every failure and halve the effective retry budget.
func (q *Queries) MarkNotificationFailed(ctx context.Context, arg MarkNotificationFailedParams) error {
	_, err := q.db.Exec(ctx, markNotificationFailed, arg.NextAttemptAt, arg.LastError, arg.ID)
	return err
}

const markNotificationProcessed = `-- name: MarkNotificationProcessed :exec
UPDATE meetup.notification_outbox
SET processed_at = now(), last_error = NULL
WHERE id = $1
`

// The only statement that ever writes processed_at. Success is the sole path
// to it, which is what lets "processed_at IS NULL" mean "not yet delivered"
// without a status column to keep consistent.
func (q *Queries) MarkNotificationProcessed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markNotificationProcessed, id)
	return err
}
