// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// host_user_id scoping (Round 11, docs/00-project/action-tracker.md
	// § 4b-26) is defense-in-depth alongside the existing Go-level ownership
	// check in RespondToRequest/acceptRequest — meetup_requests has no
	// host_user_id column of its own, so this goes through a subquery against
	// meetups, the same relationship the Go check already enforces. The
	// Go-level check stays, this doesn't replace it.
	AcceptMeetupRequest(ctx context.Context, arg AcceptMeetupRequestParams) (MeetupMeetupRequest, error)
	// Returns the rejected rows so the caller can notify each requester
	// (backend/meetup-scheduling-PLAN.md Step E).
	AutoRejectPendingRequestsForMeetup(ctx context.Context, meetupID uuid.UUID) ([]MeetupMeetupRequest, error)
	// reason is required (validated by the service layer, ADR-020 §3) —
	// accepted participants are notified and gain a new rating-eligibility
	// path against the host, both handled in the service layer after this
	// write commits. host_user_id scoping (Round 11, docs/00-project/
	// action-tracker.md § 4b-26) is defense-in-depth alongside the existing
	// Go-level ownership check in service.go's CancelMeetup — mirrors
	// CloseMeetup's own ownership clause exactly; the Go-level check stays,
	// this doesn't replace it.
	CancelMeetup(ctx context.Context, arg CancelMeetupParams) (MeetupMeetup, error)
	// Claims up to batch_size due rows. Deliberately IDENTICAL in shape to
	// ClaimNotificationOutboxBatch — the proven claiming strategy, not a second
	// design.
	//
	// It is an UPDATE rather than a SELECT ... FOR UPDATE SKIP LOCKED held for
	// the duration of processing, for the same reason as the notification
	// version: stamping next_attempt_at into the future gives each claimed row a
	// VISIBILITY TIMEOUT, so it leaves the claimable set the instant this
	// commits and a second poller skips it without needing to know who is
	// working on it. Crash recovery follows for free — a claimer that dies
	// records no outcome, and the row becomes due again when the timeout lapses.
	// No lease table, no stuck-claim reaper.
	//
	// (The notification version's stronger motivation — never hold a Postgres
	// transaction open across a third-party HTTP call — does not apply here,
	// since this processing is database-only. The pattern is kept anyway: the
	// concurrency guarantees are the ones that matter, an earlier draft of the
	// notification query that released the lock WITHOUT the stamp was caught by
	// its concurrency test claiming rows two and three times, and having one
	// claiming strategy in this codebase rather than two is worth more than
	// micro-optimising the second one.)
	//
	// attempts is incremented at CLAIM time, not on failure, so a row that
	// crashes its claimer mid-flight still counts against the retry ceiling
	// instead of being retried forever. MarkMeetupsCompletedFailed therefore
	// sets the backoff deadline without incrementing again.
	//
	// ORDER BY next_attempt_at matches idx_meetups_completed_outbox_claimable.
	ClaimMeetupsCompletedOutboxBatch(ctx context.Context, arg ClaimMeetupsCompletedOutboxBatchParams) ([]ClaimMeetupsCompletedOutboxBatchRow, error)
	// The lifecycle poller's starting-soon sweep (ADR-025 §4), reshaped into an
	// atomic CLAIM (docs/plans/03-hardening-pass.md §C2).
	//
	// WHAT CHANGED AND WHY: this used to be a plain SELECT of candidates, with
	// the de-dup guard (starting_soon_notified_at) set afterwards, per row, once
	// the notification had been sent. That is correct for exactly one poller. It
	// is not correct for two — and horizontally scaling cmd/monolith for
	// throughput is a realistic near-term move. Two pollers ticking within the
	// same window would both SELECT the same rows before either wrote the guard,
	// and every host and participant would get the reminder twice.
	//
	// Selecting and marking in ONE statement removes that window entirely: the
	// inner SELECT takes row locks with FOR UPDATE SKIP LOCKED, so a second
	// poller running concurrently skips the locked rows rather than waiting for
	// them and then re-processing, and the UPDATE stamps the guard before the
	// transaction that claimed them can be observed by anyone else. RETURNING
	// hands back exactly the rows this caller now owns.
	//
	// The trade-off this makes deliberately: the guard is set BEFORE the
	// notification is composed rather than after, so a crash between claim and
	// notify loses that reminder. That is acceptable precisely because the
	// caller enqueues the notification into meetup.notification_outbox inside
	// THIS SAME TRANSACTION (§F3) — the claim and the queued notification commit
	// together, so there is no state where a meetup is marked notified but the
	// notification does not exist.
	ClaimMeetupsStartingSoon(ctx context.Context, batchSize int32) ([]MeetupMeetup, error)
	// The lifecycle poller's auto-close sweep (ADR-025 §4), same reshaping and
	// the same reasoning as ClaimMeetupsStartingSoon above (§C2).
	//
	// The previous shape (SELECT candidates, then a per-row conditional UPDATE)
	// already prevented double-CLOSING — the UPDATE's own WHERE clause re-checked
	// eligibility, so a second closer simply affected zero rows. What it did NOT
	// prevent was duplicate NOTIFICATION: both pollers read the same candidate,
	// both then went on to notify the host and every participant, and only one
	// of them lost the race on the UPDATE it had already sent pushes for. Claiming
	// with FOR UPDATE SKIP LOCKED means the second poller never sees the row at
	// all.
	//
	// status/window_end are still both re-checked here rather than trusted from
	// a prior read, so a concurrent manual CloseMeetup on the same row is
	// resolved by the database rather than by ordering assumptions.
	ClaimMeetupsToAutoClose(ctx context.Context, batchSize int32) ([]MeetupMeetup, error)
	// Claims up to $1 due rows for delivery.
	//
	// THIS IS AN UPDATE, NOT A SELECT, AND THAT IS THE WHOLE POINT. The obvious
	// implementation — SELECT ... FOR UPDATE SKIP LOCKED, then process, then
	// record the outcome — only works if the lock is HELD for the whole of the
	// caller's processing. It cannot be here: processing means an FCM round trip
	// over the network, and holding a Postgres transaction open across a
	// third-party HTTP call is how a slow vendor turns into an exhausted
	// connection pool. A degraded FCM must not be able to take the database with
	// it.
	//
	// So the claim has to survive the lock being released, which means writing
	// something. Stamping next_attempt_at into the future gives each claimed row
	// a VISIBILITY TIMEOUT: it leaves the claimable set the instant this
	// statement commits, so a second poller (or the next tick of this one) skips
	// it without needing to know anything about who is working on it. An earlier
	// version of this query released the lock without the stamp, and the
	// concurrency test caught the result immediately — with four concurrent
	// claimers, rows were being claimed two and three times each, which in
	// production is the same user receiving the same push two and three times.
	//
	// FOR UPDATE SKIP LOCKED in the subquery is still load-bearing: it is what
	// makes two claimers running this statement at the same moment take DISJOINT
	// rows rather than one blocking on the other.
	//
	// Crash recovery follows from the same stamp. A claimer that dies
	// mid-delivery records no outcome, so its rows simply become due again once
	// the visibility timeout lapses and the next poll picks them up. Nothing has
	// to detect the crash, and there is no lease table or stuck-claim reaper to
	// get wrong.
	//
	// attempts is incremented HERE, at claim time, rather than on failure. That
	// is deliberate: a delivery that crashes the process mid-flight must still
	// count against the retry ceiling, or a row that reliably kills its claimer
	// is retried forever. Marking failed afterwards therefore sets the backoff
	// deadline but does not increment again.
	//
	// ORDER BY next_attempt_at matches idx_notification_outbox_claimable exactly
	// (see the migration) — ordering by created_at would force an unindexed sort
	// that degrades as the pending set grows. Explicit column list rather than *.
	ClaimNotificationOutboxBatch(ctx context.Context, arg ClaimNotificationOutboxBatchParams) ([]ClaimNotificationOutboxBatchRow, error)
	// The WHERE clause's four conditions (right meetup, right host, currently
	// open-ish, window actually started) are the *entire* authorization and
	// precondition check — done in the query itself so there's no window
	// between "check" and "act" for a concurrent request to slip through
	// (ADR-016). Zero rows updated (vs. an error) means one of those four
	// failed; the service layer re-fetches to distinguish which for a useful
	// error message.
	CloseMeetup(ctx context.Context, arg CloseMeetupParams) (MeetupMeetup, error)
	// Replaces the old RecomputeUserRating UPDATE (which wrote users.
	// rating_average/rating_count directly — the exact cross-database write
	// ADR-017 flagged, only possible before the DB split because this service
	// shared auth's database). This service no longer has a users table to
	// write to at all; the aggregate is computed here (read-only, over this
	// service's own meetup_user_ratings) purely to build the rating-updated
	// outbox event payload (Step 5b) — auth's own consumer applies it to its
	// cached columns on the other side. Run inside the same transaction as
	// CreateMeetupRating, after it, same as before — the row lock nothing
	// takes anymore (there's no users row to lock in this database), so
	// correctness for concurrent raters of the same person now rests on
	// meetup_user_ratings' own UNIQUE(meetup_id, rater_user_id, rated_user_id)
	// constraint plus each recompute reading committed rows only, not on a
	// row-lock serialization point the old design incidentally had.
	ComputeUserRatingAggregate(ctx context.Context, ratedUserID uuid.UUID) (ComputeUserRatingAggregateRow, error)
	CountAcceptedRequests(ctx context.Context, meetupID uuid.UUID) (int64, error)
	// Backs the pending gauge. Same predicate as the claimable partial index, so
	// it is an index-only scan over the pending set rather than a table scan.
	CountPendingMeetupsCompleted(ctx context.Context) (int64, error)
	// Backs the notification_outbox_pending gauge. Uses the same predicate as
	// the claimable partial index so it is an index-only scan over the pending
	// set, not a table scan.
	CountPendingNotifications(ctx context.Context) (int64, error)
	CreateMeetup(ctx context.Context, arg CreateMeetupParams) (MeetupMeetup, error)
	CreateMeetupRating(ctx context.Context, arg CreateMeetupRatingParams) (MeetupMeetupUserRating, error)
	CreateMeetupRequest(ctx context.Context, arg CreateMeetupRequestParams) (MeetupMeetupRequest, error)
	// Retention for dead-lettered rows, kept longer than successes on purpose.
	DeleteDeadLetteredMeetupsCompleted(ctx context.Context, arg DeleteDeadLetteredMeetupsCompletedParams) (int64, error)
	// Retention for dead-lettered rows (§F8), kept longer than successes on
	// purpose — see MarkNotificationDeadLettered.
	DeleteDeadLetteredNotifications(ctx context.Context, arg DeleteDeadLetteredNotificationsParams) (int64, error)
	// Removes a device token FCM has reported as permanently unregistered
	// (docs/plans/03-hardening-pass.md §E2c) — app uninstalled, token rotated,
	// or wrong Firebase project. Keyed by the token itself, not by user: the
	// token identifies one physical device install, and it is the device that
	// is gone.
	//
	// Idempotent: deleting a token that is already gone affects zero rows and is
	// not an error. Two concurrent deliveries can both learn the same token is
	// dead, and neither should fail because the other got there first.
	DeleteDeviceToken(ctx context.Context, fcmToken string) error
	// Retention for done rows, batched via the id subquery rather than one
	// unbounded DELETE — same reasoning as DeleteProcessedNotifications. The
	// caller loops until a batch comes back short.
	DeleteProcessedMeetupsCompleted(ctx context.Context, arg DeleteProcessedMeetupsCompletedParams) (int64, error)
	// Retention for delivered rows (§F8). Batched via the id subquery rather
	// than one unbounded DELETE: the first run after this ships (or after the
	// job has been off for a while) could face a large backlog, and a single
	// statement would hold one long transaction and a correspondingly long lock.
	// The caller loops until a batch comes back short.
	DeleteProcessedNotifications(ctx context.Context, arg DeleteProcessedNotificationsParams) (int64, error)
	// The outbox insert, executed on the SAME transaction handle as the close or
	// the auto-close claim it accompanies. That co-location is the entire point,
	// exactly as with EnqueueNotification: the completion and the record of
	// "someone must recompute totals for these" either both commit or neither
	// does. There is no window in which a meetup is completed but its recompute
	// was never scheduled.
	//
	// Cheap by construction — one INSERT of an array of ids — which is what
	// takes the expensive recompute off the closing transaction.
	EnqueueMeetupsCompleted(ctx context.Context, meetupIds []uuid.UUID) error
	// The outbox insert (§F3). Always executed on a transaction handle that is
	// ALSO carrying the business write it accompanies — that co-location is the
	// entire point: the accept/reject/cancel/close and the notification it
	// implies either both commit or neither does. A crash between them is not a
	// window that has to be tolerated; it is a state the database will not
	// produce.
	//
	// user_id is the RECIPIENT, carried alongside the resolved tokens purely so
	// the in-app notification list can ask "what was sent to me" (migration
	// 0009). Delivery itself still uses fcm_tokens only and never reads this.
	EnqueueNotification(ctx context.Context, arg EnqueueNotificationParams) error
	// Idempotent create-if-missing — called once per participant, at meetup
	// creation for the host and at accept-time for each accepted requester
	// (ADR-024 §2). ON CONFLICT DO NOTHING rather than upsert-with-RETURNING
	// since callers always follow this with a plain Get.
	EnsureSafetyState(ctx context.Context, arg EnsureSafetyStateParams) error
	// my_request_status is the *latest* request this specific user (viewerID)
	// has made on this meetup, or NULL if they never requested — the frontend
	// uses this to render "REQUEST TO JOIN" vs. the request's current status
	// (frontend/meetup-scheduling-PLAN.md Step 3). Plain LEFT JOIN + ORDER BY
	// ... LIMIT 1, not a scalar subquery or LEFT JOIN LATERAL in the SELECT
	// list — sqlc's nullability analysis correctly infers a plain LEFT JOIN
	// column as nullable (NullMeetupRequestStatus); both of the other two forms
	// were confirmed (by generating each and inspecting the output) to produce
	// a non-nullable Go type that would panic scanning a real NULL row — a
	// viewer who's never requested to join, the common browsing case.
	//
	// Host display info comes from user_display_cache, not a live JOIN users
	// (ADR-017's addendum — users is a different database now). LEFT JOIN, not
	// JOIN — deliberately, a deviation from the plan's literal "same shape":
	// user_display_cache has no FK to enforce a row exists, and is populated
	// asynchronously by a Pub/Sub consumer (Step 6), so a meetup hosted by a
	// just-onboarded user could briefly have no cache row yet. An inner JOIN
	// would make such a meetup vanish from GetMeetupByID/listings entirely
	// until the consumer catches up; LEFT JOIN + COALESCE just shows blank
	// display fields for that brief window instead — the meetup itself is
	// never at risk of disappearing due to eventual-consistency lag.
	//
	// rating_average/rating_count are a live aggregate over this service's own
	// meetup_user_ratings, not a cached column (Step 4's note: "meetup already
	// has them locally... nothing to cache back to itself") — cross-joined via
	// a LATERAL subquery so an unrated host correctly gets 0/0 rather than
	// disappearing from a plain JOIN.
	GetMeetupByID(ctx context.Context, arg GetMeetupByIDParams) (GetMeetupByIDRow, error)
	// Plain, no join — used only inside AcceptRequest's transaction to lock the
	// row and re-check status/capacity, host display info is irrelevant there.
	GetMeetupByIDForUpdate(ctx context.Context, id uuid.UUID) (MeetupMeetup, error)
	GetMeetupFeedback(ctx context.Context, arg GetMeetupFeedbackParams) (MeetupMeetupFeedback, error)
	// Plain, no join — used inside Accept's transaction where requester
	// display info is irrelevant, and as the base row write queries (Accept/
	// Reject/Withdraw) RETURNING against. Callers needing display info should
	// use GetMeetupRequestWithRequesterInfoByID instead.
	GetMeetupRequestByID(ctx context.Context, id uuid.UUID) (MeetupMeetupRequest, error)
	// See meetup.meetups.sql's GetMeetupByID for why user_display_cache/
	// meetup_user_ratings are both LEFT JOINed (not JOIN) here.
	GetMeetupRequestWithRequesterInfoByID(ctx context.Context, id uuid.UUID) (GetMeetupRequestWithRequesterInfoByIDRow, error)
	GetSafetyState(ctx context.Context, arg GetSafetyStateParams) (MeetupSafetyState, error)
	// The rating-eligibility gate: the *rater* must have already confirmed
	// (SubmitMeetupFeedback, happened=true) that the meetup happened. The ratee
	// does not need this — a no-show is legitimately ratable by someone who did
	// attend and confirm (ADR-015).
	HasConfirmedMeetupHappened(ctx context.Context, arg HasConfirmedMeetupHappenedParams) (bool, error)
	// True if meetupID is cancelled, ratedID is that meetup's host, and
	// raterID has an accepted meetup_requests row for it (ADR-020 §3) — a
	// cancelled meetup's accepted requests stay 'accepted' (cancellation is a
	// meetup-level status change, not a per-request one), so this is a plain
	// status check, no separate "was accepted at cancellation time" column
	// needed.
	IsEligibleForCancellationRating(ctx context.Context, arg IsEligibleForCancellationRatingParams) (bool, error)
	// True if there's a meetup_requests row for meetupID with
	// status = 'withdrawn', requester_id = ratedID, and raterID is that
	// meetup's host — independent of the meetup's own status (ADR-020 §4:
	// "the meetup continues for everyone else," this is per-request, not
	// per-meetup).
	IsEligibleForWithdrawalRating(ctx context.Context, arg IsEligibleForWithdrawalRatingParams) (bool, error)
	// True if userID is the host of meetupID, or has an accepted request on it
	// — the "ratable set" (ADR-015, docs/02-domain/domain-model.md § Rating).
	IsMeetupParticipant(ctx context.Context, arg IsMeetupParticipantParams) (bool, error)
	// A user never seen by either event has no row at all — the caller maps
	// pgx.ErrNoRows to false (free/not-entitled), which is the safe default,
	// not an error.
	IsSubscriptionEntitled(ctx context.Context, userID uuid.UUID) (bool, error)
	ListDeviceTokensForUser(ctx context.Context, userID uuid.UUID) ([]MeetupDeviceToken, error)
	// Batched form of ListDeviceTokensForUser (2026-08-31 round-3 hardening,
	// internal/notifications.BatchSender) — one query for all of a fan-out's
	// recipients instead of one per recipient. user_id is part of the SELECT
	// list (not just fcm_token) so the caller can group rows back by user
	// without a second lookup.
	ListDeviceTokensForUsers(ctx context.Context, userIds []uuid.UUID) ([]MeetupDeviceToken, error)
	// Meetups this user took part in whose window has ended and which they have
	// not finished reviewing. Bounded by a cutoff so an ignored review does not
	// sit on Home forever (see service.reviewWindow).
	ListMeetupIDsAwaitingReview(ctx context.Context, arg ListMeetupIDsAwaitingReviewParams) ([]uuid.UUID, error)
	// The people on a meetup: its host, plus everyone whose request was
	// accepted. Ordered host-first, then by name, so the list reads the same way
	// every time it is fetched.
	//
	// Deliberately NOT scoped to a viewer. Who may see WHAT of this is a policy
	// question the service layer answers (see ListMeetupParticipants there) —
	// this query answers only "who is on this meetup". Mixing the two here would
	// put a trust rule in SQL where nobody reviewing the trust ladder would
	// think to look for it.
	ListMeetupParticipants(ctx context.Context, meetupID uuid.UUID) ([]ListMeetupParticipantsRow, error)
	// Keyset continuation of ListMeetupsByHostFirstPage — same
	// (created_at, id) < (cursor) shape as
	// ListOpenMeetupsByIntentAfterCursor.
	ListMeetupsByHostAfterCursor(ctx context.Context, arg ListMeetupsByHostAfterCursorParams) ([]ListMeetupsByHostAfterCursorRow, error)
	// Real cursor pagination (2026-08-31 round-3 hardening), replacing round
	// 2's flat LIMIT 200 — that fix closed the unbounded-memory risk but left
	// a hard completeness ceiling: a host past 200 meetups had no way to
	// reach the rest. Mirrors ListOpenMeetupsByIntentFirstPage's keyset shape
	// exactly (fetch limit+1 in Go, ORDER BY created_at DESC, id DESC for a
	// stable sort a plain created_at DESC alone doesn't guarantee when two
	// rows share a timestamp).
	ListMeetupsByHostFirstPage(ctx context.Context, arg ListMeetupsByHostFirstPageParams) ([]ListMeetupsByHostFirstPageRow, error)
	// Keyset continuation of ListMeetupsRequestedByUserFirstPage.
	ListMeetupsRequestedByUserAfterCursor(ctx context.Context, arg ListMeetupsRequestedByUserAfterCursorParams) ([]ListMeetupsRequestedByUserAfterCursorRow, error)
	// One row per meetup, carrying the requester's *latest* request status for
	// it (a requester can have multiple historical rows for the same meetup —
	// e.g. rejected, then withdrawn, then a fresh pending one — the UNIQUE
	// constraint is per (meetup_id, requester_id, status), not per
	// (meetup_id, requester_id) alone).
	//
	// Real cursor pagination (2026-08-31 round-3 hardening) — same fix and
	// reasoning as ListMeetupsByHostFirstPage above, applied to the
	// requested-meetups side of the same pre-existing completeness ceiling.
	ListMeetupsRequestedByUserFirstPage(ctx context.Context, arg ListMeetupsRequestedByUserFirstPageParams) ([]ListMeetupsRequestedByUserFirstPageRow, error)
	// What the viewer themselves submitted on this meetup — the read behind
	// "see the ratings we gave" on a history card. Only ever the viewer's own
	// rows (rater_user_id = viewer): a rating is private to the person who gave
	// it, and this must never become a way to read what others scored someone.
	ListMyMeetupRatings(ctx context.Context, arg ListMyMeetupRatingsParams) ([]ListMyMeetupRatingsRow, error)
	// The in-app notification list. Bounded by `since`, which the caller sets to
	// the same retention window the cleanup job uses — so the list can never
	// show a row that is about to vanish, and the two windows cannot drift.
	//
	// Dead-lettered rows are excluded: they were never delivered to anyone, so
	// showing them would be telling the user about a notification they did not
	// get.
	ListNotificationsForUser(ctx context.Context, arg ListNotificationsForUserParams) ([]ListNotificationsForUserRow, error)
	// Keyset pagination on (created_at, id) — cursorCreatedAt/cursorID are the
	// last row of the previous page, so this resumes strictly after it. Row
	// comparison (a, b) < (c, d) is a single index-friendly condition, not a
	// chain of ORs. Same DISTINCT-then-re-sort shape as the first-page query
	// above, for the same reason. See that query's comment for the
	// ST_DWithin condition below, and for why the viewer's own hosted meetups
	// (m.host_user_id = requester_id) are exempt from the 40km radius — the exemption
	// must stay identical in both queries, or a host's own out-of-range meetup
	// would appear on page 1 and then vanish from page 2 onward.
	ListOpenMeetupsAfterCursor(ctx context.Context, arg ListOpenMeetupsAfterCursorParams) ([]ListOpenMeetupsAfterCursorRow, error)
	// DISTINCT ON (m.id) + a wrapping SELECT to re-sort by recency: DISTINCT ON
	// requires its own ORDER BY to start with the same expression(s), which
	// would otherwise force sorting this page by id instead of created_at —
	// the inner query dedupes (a requester can have multiple historical
	// meetup_requests rows for the same meetup, see ListMeetupsRequestedByUser
	// above), the outer one restores the intended pagination order. Plain LEFT
	// JOIN (not LATERAL/a scalar subquery) for my_request_status, same
	// nullability reasoning as GetMeetupByID above. See GetMeetupByID for why
	// user_display_cache/meetup_user_ratings are both LEFT JOINed.
	//
	// The ST_DWithin distance condition in WHERE (ADR-021 §2 originally,
	// rewritten from a plain haversine expression to real PostGIS per
	// ADR-027) runs alongside idx_meetups_intent_status's own narrowing of
	// m.status/m.intent — the two conditions each use their own index
	// (idx_meetups_intent_status, idx_meetups_location_gist), not one
	// replacing the other. 40000 = 40km in meters (ST_DWithin on geography
	// takes meters, not degrees).
	//
	// The viewer's OWN hosted meetups are exempt from that radius: a host who
	// scheduled a meetup outside their own current 40km bubble (travelling, or
	// scheduling somewhere they'll be later) otherwise couldn't see their own
	// meetup on the browse feed at all, even though _MeetupCard already has a
	// "YOU'RE HOSTING" state ready for exactly that row. This deliberately
	// reuses sqlc.arg(requester_id) — already bound to the viewer's id for the my_request_status
	// LEFT JOIN below — rather than adding a new bound parameter, so no
	// caller/param struct changes: the same value simply does double duty.
	// Scoped to hosts only; a meetup the viewer merely has an accepted request
	// for is NOT exempted here (it already surfaces distance-unfiltered via
	// "Your Meetups"/Active Meetups).
	ListOpenMeetupsFirstPage(ctx context.Context, arg ListOpenMeetupsFirstPageParams) ([]ListOpenMeetupsFirstPageRow, error)
	// Host + accepted requesters of meetupID, excluding viewerID, each flagged
	// with whether viewerID has already rated them for this meetup. Also
	// includes (ADR-020 §3/§4):
	//   - The host is already covered for the cancellation-triggered case
	//     without any change here — this base query never filtered on
	//     meetup.meetups.status, so an accepted requester on a now-cancelled meetup
	//     already sees the host as ratable (meetup.meetup_requests.status stays
	//     'accepted' through a cancellation — it's a meetup-level change, not
	//     a per-request one). Verified explicitly by
	//     TestListRatableParticipants_IncludesCancelledMeetupHost, not just
	//     assumed from reading this comment.
	//   - Withdrawn requesters, ratable only by the host — a genuinely new
	//     source (the base query's second branch only ever selected
	//     status = 'accepted'), gated to viewer_id = host_user_id directly in
	//     this branch since a non-host viewer must never see a withdrawn
	//     requester as ratable.
	//
	// LEFT JOIN meetup.user_display_cache, not JOIN users (ADR-017's addendum — users
	// is a different database now; see meetup.meetups.sql's GetMeetupByID for the
	// full LEFT-JOIN-not-JOIN reasoning, same here) — a participant excluded
	// from this list because their display cache hasn't synced yet would be a
	// real (if narrow) correctness bug: someone ratable would silently not
	// appear to rate.
	ListRatableParticipants(ctx context.Context, arg ListRatableParticipantsParams) ([]ListRatableParticipantsRow, error)
	// LEFT JOIN meetup.safety_state (ADR-024 §6) — host visibility into each
	// accepted participant's check-in status, piggybacking on this query's
	// existing host-only ListMeetupRequests call site rather than a new
	// endpoint. A pending/rejected/withdrawn request never has a safety-state
	// row (EnsureExists only ever runs at accept-time), so these columns are
	// naturally NULL for anything that isn't accepted — no extra WHERE needed.
	// One join, not a per-row follow-up query (avoids N+1).
	ListRequestsForMeetup(ctx context.Context, meetupID uuid.UUID) ([]ListRequestsForMeetupRow, error)
	// Everyone this user has already told about this meetup, so the screen can
	// show it instead of asking again blind.
	ListSafetyShareContactIDs(ctx context.Context, arg ListSafetyShareContactIDsParams) ([]uuid.UUID, error)
	// Backs the meetup-created consumer's nearby-notification fan-out
	// (backend/geo-visibility-and-nearby-notifications-PLAN.md Step 4) — same
	// ST_DWithin condition as ListOpenMeetupsByIntentFirstPage (meetup.meetups.sql),
	// rewritten from a plain haversine expression to real PostGIS per
	// ADR-027, now against this cache table instead of the viewer's own
	// fresh coordinate. sqlc.arg(not_before) bounds staleness (Step 4: "non-
	// stale, updated_at within 24 hours") — a cache row older than that is
	// excluded rather than notifying someone about a meetup near where they
	// used to be.
	//
	// LIMIT 500 (2026-08-31 round-3 hardening) — a backstop cap even with a
	// real GiST index doing the heavy lifting: a single meetup notifying more
	// than 500 nearby users in one fan-out is worth capping regardless of how
	// fast the lookup itself is.
	ListUserLocationCacheWithinRadius(ctx context.Context, arg ListUserLocationCacheWithinRadiusParams) ([]ListUserLocationCacheWithinRadiusRow, error)
	MarkMeetupFull(ctx context.Context, id uuid.UUID) error
	// Terminal. Leaves the claimable partial index and is never attempted again,
	// but the row is kept: a permanent failure here means some users' profile
	// counts are silently stale, which is exactly the thing someone should be
	// able to find and fix.
	MarkMeetupsCompletedDeadLettered(ctx context.Context, arg MarkMeetupsCompletedDeadLetteredParams) error
	// A retryable failure: pull next_attempt_at back from the visibility timeout
	// to the real backoff deadline and record why. processed_at is untouched, so
	// the row stays pending by construction. attempts is NOT incremented here —
	// the claim already did that.
	MarkMeetupsCompletedFailed(ctx context.Context, arg MarkMeetupsCompletedFailedParams) error
	// The only statement that ever writes processed_at.
	MarkMeetupsCompletedProcessed(ctx context.Context, id uuid.UUID) error
	// Terminal. The row leaves the claimable partial index (which excludes
	// dead_lettered_at IS NOT NULL) and is never attempted again, but is kept —
	// a permanent delivery failure is evidence someone should look at, not
	// something to erase on the spot. The retention job keeps these far longer
	// than successes for exactly that reason.
	MarkNotificationDeadLettered(ctx context.Context, arg MarkNotificationDeadLetteredParams) error
	// A retryable failure: pull the row's next attempt back from the visibility
	// timeout to its real backoff deadline, and record why. processed_at is
	// untouched, so the row stays pending by construction.
	//
	// attempts is NOT incremented here — ClaimNotificationOutboxBatch already
	// did that when it handed the row out. Incrementing in both places would
	// double-count every failure and halve the effective retry budget.
	MarkNotificationFailed(ctx context.Context, arg MarkNotificationFailedParams) error
	// The only statement that ever writes processed_at. Success is the sole path
	// to it, which is what lets "processed_at IS NULL" mean "not yet delivered"
	// without a status column to keep consistent.
	MarkNotificationProcessed(ctx context.Context, id uuid.UUID) error
	// Everyone whose "meetups completed" total is changed by the meetups in
	// meetup_ids having just completed, together with each one's NEW total.
	//
	// Runs inside the same transaction that completed those meetups, so the
	// counts already include them — that is what lets the event carry an
	// absolute figure rather than a delta, and absolute is what makes the auth
	// module's consumer idempotent under redelivery (see auth/0005).
	//
	// PARTICIPANT = the host, plus every requester whose request is 'accepted'.
	// Deliberately NOT gated on the Safety Gate check-in: check-in is a safety
	// affordance people can legitimately skip, and someone who attended but
	// never opened the checklist has still completed a meetup. The same
	// definition IsParticipant uses everywhere else in this module.
	//
	// One statement rather than "list participants, then count per participant":
	// the fan-out is small (a meetup's capacity), but the 1+N version would run
	// inside the close transaction and hold it open for the round trips.
	RecomputeMeetupsCompletedForParticipants(ctx context.Context, meetupIds []uuid.UUID) ([]RecomputeMeetupsCompletedForParticipantsRow, error)
	// Records that contact_id was told about this meetup by user_id.
	//
	// ON CONFLICT DO NOTHING keeps the FIRST notified_at. Re-sharing with a
	// contact who already knows is a no-op rather than a second row (and, at the
	// service layer above, a second text message) — the primary key is what
	// makes "select all" safe to press twice.
	RecordSafetyShare(ctx context.Context, arg RecordSafetyShareParams) error
	// WHERE status = 'pending' guards against rejecting an already-resolved
	// request (double-tap, or a race with auto-reject) — zero rows affected
	// (pgx.ErrNoRows) is the repository's signal to map to apperror.ErrConflict.
	// host_user_id scoping (Round 11) added the same way as AcceptMeetupRequest
	// above — defense-in-depth alongside the existing Go-level check.
	RejectMeetupRequest(ctx context.Context, arg RejectMeetupRequestParams) (MeetupMeetupRequest, error)
	SetCheckedIn(ctx context.Context, arg SetCheckedInParams) (MeetupSafetyState, error)
	SetChecklistAck(ctx context.Context, arg SetChecklistAckParams) (MeetupSafetyState, error)
	// ADR-024 §4 — mutual exclusion with check-in is enforced at the service
	// layer (both states are visible together there), not here.
	SetDeclined(ctx context.Context, arg SetDeclinedParams) (MeetupSafetyState, error)
	SetLiveLocationOptIn(ctx context.Context, arg SetLiveLocationOptInParams) (MeetupSafetyState, error)
	// The review flow's own write: the overall 1-5 for the meetup plus the
	// optional note, and the completion stamp. Separate from
	// UpsertMeetupFeedback (the safety questions) because the two are answered
	// at different moments by different screens, and a review must never
	// silently clear a felt_safe answer given earlier.
	//
	// happened is forced true: reaching the end of the review flow IS the
	// statement that it happened, and leaving it null would make the row fail
	// HasConfirmedMeetupHappened and so refuse the very ratings being submitted
	// alongside it.
	SetMeetupOverallReview(ctx context.Context, arg SetMeetupOverallReviewParams) (MeetupMeetupFeedback, error)
	// Upserts by token, not by user — a token identifies one physical device
	// install; re-registering it under a different account reassigns
	// ownership rather than leaving a stale row.
	UpsertDeviceToken(ctx context.Context, arg UpsertDeviceTokenParams) (MeetupDeviceToken, error)
	UpsertMeetupFeedback(ctx context.Context, arg UpsertMeetupFeedbackParams) (MeetupMeetupFeedback, error)
	// The subscription-activated/subscription-deactivated consumer's
	// idempotent, order-guarded upsert — same shape as user_display_cache.sql's
	// UpsertUserDisplayCache. ON CONFLICT DO UPDATE handles redelivery safely;
	// the WHERE clause is the ordering guard, applying unconditionally on first
	// insert, otherwise only if this event is strictly newer than what is
	// already stored. Rows affected (0 or 1) tells the caller whether the guard
	// skipped a stale event, purely for logging.
	//
	// Generated through sqlc here, unlike the source, whose own
	// subscription_cache_postgres.go hand-writes this as raw pgx with a comment
	// saying the sqlc CLI "wasn't available in this environment at
	// implementation time... worth regenerating through sqlcgen for real once
	// the CLI is available". It is available here, so this is that.
	UpsertSubscriptionCache(ctx context.Context, arg UpsertSubscriptionCacheParams) (int64, error)
	// The user-onboarded/user-profile-updated consumer's idempotent,
	// order-guarded upsert (ADR-018 Decision 2, ADR-017's addendum Step 4).
	// ON CONFLICT DO UPDATE handles redelivery of the same event safely; the
	// WHERE clause on the DO UPDATE is the ordering guard — applies
	// unconditionally on first insert, otherwise only if this event is
	// strictly newer than what's already stored. Rows affected (0 or 1) tells
	// the caller whether the guard actually skipped a stale/out-of-order
	// event, purely for logging.
	UpsertUserDisplayCache(ctx context.Context, arg UpsertUserDisplayCacheParams) (int64, error)
	// The user-location-updated consumer's idempotent, order-guarded upsert —
	// same shape as meetup.user_display_cache.sql's UpsertUserDisplayCache (ADR-018
	// Decision 2). ON CONFLICT DO UPDATE handles redelivery of the same event
	// safely; the WHERE clause on the DO UPDATE is the ordering guard.
	UpsertUserLocationCache(ctx context.Context, arg UpsertUserLocationCacheParams) (int64, error)
	// Both 'pending' and 'accepted' are withdrawable (ADR-020 §4) — widened
	// from the original pending-only precondition: a requester backing out
	// *after* being accepted is exactly the case the withdrawal-rating path
	// exists for ("the meetup continues for everyone else," ADR-020's own
	// framing — only meaningful if they'd actually been accepted into it).
	// note is optional (may be NULL). Does not touch the meetup's own
	// capacity/status — a freed-up slot on a full meetup reopening is a
	// separate, not-yet-built concern. requester_id scoping (Round 11,
	// docs/00-project/action-tracker.md § 4b-26) is defense-in-depth
	// alongside the existing Go-level check in service.go's WithdrawRequest —
	// scoped to the *requester*, not the host, unlike Accept/Reject/Cancel.
	// The Go-level check stays, this doesn't replace it.
	WithdrawMeetupRequest(ctx context.Context, arg WithdrawMeetupRequestParams) (MeetupMeetupRequest, error)
}

var _ Querier = (*Queries)(nil)
