// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ratings.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const computeUserRatingAggregate = `-- name: ComputeUserRatingAggregate :one
SELECT
  COUNT(*)::int AS rating_count,
  COALESCE(ROUND(AVG(score), 2), 0)::numeric(3,2) AS rating_average
FROM meetup.meetup_user_ratings
WHERE rated_user_id = $1
`

type ComputeUserRatingAggregateRow struct {
	RatingCount   int32          `json:"rating_count"`
	RatingAverage pgtype.Numeric `json:"rating_average"`
}

// Replaces the old RecomputeUserRating UPDATE (which wrote users.
// rating_average/rating_count directly — the exact cross-database write
// ADR-017 flagged, only possible before the DB split because this service
// shared auth's database). This service no longer has a users table to
// write to at all; the aggregate is computed here (read-only, over this
// service's own meetup_user_ratings) purely to build the rating-updated
// outbox event payload (Step 5b) — auth's own consumer applies it to its
// cached columns on the other side. Run inside the same transaction as
// CreateMeetupRating, after it, same as before — the row lock nothing
// takes anymore (there's no users row to lock in this database), so
// correctness for concurrent raters of the same person now rests on
// meetup_user_ratings' own UNIQUE(meetup_id, rater_user_id, rated_user_id)
// constraint plus each recompute reading committed rows only, not on a
// row-lock serialization point the old design incidentally had.
func (q *Queries) ComputeUserRatingAggregate(ctx context.Context, ratedUserID uuid.UUID) (ComputeUserRatingAggregateRow, error) {
	row := q.db.QueryRow(ctx, computeUserRatingAggregate, ratedUserID)
	var i ComputeUserRatingAggregateRow
	err := row.Scan(&i.RatingCount, &i.RatingAverage)
	return i, err
}

const createMeetupRating = `-- name: CreateMeetupRating :one
INSERT INTO meetup.meetup_user_ratings (meetup_id, rater_user_id, rated_user_id, score, traits)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, meetup_id, rater_user_id, rated_user_id, score, created_at, traits
`

type CreateMeetupRatingParams struct {
	MeetupID    uuid.UUID `json:"meetup_id"`
	RaterUserID uuid.UUID `json:"rater_user_id"`
	RatedUserID uuid.UUID `json:"rated_user_id"`
	Score       int16     `json:"score"`
	Traits      []string  `json:"traits"`
}

func (q *Queries) CreateMeetupRating(ctx context.Context, arg CreateMeetupRatingParams) (MeetupMeetupUserRating, error) {
	row := q.db.QueryRow(ctx, createMeetupRating,
		arg.MeetupID,
		arg.RaterUserID,
		arg.RatedUserID,
		arg.Score,
		arg.Traits,
	)
	var i MeetupMeetupUserRating
	err := row.Scan(
		&i.ID,
		&i.MeetupID,
		&i.RaterUserID,
		&i.RatedUserID,
		&i.Score,
		&i.CreatedAt,
		&i.Traits,
	)
	return i, err
}

const hasConfirmedMeetupHappened = `-- name: HasConfirmedMeetupHappened :one
SELECT EXISTS(
  SELECT 1 FROM meetup.meetup_feedback WHERE meetup_id = $1 AND user_id = $2 AND happened = true
)
`

type HasConfirmedMeetupHappenedParams struct {
	MeetupID uuid.UUID `json:"meetup_id"`
	UserID   uuid.UUID `json:"user_id"`
}

// The rating-eligibility gate: the *rater* must have already confirmed
// (SubmitMeetupFeedback, happened=true) that the meetup happened. The ratee
// does not need this — a no-show is legitimately ratable by someone who did
// attend and confirm (ADR-015).
func (q *Queries) HasConfirmedMeetupHappened(ctx context.Context, arg HasConfirmedMeetupHappenedParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasConfirmedMeetupHappened, arg.MeetupID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isEligibleForCancellationRating = `-- name: IsEligibleForCancellationRating :one
SELECT EXISTS(
  SELECT 1 FROM meetup.meetups m
  WHERE m.id = $1 AND m.status = 'cancelled' AND m.host_user_id = $2
    AND EXISTS(
      SELECT 1 FROM meetup.meetup_requests r
      WHERE r.meetup_id = $1 AND r.requester_id = $3 AND r.status = 'accepted'
    )
)
`

type IsEligibleForCancellationRatingParams struct {
	MeetupID uuid.UUID `json:"meetup_id"`
	RatedID  uuid.UUID `json:"rated_id"`
	RaterID  uuid.UUID `json:"rater_id"`
}

// True if meetupID is cancelled, ratedID is that meetup's host, and
// raterID has an accepted meetup_requests row for it (ADR-020 §3) — a
// cancelled meetup's accepted requests stay 'accepted' (cancellation is a
// meetup-level status change, not a per-request one), so this is a plain
// status check, no separate "was accepted at cancellation time" column
// needed.
func (q *Queries) IsEligibleForCancellationRating(ctx context.Context, arg IsEligibleForCancellationRatingParams) (bool, error) {
	row := q.db.QueryRow(ctx, isEligibleForCancellationRating, arg.MeetupID, arg.RatedID, arg.RaterID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isEligibleForWithdrawalRating = `-- name: IsEligibleForWithdrawalRating :one
SELECT EXISTS(
  SELECT 1 FROM meetup.meetup_requests r
  JOIN meetup.meetups m ON m.id = r.meetup_id
  WHERE r.meetup_id = $1 AND r.requester_id = $2
    AND r.status = 'withdrawn' AND m.host_user_id = $3
)
`

type IsEligibleForWithdrawalRatingParams struct {
	MeetupID uuid.UUID `json:"meetup_id"`
	RatedID  uuid.UUID `json:"rated_id"`
	RaterID  uuid.UUID `json:"rater_id"`
}

// True if there's a meetup_requests row for meetupID with
// status = 'withdrawn', requester_id = ratedID, and raterID is that
// meetup's host — independent of the meetup's own status (ADR-020 §4:
// "the meetup continues for everyone else," this is per-request, not
// per-meetup).
func (q *Queries) IsEligibleForWithdrawalRating(ctx context.Context, arg IsEligibleForWithdrawalRatingParams) (bool, error) {
	row := q.db.QueryRow(ctx, isEligibleForWithdrawalRating, arg.MeetupID, arg.RatedID, arg.RaterID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isMeetupParticipant = `-- name: IsMeetupParticipant :one
SELECT EXISTS(
  SELECT 1 FROM meetup.meetups m WHERE m.id = $1 AND m.host_user_id = $2
  UNION
  SELECT 1 FROM meetup.meetup_requests r WHERE r.meetup_id = $1 AND r.requester_id = $2 AND r.status = 'accepted'
)
`

type IsMeetupParticipantParams struct {
	MeetupID uuid.UUID `json:"meetup_id"`
	UserID   uuid.UUID `json:"user_id"`
}

// True if userID is the host of meetupID, or has an accepted request on it
// — the "ratable set" (ADR-015, docs/02-domain/domain-model.md § Rating).
func (q *Queries) IsMeetupParticipant(ctx context.Context, arg IsMeetupParticipantParams) (bool, error) {
	row := q.db.QueryRow(ctx, isMeetupParticipant, arg.MeetupID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listMyMeetupRatings = `-- name: ListMyMeetupRatings :many
SELECT
  r.rated_user_id,
  COALESCE(u.full_name, '') AS full_name,
  u.profile_photo_url,
  r.score,
  r.traits
FROM meetup.meetup_user_ratings r
LEFT JOIN meetup.user_display_cache u ON u.user_id = r.rated_user_id
WHERE r.meetup_id = $1 AND r.rater_user_id = $2
ORDER BY u.full_name
`

type ListMyMeetupRatingsParams struct {
	MeetupID uuid.UUID `json:"meetup_id"`
	ViewerID uuid.UUID `json:"viewer_id"`
}

type ListMyMeetupRatingsRow struct {
	RatedUserID     uuid.UUID   `json:"rated_user_id"`
	FullName        string      `json:"full_name"`
	ProfilePhotoUrl pgtype.Text `json:"profile_photo_url"`
	Score           int16       `json:"score"`
	Traits          []string    `json:"traits"`
}

// What the viewer themselves submitted on this meetup — the read behind
// "see the ratings we gave" on a history card. Only ever the viewer's own
// rows (rater_user_id = viewer): a rating is private to the person who gave
// it, and this must never become a way to read what others scored someone.
func (q *Queries) ListMyMeetupRatings(ctx context.Context, arg ListMyMeetupRatingsParams) ([]ListMyMeetupRatingsRow, error) {
	rows, err := q.db.Query(ctx, listMyMeetupRatings, arg.MeetupID, arg.ViewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMyMeetupRatingsRow
	for rows.Next() {
		var i ListMyMeetupRatingsRow
		if err := rows.Scan(
			&i.RatedUserID,
			&i.FullName,
			&i.ProfilePhotoUrl,
			&i.Score,
			&i.Traits,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRatableParticipants = `-- name: ListRatableParticipants :many
SELECT
  participants.user_id,
  COALESCE(u.full_name, '') AS full_name,
  u.profile_photo_url,
  COALESCE(u.trust_level, 0) AS trust_level,
  (mr.id IS NOT NULL)::boolean AS already_rated,
  participants.context_note
FROM (
  SELECT m.host_user_id AS user_id, NULL::text AS context_note
  FROM meetup.meetups m WHERE m.id = $1
  UNION
  SELECT r.requester_id AS user_id, NULL::text AS context_note
  FROM meetup.meetup_requests r WHERE r.meetup_id = $1 AND r.status = 'accepted'
  UNION
  SELECT r.requester_id AS user_id, r.withdrawal_note AS context_note
  FROM meetup.meetup_requests r
  JOIN meetup.meetups m ON m.id = r.meetup_id
  WHERE r.meetup_id = $1 AND r.status = 'withdrawn' AND m.host_user_id = $2
) participants
LEFT JOIN meetup.user_display_cache u ON u.user_id = participants.user_id
LEFT JOIN meetup.meetup_user_ratings mr
  ON mr.meetup_id = $1 AND mr.rater_user_id = $2 AND mr.rated_user_id = participants.user_id
WHERE participants.user_id <> $2
`

type ListRatableParticipantsParams struct {
	MeetupID uuid.UUID `json:"meetup_id"`
	ViewerID uuid.UUID `json:"viewer_id"`
}

type ListRatableParticipantsRow struct {
	UserID          uuid.UUID   `json:"user_id"`
	FullName        string      `json:"full_name"`
	ProfilePhotoUrl pgtype.Text `json:"profile_photo_url"`
	TrustLevel      int16       `json:"trust_level"`
	AlreadyRated    bool        `json:"already_rated"`
	ContextNote     pgtype.Text `json:"context_note"`
}

// Host + accepted requesters of meetupID, excluding viewerID, each flagged
// with whether viewerID has already rated them for this meetup. Also
// includes (ADR-020 §3/§4):
//   - The host is already covered for the cancellation-triggered case
//     without any change here — this base query never filtered on
//     meetup.meetups.status, so an accepted requester on a now-cancelled meetup
//     already sees the host as ratable (meetup.meetup_requests.status stays
//     'accepted' through a cancellation — it's a meetup-level change, not
//     a per-request one). Verified explicitly by
//     TestListRatableParticipants_IncludesCancelledMeetupHost, not just
//     assumed from reading this comment.
//   - Withdrawn requesters, ratable only by the host — a genuinely new
//     source (the base query's second branch only ever selected
//     status = 'accepted'), gated to viewer_id = host_user_id directly in
//     this branch since a non-host viewer must never see a withdrawn
//     requester as ratable.
//
// LEFT JOIN meetup.user_display_cache, not JOIN users (ADR-017's addendum — users
// is a different database now; see meetup.meetups.sql's GetMeetupByID for the
// full LEFT-JOIN-not-JOIN reasoning, same here) — a participant excluded
// from this list because their display cache hasn't synced yet would be a
// real (if narrow) correctness bug: someone ratable would silently not
// appear to rate.
func (q *Queries) ListRatableParticipants(ctx context.Context, arg ListRatableParticipantsParams) ([]ListRatableParticipantsRow, error) {
	rows, err := q.db.Query(ctx, listRatableParticipants, arg.MeetupID, arg.ViewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRatableParticipantsRow
	for rows.Next() {
		var i ListRatableParticipantsRow
		if err := rows.Scan(
			&i.UserID,
			&i.FullName,
			&i.ProfilePhotoUrl,
			&i.TrustLevel,
			&i.AlreadyRated,
			&i.ContextNote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
