// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: safety_state.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const ensureSafetyState = `-- name: EnsureSafetyState :exec
INSERT INTO meetup.safety_state (meetup_id, user_id) VALUES ($1, $2)
ON CONFLICT (meetup_id, user_id) DO NOTHING
`

type EnsureSafetyStateParams struct {
	MeetupID uuid.UUID `json:"meetup_id"`
	UserID   uuid.UUID `json:"user_id"`
}

// Idempotent create-if-missing — called once per participant, at meetup
// creation for the host and at accept-time for each accepted requester
// (ADR-024 §2). ON CONFLICT DO NOTHING rather than upsert-with-RETURNING
// since callers always follow this with a plain Get.
func (q *Queries) EnsureSafetyState(ctx context.Context, arg EnsureSafetyStateParams) error {
	_, err := q.db.Exec(ctx, ensureSafetyState, arg.MeetupID, arg.UserID)
	return err
}

const getSafetyState = `-- name: GetSafetyState :one
SELECT meetup_id, user_id, checklist_ack_at, live_location_opt_in, checked_in_at, declined_at, decline_reason, updated_at FROM meetup.safety_state WHERE meetup_id = $1 AND user_id = $2
`

type GetSafetyStateParams struct {
	MeetupID uuid.UUID `json:"meetup_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) GetSafetyState(ctx context.Context, arg GetSafetyStateParams) (MeetupSafetyState, error) {
	row := q.db.QueryRow(ctx, getSafetyState, arg.MeetupID, arg.UserID)
	var i MeetupSafetyState
	err := row.Scan(
		&i.MeetupID,
		&i.UserID,
		&i.ChecklistAckAt,
		&i.LiveLocationOptIn,
		&i.CheckedInAt,
		&i.DeclinedAt,
		&i.DeclineReason,
		&i.UpdatedAt,
	)
	return i, err
}

const listSafetyShareContactIDs = `-- name: ListSafetyShareContactIDs :many
SELECT contact_id
  FROM meetup.safety_share
 WHERE meetup_id = $1
   AND user_id = $2
 ORDER BY notified_at
`

type ListSafetyShareContactIDsParams struct {
	MeetupID uuid.UUID `json:"meetup_id"`
	UserID   uuid.UUID `json:"user_id"`
}

// Everyone this user has already told about this meetup, so the screen can
// show it instead of asking again blind.
func (q *Queries) ListSafetyShareContactIDs(ctx context.Context, arg ListSafetyShareContactIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listSafetyShareContactIDs, arg.MeetupID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var contact_id uuid.UUID
		if err := rows.Scan(&contact_id); err != nil {
			return nil, err
		}
		items = append(items, contact_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordSafetyShare = `-- name: RecordSafetyShare :exec
INSERT INTO meetup.safety_share (meetup_id, user_id, contact_id)
VALUES ($1, $2, $3)
ON CONFLICT (meetup_id, user_id, contact_id) DO NOTHING
`

type RecordSafetyShareParams struct {
	MeetupID  uuid.UUID `json:"meetup_id"`
	UserID    uuid.UUID `json:"user_id"`
	ContactID uuid.UUID `json:"contact_id"`
}

// Records that contact_id was told about this meetup by user_id.
//
// ON CONFLICT DO NOTHING keeps the FIRST notified_at. Re-sharing with a
// contact who already knows is a no-op rather than a second row (and, at the
// service layer above, a second text message) — the primary key is what
// makes "select all" safe to press twice.
func (q *Queries) RecordSafetyShare(ctx context.Context, arg RecordSafetyShareParams) error {
	_, err := q.db.Exec(ctx, recordSafetyShare, arg.MeetupID, arg.UserID, arg.ContactID)
	return err
}

const setCheckedIn = `-- name: SetCheckedIn :one
UPDATE meetup.safety_state SET checked_in_at = now()
WHERE meetup_id = $1 AND user_id = $2
RETURNING meetup_id, user_id, checklist_ack_at, live_location_opt_in, checked_in_at, declined_at, decline_reason, updated_at
`

type SetCheckedInParams struct {
	MeetupID uuid.UUID `json:"meetup_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) SetCheckedIn(ctx context.Context, arg SetCheckedInParams) (MeetupSafetyState, error) {
	row := q.db.QueryRow(ctx, setCheckedIn, arg.MeetupID, arg.UserID)
	var i MeetupSafetyState
	err := row.Scan(
		&i.MeetupID,
		&i.UserID,
		&i.ChecklistAckAt,
		&i.LiveLocationOptIn,
		&i.CheckedInAt,
		&i.DeclinedAt,
		&i.DeclineReason,
		&i.UpdatedAt,
	)
	return i, err
}

const setChecklistAck = `-- name: SetChecklistAck :one
UPDATE meetup.safety_state SET checklist_ack_at = now()
WHERE meetup_id = $1 AND user_id = $2
RETURNING meetup_id, user_id, checklist_ack_at, live_location_opt_in, checked_in_at, declined_at, decline_reason, updated_at
`

type SetChecklistAckParams struct {
	MeetupID uuid.UUID `json:"meetup_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) SetChecklistAck(ctx context.Context, arg SetChecklistAckParams) (MeetupSafetyState, error) {
	row := q.db.QueryRow(ctx, setChecklistAck, arg.MeetupID, arg.UserID)
	var i MeetupSafetyState
	err := row.Scan(
		&i.MeetupID,
		&i.UserID,
		&i.ChecklistAckAt,
		&i.LiveLocationOptIn,
		&i.CheckedInAt,
		&i.DeclinedAt,
		&i.DeclineReason,
		&i.UpdatedAt,
	)
	return i, err
}

const setDeclined = `-- name: SetDeclined :one
UPDATE meetup.safety_state SET declined_at = now(), decline_reason = $3
WHERE meetup_id = $1 AND user_id = $2
RETURNING meetup_id, user_id, checklist_ack_at, live_location_opt_in, checked_in_at, declined_at, decline_reason, updated_at
`

type SetDeclinedParams struct {
	MeetupID      uuid.UUID   `json:"meetup_id"`
	UserID        uuid.UUID   `json:"user_id"`
	DeclineReason pgtype.Text `json:"decline_reason"`
}

// ADR-024 §4 — mutual exclusion with check-in is enforced at the service
// layer (both states are visible together there), not here.
func (q *Queries) SetDeclined(ctx context.Context, arg SetDeclinedParams) (MeetupSafetyState, error) {
	row := q.db.QueryRow(ctx, setDeclined, arg.MeetupID, arg.UserID, arg.DeclineReason)
	var i MeetupSafetyState
	err := row.Scan(
		&i.MeetupID,
		&i.UserID,
		&i.ChecklistAckAt,
		&i.LiveLocationOptIn,
		&i.CheckedInAt,
		&i.DeclinedAt,
		&i.DeclineReason,
		&i.UpdatedAt,
	)
	return i, err
}

const setLiveLocationOptIn = `-- name: SetLiveLocationOptIn :one
UPDATE meetup.safety_state SET live_location_opt_in = $3
WHERE meetup_id = $1 AND user_id = $2
RETURNING meetup_id, user_id, checklist_ack_at, live_location_opt_in, checked_in_at, declined_at, decline_reason, updated_at
`

type SetLiveLocationOptInParams struct {
	MeetupID          uuid.UUID `json:"meetup_id"`
	UserID            uuid.UUID `json:"user_id"`
	LiveLocationOptIn bool      `json:"live_location_opt_in"`
}

func (q *Queries) SetLiveLocationOptIn(ctx context.Context, arg SetLiveLocationOptInParams) (MeetupSafetyState, error) {
	row := q.db.QueryRow(ctx, setLiveLocationOptIn, arg.MeetupID, arg.UserID, arg.LiveLocationOptIn)
	var i MeetupSafetyState
	err := row.Scan(
		&i.MeetupID,
		&i.UserID,
		&i.ChecklistAckAt,
		&i.LiveLocationOptIn,
		&i.CheckedInAt,
		&i.DeclinedAt,
		&i.DeclineReason,
		&i.UpdatedAt,
	)
	return i, err
}
