// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_location_cache.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listUserLocationCacheWithinRadius = `-- name: ListUserLocationCacheWithinRadius :many
SELECT user_id, lat, lng, updated_at
FROM meetup.user_location_cache
WHERE updated_at > $1::timestamptz
  AND ST_DWithin(
    location,
    ST_SetSRID(ST_MakePoint($2::float8, $3::float8), 4326)::geography,
    50000
  )
LIMIT 500
`

type ListUserLocationCacheWithinRadiusParams struct {
	NotBefore pgtype.Timestamptz `json:"not_before"`
	CenterLng float64            `json:"center_lng"`
	CenterLat float64            `json:"center_lat"`
}

type ListUserLocationCacheWithinRadiusRow struct {
	UserID    uuid.UUID          `json:"user_id"`
	Lat       float64            `json:"lat"`
	Lng       float64            `json:"lng"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Backs the meetup-created consumer's nearby-notification fan-out
// (backend/geo-visibility-and-nearby-notifications-PLAN.md Step 4) — same
// ST_DWithin condition as ListOpenMeetupsByIntentFirstPage (meetup.meetups.sql),
// rewritten from a plain haversine expression to real PostGIS per
// ADR-027, now against this cache table instead of the viewer's own
// fresh coordinate. sqlc.arg(not_before) bounds staleness (Step 4: "non-
// stale, updated_at within 24 hours") — a cache row older than that is
// excluded rather than notifying someone about a meetup near where they
// used to be.
//
// LIMIT 500 (2026-08-31 round-3 hardening) — a backstop cap even with a
// real GiST index doing the heavy lifting: a single meetup notifying more
// than 500 nearby users in one fan-out is worth capping regardless of how
// fast the lookup itself is.
func (q *Queries) ListUserLocationCacheWithinRadius(ctx context.Context, arg ListUserLocationCacheWithinRadiusParams) ([]ListUserLocationCacheWithinRadiusRow, error) {
	rows, err := q.db.Query(ctx, listUserLocationCacheWithinRadius, arg.NotBefore, arg.CenterLng, arg.CenterLat)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserLocationCacheWithinRadiusRow
	for rows.Next() {
		var i ListUserLocationCacheWithinRadiusRow
		if err := rows.Scan(
			&i.UserID,
			&i.Lat,
			&i.Lng,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserLocationCache = `-- name: UpsertUserLocationCache :execrows
INSERT INTO meetup.user_location_cache (user_id, lat, lng, updated_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE
SET lat = excluded.lat,
    lng = excluded.lng,
    updated_at = excluded.updated_at
WHERE excluded.updated_at > meetup.user_location_cache.updated_at
`

type UpsertUserLocationCacheParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	Lat       float64            `json:"lat"`
	Lng       float64            `json:"lng"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// The user-location-updated consumer's idempotent, order-guarded upsert —
// same shape as meetup.user_display_cache.sql's UpsertUserDisplayCache (ADR-018
// Decision 2). ON CONFLICT DO UPDATE handles redelivery of the same event
// safely; the WHERE clause on the DO UPDATE is the ordering guard.
func (q *Queries) UpsertUserLocationCache(ctx context.Context, arg UpsertUserLocationCacheParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertUserLocationCache,
		arg.UserID,
		arg.Lat,
		arg.Lng,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
