// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_display_cache.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const upsertUserDisplayCache = `-- name: UpsertUserDisplayCache :execrows
INSERT INTO meetup.user_display_cache (user_id, full_name, profile_photo_url, trust_level, updated_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id) DO UPDATE
SET full_name = excluded.full_name,
    profile_photo_url = excluded.profile_photo_url,
    trust_level = excluded.trust_level,
    updated_at = excluded.updated_at
WHERE excluded.updated_at > meetup.user_display_cache.updated_at
`

type UpsertUserDisplayCacheParams struct {
	UserID          uuid.UUID          `json:"user_id"`
	FullName        string             `json:"full_name"`
	ProfilePhotoUrl pgtype.Text        `json:"profile_photo_url"`
	TrustLevel      int16              `json:"trust_level"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

// The user-onboarded/user-profile-updated consumer's idempotent,
// order-guarded upsert (ADR-018 Decision 2, ADR-017's addendum Step 4).
// ON CONFLICT DO UPDATE handles redelivery of the same event safely; the
// WHERE clause on the DO UPDATE is the ordering guard — applies
// unconditionally on first insert, otherwise only if this event is
// strictly newer than what's already stored. Rows affected (0 or 1) tells
// the caller whether the guard actually skipped a stale/out-of-order
// event, purely for logging.
func (q *Queries) UpsertUserDisplayCache(ctx context.Context, arg UpsertUserDisplayCacheParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertUserDisplayCache,
		arg.UserID,
		arg.FullName,
		arg.ProfilePhotoUrl,
		arg.TrustLevel,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
