// File generated by hand from the real Firebase console config files
// (frontend/android/app/google-services.json,
// frontend/ios/Runner/GoogleService-Info.plist) rather than via the
// `flutterfire configure` CLI, to avoid needing an interactive Firebase
// CLI login on this machine — the values are identical either way, since
// `flutterfire configure` only ever extracts them from these same two
// files. If `flutterfire configure` is ever run for real later (e.g. to
// add a web/macOS app), let it overwrite this file rather than
// hand-editing around it.
//
// Project: professional-meetups-976d2 (Firebase Hosting for the LinkedIn
// OAuth bridge page already lives on this same project — see
// docs/04-decisions/adr-011-linkedin-onboarding-slice-design.md — FCM
// reuses it rather than a second project).

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Only Android and iOS apps exist in the Firebase console for this
/// project today — no web/macOS/Windows/Linux app has been created, so
/// [currentPlatform] throws for anything else rather than returning
/// silently-wrong options.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web — '
        'no web app exists in the professional-meetups-976d2 Firebase '
        'project. Add one in the console and regenerate this file if '
        'web support is ever needed.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform '
          '($defaultTargetPlatform) — only Android and iOS apps exist in '
          'the professional-meetups-976d2 Firebase project today.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHXpJo26EOccLmyF39GkkcBNucg3626T8',
    appId: '1:762300092898:android:f5cbcf66dd507cdfae69bb',
    messagingSenderId: '762300092898',
    projectId: 'professional-meetups-976d2',
    storageBucket: 'professional-meetups-976d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSAdGsEgZEs3A5ogcYItb1CeaxFuPM_xM',
    appId: '1:762300092898:ios:d93232f8987672a7ae69bb',
    messagingSenderId: '762300092898',
    projectId: 'professional-meetups-976d2',
    storageBucket: 'professional-meetups-976d2.firebasestorage.app',
    iosBundleId: 'com.profconn.professionalConnectionsPlatform',
  );
}
