// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: auth/v1/auth.proto

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IdentityProviderProto — LINKEDIN is valid for LinkIdentityRequest (the
// Profile "Connect LinkedIn" flow) but never for CompleteFederatedSignup,
// which only ever accepts APPLE/GOOGLE (LinkedIn's own direct-signup path
// is CompleteLinkedInOnboarding, unchanged from ADR-011, not this RPC).
type IdentityProviderProto int32

const (
	IdentityProviderProto_IDENTITY_PROVIDER_UNSPECIFIED IdentityProviderProto = 0
	IdentityProviderProto_IDENTITY_PROVIDER_APPLE       IdentityProviderProto = 1
	IdentityProviderProto_IDENTITY_PROVIDER_GOOGLE      IdentityProviderProto = 2
	IdentityProviderProto_IDENTITY_PROVIDER_LINKEDIN    IdentityProviderProto = 3
)

// Enum value maps for IdentityProviderProto.
var (
	IdentityProviderProto_name = map[int32]string{
		0: "IDENTITY_PROVIDER_UNSPECIFIED",
		1: "IDENTITY_PROVIDER_APPLE",
		2: "IDENTITY_PROVIDER_GOOGLE",
		3: "IDENTITY_PROVIDER_LINKEDIN",
	}
	IdentityProviderProto_value = map[string]int32{
		"IDENTITY_PROVIDER_UNSPECIFIED": 0,
		"IDENTITY_PROVIDER_APPLE":       1,
		"IDENTITY_PROVIDER_GOOGLE":      2,
		"IDENTITY_PROVIDER_LINKEDIN":    3,
	}
)

func (x IdentityProviderProto) Enum() *IdentityProviderProto {
	p := new(IdentityProviderProto)
	*p = x
	return p
}

func (x IdentityProviderProto) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IdentityProviderProto) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_v1_auth_proto_enumTypes[0].Descriptor()
}

func (IdentityProviderProto) Type() protoreflect.EnumType {
	return &file_auth_v1_auth_proto_enumTypes[0]
}

func (x IdentityProviderProto) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IdentityProviderProto.Descriptor instead.
func (IdentityProviderProto) EnumDescriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

// VerificationPurpose is shared across phone/personal-email/corporate-email
// — one OTP mechanism, three purposes (backend/PLAN.md's addendum, Step
// C/D), not three separate mechanisms. Redundant with which RPC is called
// (StartPhoneVerification vs. StartPersonalEmailVerification, etc.) by
// design — the service layer asserts the two agree, catching a
// mismatched-purpose client bug rather than silently trusting the RPC
// choice alone.
type VerificationPurpose int32

const (
	VerificationPurpose_VERIFICATION_PURPOSE_UNSPECIFIED     VerificationPurpose = 0
	VerificationPurpose_VERIFICATION_PURPOSE_PHONE           VerificationPurpose = 1
	VerificationPurpose_VERIFICATION_PURPOSE_PERSONAL_EMAIL  VerificationPurpose = 2
	VerificationPurpose_VERIFICATION_PURPOSE_CORPORATE_EMAIL VerificationPurpose = 3
	// Email+password signup (ADR-014 decision #2) — StartEmailSignup is
	// unauthenticated, so StartVerificationRequest.user_id is always "" for
	// this purpose; the service layer routes it to the target-keyed
	// verification_codes methods instead (migration 0004), not the
	// userID-keyed ones the other three purposes use.
	VerificationPurpose_VERIFICATION_PURPOSE_EMAIL_SIGNUP VerificationPurpose = 4
	// Passwordless email login (ADR-019 §1) — StartEmailLogin is
	// unauthenticated, so StartVerificationRequest.user_id is always "" for
	// this purpose too; routed to the same target-keyed verification_codes
	// methods VERIFICATION_PURPOSE_EMAIL_SIGNUP uses, but verified against
	// an already-existing account (CompleteEmailLogin) rather than
	// creating/recovering one.
	VerificationPurpose_VERIFICATION_PURPOSE_EMAIL_LOGIN VerificationPurpose = 5
)

// Enum value maps for VerificationPurpose.
var (
	VerificationPurpose_name = map[int32]string{
		0: "VERIFICATION_PURPOSE_UNSPECIFIED",
		1: "VERIFICATION_PURPOSE_PHONE",
		2: "VERIFICATION_PURPOSE_PERSONAL_EMAIL",
		3: "VERIFICATION_PURPOSE_CORPORATE_EMAIL",
		4: "VERIFICATION_PURPOSE_EMAIL_SIGNUP",
		5: "VERIFICATION_PURPOSE_EMAIL_LOGIN",
	}
	VerificationPurpose_value = map[string]int32{
		"VERIFICATION_PURPOSE_UNSPECIFIED":     0,
		"VERIFICATION_PURPOSE_PHONE":           1,
		"VERIFICATION_PURPOSE_PERSONAL_EMAIL":  2,
		"VERIFICATION_PURPOSE_CORPORATE_EMAIL": 3,
		"VERIFICATION_PURPOSE_EMAIL_SIGNUP":    4,
		"VERIFICATION_PURPOSE_EMAIL_LOGIN":     5,
	}
)

func (x VerificationPurpose) Enum() *VerificationPurpose {
	p := new(VerificationPurpose)
	*p = x
	return p
}

func (x VerificationPurpose) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VerificationPurpose) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_v1_auth_proto_enumTypes[1].Descriptor()
}

func (VerificationPurpose) Type() protoreflect.EnumType {
	return &file_auth_v1_auth_proto_enumTypes[1]
}

func (x VerificationPurpose) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VerificationPurpose.Descriptor instead.
func (VerificationPurpose) EnumDescriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

type CompleteFederatedSignupRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Provider            IdentityProviderProto  `protobuf:"varint,1,opt,name=provider,proto3,enum=auth.v1.IdentityProviderProto" json:"provider,omitempty"`
	IdToken             string                 `protobuf:"bytes,2,opt,name=id_token,json=idToken,proto3" json:"id_token,omitempty"`
	AgeConfirmedOver_18 bool                   `protobuf:"varint,3,opt,name=age_confirmed_over_18,json=ageConfirmedOver18,proto3" json:"age_confirmed_over_18,omitempty"`
	// nonce is a DELIBERATE ADDITION over the sibling repo's contract, not a
	// port — it closes the id_token replay window the source leaves open by
	// never checking this claim (docs/security-review-framework.md,
	// Authenticity). Required: an empty value is rejected, never treated as
	// "skip the check".
	//
	// IT IS THE PRE-IMAGE, NOT THE CLAIM VALUE. The client generates a random
	// value, hands the provider SHA-256(value) as the sign-in request's nonce
	// (which is what Apple/Google embed in the id_token), and sends the RAW
	// value here. The server hashes it and compares.
	//
	// Sending the claim value itself would make the check decorative: a JWT's
	// nonce claim is readable by anyone holding the token, so an attacker who
	// obtained an id_token could read it out and submit it right back. The
	// pre-image is what they cannot produce. Same construction Apple documents
	// for Sign in with Apple and that Firebase's own
	// OAuthProvider.credential(idToken:rawNonce:) uses.
	Nonce         string `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteFederatedSignupRequest) Reset() {
	*x = CompleteFederatedSignupRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteFederatedSignupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteFederatedSignupRequest) ProtoMessage() {}

func (x *CompleteFederatedSignupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteFederatedSignupRequest.ProtoReflect.Descriptor instead.
func (*CompleteFederatedSignupRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *CompleteFederatedSignupRequest) GetProvider() IdentityProviderProto {
	if x != nil {
		return x.Provider
	}
	return IdentityProviderProto_IDENTITY_PROVIDER_UNSPECIFIED
}

func (x *CompleteFederatedSignupRequest) GetIdToken() string {
	if x != nil {
		return x.IdToken
	}
	return ""
}

func (x *CompleteFederatedSignupRequest) GetAgeConfirmedOver_18() bool {
	if x != nil {
		return x.AgeConfirmedOver_18
	}
	return false
}

func (x *CompleteFederatedSignupRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

type CompleteLinkedInOnboardingRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AuthorizationCode   string                 `protobuf:"bytes,1,opt,name=authorization_code,json=authorizationCode,proto3" json:"authorization_code,omitempty"`
	RedirectUri         string                 `protobuf:"bytes,2,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"` // must exactly match the URI used to start the flow
	AgeConfirmedOver_18 bool                   `protobuf:"varint,3,opt,name=age_confirmed_over_18,json=ageConfirmedOver18,proto3" json:"age_confirmed_over_18,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CompleteLinkedInOnboardingRequest) Reset() {
	*x = CompleteLinkedInOnboardingRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteLinkedInOnboardingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteLinkedInOnboardingRequest) ProtoMessage() {}

func (x *CompleteLinkedInOnboardingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteLinkedInOnboardingRequest.ProtoReflect.Descriptor instead.
func (*CompleteLinkedInOnboardingRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *CompleteLinkedInOnboardingRequest) GetAuthorizationCode() string {
	if x != nil {
		return x.AuthorizationCode
	}
	return ""
}

func (x *CompleteLinkedInOnboardingRequest) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

func (x *CompleteLinkedInOnboardingRequest) GetAgeConfirmedOver_18() bool {
	if x != nil {
		return x.AgeConfirmedOver_18
	}
	return false
}

type LinkIdentityRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	UserId   string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // set by gateway from verified JWT
	Provider IdentityProviderProto  `protobuf:"varint,2,opt,name=provider,proto3,enum=auth.v1.IdentityProviderProto" json:"provider,omitempty"`
	IdToken  string                 `protobuf:"bytes,3,opt,name=id_token,json=idToken,proto3" json:"id_token,omitempty"` // Apple/Google branch: native-SDK id_token, verified via internal/identity
	// LinkedIn branch: its flow is authorization-code, not a native-SDK
	// id_token like Apple/Google, so it needs its own pair of fields on this
	// one generic message rather than a second RPC.
	AuthorizationCode string `protobuf:"bytes,4,opt,name=authorization_code,json=authorizationCode,proto3" json:"authorization_code,omitempty"`
	RedirectUri       string `protobuf:"bytes,5,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"` // must exactly match the URI used to start the flow
	// nonce accompanies id_token on the Apple/Google branch, exactly as on
	// CompleteFederatedSignupRequest above — the raw pre-image, not the
	// token's claim value. Ignored on the LinkedIn branch, which has no
	// id_token to bind it to and is protected by its own state parameter
	// instead.
	Nonce         string `protobuf:"bytes,6,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkIdentityRequest) Reset() {
	*x = LinkIdentityRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkIdentityRequest) ProtoMessage() {}

func (x *LinkIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkIdentityRequest.ProtoReflect.Descriptor instead.
func (*LinkIdentityRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *LinkIdentityRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LinkIdentityRequest) GetProvider() IdentityProviderProto {
	if x != nil {
		return x.Provider
	}
	return IdentityProviderProto_IDENTITY_PROVIDER_UNSPECIFIED
}

func (x *LinkIdentityRequest) GetIdToken() string {
	if x != nil {
		return x.IdToken
	}
	return ""
}

func (x *LinkIdentityRequest) GetAuthorizationCode() string {
	if x != nil {
		return x.AuthorizationCode
	}
	return ""
}

func (x *LinkIdentityRequest) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

func (x *LinkIdentityRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

// GuestSignupRequest carries only the age attestation — a guest supplies
// nothing else, by design.
type GuestSignupRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AgeConfirmedOver_18 bool                   `protobuf:"varint,1,opt,name=age_confirmed_over_18,json=ageConfirmedOver18,proto3" json:"age_confirmed_over_18,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GuestSignupRequest) Reset() {
	*x = GuestSignupRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuestSignupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuestSignupRequest) ProtoMessage() {}

func (x *GuestSignupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuestSignupRequest.ProtoReflect.Descriptor instead.
func (*GuestSignupRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *GuestSignupRequest) GetAgeConfirmedOver_18() bool {
	if x != nil {
		return x.AgeConfirmedOver_18
	}
	return false
}

type CompleteEmailSignupRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Email               string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Code                string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"` // the OTP just verified via StartEmailSignup
	AgeConfirmedOver_18 bool                   `protobuf:"varint,4,opt,name=age_confirmed_over_18,json=ageConfirmedOver18,proto3" json:"age_confirmed_over_18,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CompleteEmailSignupRequest) Reset() {
	*x = CompleteEmailSignupRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteEmailSignupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteEmailSignupRequest) ProtoMessage() {}

func (x *CompleteEmailSignupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteEmailSignupRequest.ProtoReflect.Descriptor instead.
func (*CompleteEmailSignupRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *CompleteEmailSignupRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CompleteEmailSignupRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CompleteEmailSignupRequest) GetAgeConfirmedOver_18() bool {
	if x != nil {
		return x.AgeConfirmedOver_18
	}
	return false
}

// SessionResponse is what every session-issuing RPC returns. ADR-001 §6:
// there is deliberately no access_token field here (fields 2 and 4 are
// reserved, not reused) — the monolith never holds the JWT private key, so
// it cannot mint one. It returns the identity facts the gateway needs to
// sign a token itself: user_id and trust_level become the JWT's two custom
// claims, and the gateway fills access_token/expires_in into its own REST
// response afterwards.
//
// refresh_token IS still returned by the monolith (the raw value, exactly
// once) — unlike the access token, a refresh token is a database row this
// module owns and rotates (auth.refresh_tokens); only its SHA-256 hash is
// ever stored, so the raw value has to come back from whoever generated it.
// See docs/plans/01-phase1-scaffold-gateway-auth.md Step 3, which specifies
// this field precisely ("the new refresh-token row's raw value").
type SessionResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	UserId       string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RefreshToken string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	IsNewUser    bool                   `protobuf:"varint,5,opt,name=is_new_user,json=isNewUser,proto3" json:"is_new_user,omitempty"`
	// full_name and profile_photo_url are the values captured from LinkedIn's
	// userinfo response at account creation (see internal/modules/auth's
	// CompleteLinkedInOnboarding) and already persisted on the user row —
	// returned here because there is no separate GET /v1/users/me endpoint
	// yet for a client to fetch them from afterward.
	FullName        string `protobuf:"bytes,6,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	ProfilePhotoUrl string `protobuf:"bytes,7,opt,name=profile_photo_url,json=profilePhotoUrl,proto3" json:"profile_photo_url,omitempty"`
	// trust_level is new relative to the sibling repo's SessionResponse
	// (ADR-001 §6): the auth service used to put this claim into the token
	// itself, so it never had to travel over the wire. The gateway needs it
	// to build the same jwt.Claims{UserID, TrustLevel} pair the auth service
	// used to build internally — without it, every issued token would claim
	// trust level 0.
	TrustLevel    int32 `protobuf:"varint,8,opt,name=trust_level,json=trustLevel,proto3" json:"trust_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionResponse) Reset() {
	*x = SessionResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionResponse) ProtoMessage() {}

func (x *SessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionResponse.ProtoReflect.Descriptor instead.
func (*SessionResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *SessionResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SessionResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *SessionResponse) GetIsNewUser() bool {
	if x != nil {
		return x.IsNewUser
	}
	return false
}

func (x *SessionResponse) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *SessionResponse) GetProfilePhotoUrl() string {
	if x != nil {
		return x.ProfilePhotoUrl
	}
	return ""
}

func (x *SessionResponse) GetTrustLevel() int32 {
	if x != nil {
		return x.TrustLevel
	}
	return 0
}

type RefreshSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshSessionRequest) Reset() {
	*x = RefreshSessionRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshSessionRequest) ProtoMessage() {}

func (x *RefreshSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshSessionRequest.ProtoReflect.Descriptor instead.
func (*RefreshSessionRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *RefreshSessionRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RevokeSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeSessionRequest) Reset() {
	*x = RevokeSessionRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSessionRequest) ProtoMessage() {}

func (x *RevokeSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeSessionRequest.ProtoReflect.Descriptor instead.
func (*RevokeSessionRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{7}
}

func (x *RevokeSessionRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RevokeSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeSessionResponse) Reset() {
	*x = RevokeSessionResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSessionResponse) ProtoMessage() {}

func (x *RevokeSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeSessionResponse.ProtoReflect.Descriptor instead.
func (*RevokeSessionResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{8}
}

func (x *RevokeSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type StartVerificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // set by the gateway from the verified JWT, never client-supplied
	Purpose       VerificationPurpose    `protobuf:"varint,2,opt,name=purpose,proto3,enum=auth.v1.VerificationPurpose" json:"purpose,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"` // phone number (E.164) or email address to verify
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartVerificationRequest) Reset() {
	*x = StartVerificationRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVerificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVerificationRequest) ProtoMessage() {}

func (x *StartVerificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVerificationRequest.ProtoReflect.Descriptor instead.
func (*StartVerificationRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{9}
}

func (x *StartVerificationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StartVerificationRequest) GetPurpose() VerificationPurpose {
	if x != nil {
		return x.Purpose
	}
	return VerificationPurpose_VERIFICATION_PURPOSE_UNSPECIFIED
}

func (x *StartVerificationRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

// Intentionally near-empty — never echoes the code, or any indication of
// whether target already exists on another account (a user-enumeration
// leak). See backend/ARCHITECTURE.md for the full error-mapping rationale.
type StartVerificationResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ResendAfterSeconds int32                  `protobuf:"varint,1,opt,name=resend_after_seconds,json=resendAfterSeconds,proto3" json:"resend_after_seconds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StartVerificationResponse) Reset() {
	*x = StartVerificationResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVerificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVerificationResponse) ProtoMessage() {}

func (x *StartVerificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVerificationResponse.ProtoReflect.Descriptor instead.
func (*StartVerificationResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{10}
}

func (x *StartVerificationResponse) GetResendAfterSeconds() int32 {
	if x != nil {
		return x.ResendAfterSeconds
	}
	return 0
}

type VerifyCodeRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	UserId  string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Purpose VerificationPurpose    `protobuf:"varint,2,opt,name=purpose,proto3,enum=auth.v1.VerificationPurpose" json:"purpose,omitempty"`
	Target  string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"` // must match what StartVerification was called with
	Code    string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	// company_name is only meaningful for VERIFICATION_PURPOSE_CORPORATE_EMAIL
	// (ADR-019 §3) — the name-vs-domain cross-check against known_companies
	// this verification never had before; ignored for every other purpose.
	// Required in practice for corporate-email verification even though the
	// proto can't enforce that — VerifyCorporateEmailCode rejects an empty
	// value itself.
	CompanyName   string `protobuf:"bytes,5,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyCodeRequest) Reset() {
	*x = VerifyCodeRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCodeRequest) ProtoMessage() {}

func (x *VerifyCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCodeRequest.ProtoReflect.Descriptor instead.
func (*VerifyCodeRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{11}
}

func (x *VerifyCodeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VerifyCodeRequest) GetPurpose() VerificationPurpose {
	if x != nil {
		return x.Purpose
	}
	return VerificationPurpose_VERIFICATION_PURPOSE_UNSPECIFIED
}

func (x *VerifyCodeRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *VerifyCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *VerifyCodeRequest) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

type SubmitPersonalDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LegalName     string                 `protobuf:"bytes,2,opt,name=legal_name,json=legalName,proto3" json:"legal_name,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitPersonalDetailsRequest) Reset() {
	*x = SubmitPersonalDetailsRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitPersonalDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitPersonalDetailsRequest) ProtoMessage() {}

func (x *SubmitPersonalDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitPersonalDetailsRequest.ProtoReflect.Descriptor instead.
func (*SubmitPersonalDetailsRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{12}
}

func (x *SubmitPersonalDetailsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SubmitPersonalDetailsRequest) GetLegalName() string {
	if x != nil {
		return x.LegalName
	}
	return ""
}

func (x *SubmitPersonalDetailsRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // set by the gateway from the verified JWT, never client-supplied
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{13}
}

func (x *GetProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// ProfileResponse is returned only to the authenticated caller about their
// own account (GetProfileRequest.user_id is gateway-set from the verified
// JWT, never client-supplied — see GetProfile's implementation for the
// re-confirmed invariant). Verification Model § 1's "never reveal a user's
// full phone number **to other users**" rule was, before ADR-023, applied
// here as "never to anyone, including the owner" — an over-generalization
// the domain rule never actually required. ADR-023 §4 corrects that: four
// raw fields (phone_number, personal_email, legal_name, address) are now
// included below, visible only to the account's own owner via this one
// self-authenticated endpoint — no other endpoint and no other user ever
// sees them. Work email is a separate, stronger rule (ADR-003: never
// *stored* past the verification round-trip) and stays fully excluded —
// there is no raw work-email field here, for anyone, ever. full_name/
// profile_photo_url are already in SessionResponse but repeated here since
// this is the one endpoint a client can call any time to refresh its whole
// profile view, not just at sign-in.
type ProfileResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	UserId                  string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FullName                string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	ProfilePhotoUrl         string                 `protobuf:"bytes,3,opt,name=profile_photo_url,json=profilePhotoUrl,proto3" json:"profile_photo_url,omitempty"`
	TrustLevel              int32                  `protobuf:"varint,4,opt,name=trust_level,json=trustLevel,proto3" json:"trust_level,omitempty"`
	PhoneVerified           bool                   `protobuf:"varint,5,opt,name=phone_verified,json=phoneVerified,proto3" json:"phone_verified,omitempty"`
	PersonalEmailVerified   bool                   `protobuf:"varint,6,opt,name=personal_email_verified,json=personalEmailVerified,proto3" json:"personal_email_verified,omitempty"`
	PersonalDetailsComplete bool                   `protobuf:"varint,7,opt,name=personal_details_complete,json=personalDetailsComplete,proto3" json:"personal_details_complete,omitempty"`
	CompanyDomain           string                 `protobuf:"bytes,8,opt,name=company_domain,json=companyDomain,proto3" json:"company_domain,omitempty"`
	WorkEmailVerified       bool                   `protobuf:"varint,9,opt,name=work_email_verified,json=workEmailVerified,proto3" json:"work_email_verified,omitempty"`
	// Post-meetup star rating aggregate (ADR-015,
	// docs/02-domain/domain-model.md § Rating) — read here from the same
	// users columns services/meetup writes to after SubmitRating.
	RatingAverage float64 `protobuf:"fixed64,10,opt,name=rating_average,json=ratingAverage,proto3" json:"rating_average,omitempty"`
	RatingCount   int32   `protobuf:"varint,11,opt,name=rating_count,json=ratingCount,proto3" json:"rating_count,omitempty"`
	// Raw PII, self-view only — ADR-023 §4. Empty when unset, same
	// presence-means-verified convention the *_verified booleans already use.
	PhoneNumber   string `protobuf:"bytes,12,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	PersonalEmail string `protobuf:"bytes,13,opt,name=personal_email,json=personalEmail,proto3" json:"personal_email,omitempty"`
	LegalName     string `protobuf:"bytes,14,opt,name=legal_name,json=legalName,proto3" json:"legal_name,omitempty"`
	Address       string `protobuf:"bytes,15,opt,name=address,proto3" json:"address,omitempty"`
	// ADR-002: derived boolean, never the raw linkedin_sub. The client can no
	// longer infer this from trust_level >= 1 — after ADR-002 §2 that is true
	// for every real signup path, LinkedIn or not.
	LinkedinConnected bool `protobuf:"varint,18,opt,name=linkedin_connected,json=linkedinConnected,proto3" json:"linkedin_connected,omitempty"`
	// ADR-002 §3: lets the client render guest chrome and route a guest to
	// signup rather than to the Level 2 checklist, without inferring it from
	// trust_level == 0 (a different question that only coincides today).
	IsGuest bool `protobuf:"varint,16,opt,name=is_guest,json=isGuest,proto3" json:"is_guest,omitempty"`
	// ADR-002 §2: the free-text organisation name, now part of the Level 3
	// condition alongside work_email_verified. Prefills the hosting-unlock
	// page when a company was registered once already.
	CompanyName string `protobuf:"bytes,17,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	// How many meetups this user has actually completed — the profile's
	// "MEETUPS" figure, which was a hardcoded literal on the client until
	// this field existed. Read from auth.users.meetups_completed, a cache the
	// meetup module keeps current (auth/0005), same arrangement as
	// rating_average/rating_count above.
	MeetupsCompleted int32 `protobuf:"varint,19,opt,name=meetups_completed,json=meetupsCompleted,proto3" json:"meetups_completed,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProfileResponse) Reset() {
	*x = ProfileResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileResponse) ProtoMessage() {}

func (x *ProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileResponse.ProtoReflect.Descriptor instead.
func (*ProfileResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{14}
}

func (x *ProfileResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProfileResponse) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *ProfileResponse) GetProfilePhotoUrl() string {
	if x != nil {
		return x.ProfilePhotoUrl
	}
	return ""
}

func (x *ProfileResponse) GetTrustLevel() int32 {
	if x != nil {
		return x.TrustLevel
	}
	return 0
}

func (x *ProfileResponse) GetPhoneVerified() bool {
	if x != nil {
		return x.PhoneVerified
	}
	return false
}

func (x *ProfileResponse) GetPersonalEmailVerified() bool {
	if x != nil {
		return x.PersonalEmailVerified
	}
	return false
}

func (x *ProfileResponse) GetPersonalDetailsComplete() bool {
	if x != nil {
		return x.PersonalDetailsComplete
	}
	return false
}

func (x *ProfileResponse) GetCompanyDomain() string {
	if x != nil {
		return x.CompanyDomain
	}
	return ""
}

func (x *ProfileResponse) GetWorkEmailVerified() bool {
	if x != nil {
		return x.WorkEmailVerified
	}
	return false
}

func (x *ProfileResponse) GetRatingAverage() float64 {
	if x != nil {
		return x.RatingAverage
	}
	return 0
}

func (x *ProfileResponse) GetRatingCount() int32 {
	if x != nil {
		return x.RatingCount
	}
	return 0
}

func (x *ProfileResponse) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *ProfileResponse) GetPersonalEmail() string {
	if x != nil {
		return x.PersonalEmail
	}
	return ""
}

func (x *ProfileResponse) GetLegalName() string {
	if x != nil {
		return x.LegalName
	}
	return ""
}

func (x *ProfileResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ProfileResponse) GetLinkedinConnected() bool {
	if x != nil {
		return x.LinkedinConnected
	}
	return false
}

func (x *ProfileResponse) GetIsGuest() bool {
	if x != nil {
		return x.IsGuest
	}
	return false
}

func (x *ProfileResponse) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *ProfileResponse) GetMeetupsCompleted() int32 {
	if x != nil {
		return x.MeetupsCompleted
	}
	return 0
}

type CompleteProfileSetupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                   // set by the gateway from the verified JWT, never client-supplied
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`             // always required
	CompanyName   string                 `protobuf:"bytes,3,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`    // optional; only meaningful paired with company_email
	CompanyEmail  string                 `protobuf:"bytes,4,opt,name=company_email,json=companyEmail,proto3" json:"company_email,omitempty"` // optional; if set, kicks off corporate-email verification-start (ADR-019 §2)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteProfileSetupRequest) Reset() {
	*x = CompleteProfileSetupRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteProfileSetupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteProfileSetupRequest) ProtoMessage() {}

func (x *CompleteProfileSetupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteProfileSetupRequest.ProtoReflect.Descriptor instead.
func (*CompleteProfileSetupRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{15}
}

func (x *CompleteProfileSetupRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CompleteProfileSetupRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CompleteProfileSetupRequest) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *CompleteProfileSetupRequest) GetCompanyEmail() string {
	if x != nil {
		return x.CompanyEmail
	}
	return ""
}

// 50km geo-visibility (ADR-021 §4).
type UpdateLastKnownLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // set by the gateway from the verified JWT
	Lat           float64                `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,3,opt,name=lng,proto3" json:"lng,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLastKnownLocationRequest) Reset() {
	*x = UpdateLastKnownLocationRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLastKnownLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLastKnownLocationRequest) ProtoMessage() {}

func (x *UpdateLastKnownLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLastKnownLocationRequest.ProtoReflect.Descriptor instead.
func (*UpdateLastKnownLocationRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateLastKnownLocationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateLastKnownLocationRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *UpdateLastKnownLocationRequest) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

type UpdateLastKnownLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLastKnownLocationResponse) Reset() {
	*x = UpdateLastKnownLocationResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLastKnownLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLastKnownLocationResponse) ProtoMessage() {}

func (x *UpdateLastKnownLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLastKnownLocationResponse.ProtoReflect.Descriptor instead.
func (*UpdateLastKnownLocationResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateLastKnownLocationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Minimal real SOS + trusted contacts (ADR-026).
type AddTrustedContactRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // set by the gateway from the verified JWT
	Name   string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// At least one of phone_number/email is required — enforced server-side,
	// mirroring the DB CHECK constraint (migration 0009).
	PhoneNumber string `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Email       string `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	// ADR-003 — set by the gateway from the verified JWT's trust_level claim,
	// never a client-supplied value. AddTrustedContact/TriggerSOS require
	// Level 2, the same floor as joining a meetup.
	CallerTrustLevel int32 `protobuf:"varint,5,opt,name=caller_trust_level,json=callerTrustLevel,proto3" json:"caller_trust_level,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AddTrustedContactRequest) Reset() {
	*x = AddTrustedContactRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTrustedContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTrustedContactRequest) ProtoMessage() {}

func (x *AddTrustedContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTrustedContactRequest.ProtoReflect.Descriptor instead.
func (*AddTrustedContactRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{18}
}

func (x *AddTrustedContactRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddTrustedContactRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddTrustedContactRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *AddTrustedContactRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AddTrustedContactRequest) GetCallerTrustLevel() int32 {
	if x != nil {
		return x.CallerTrustLevel
	}
	return 0
}

type TrustedContactResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PhoneNumber          string                 `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Email                string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAtUnixSeconds int64                  `protobuf:"varint,5,opt,name=created_at_unix_seconds,json=createdAtUnixSeconds,proto3" json:"created_at_unix_seconds,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TrustedContactResponse) Reset() {
	*x = TrustedContactResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrustedContactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrustedContactResponse) ProtoMessage() {}

func (x *TrustedContactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrustedContactResponse.ProtoReflect.Descriptor instead.
func (*TrustedContactResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{19}
}

func (x *TrustedContactResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TrustedContactResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TrustedContactResponse) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *TrustedContactResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *TrustedContactResponse) GetCreatedAtUnixSeconds() int64 {
	if x != nil {
		return x.CreatedAtUnixSeconds
	}
	return 0
}

type ListTrustedContactsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // set by the gateway from the verified JWT
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTrustedContactsRequest) Reset() {
	*x = ListTrustedContactsRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTrustedContactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTrustedContactsRequest) ProtoMessage() {}

func (x *ListTrustedContactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTrustedContactsRequest.ProtoReflect.Descriptor instead.
func (*ListTrustedContactsRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{20}
}

func (x *ListTrustedContactsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListTrustedContactsResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Contacts      []*TrustedContactResponse `protobuf:"bytes,1,rep,name=contacts,proto3" json:"contacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTrustedContactsResponse) Reset() {
	*x = ListTrustedContactsResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTrustedContactsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTrustedContactsResponse) ProtoMessage() {}

func (x *ListTrustedContactsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTrustedContactsResponse.ProtoReflect.Descriptor instead.
func (*ListTrustedContactsResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{21}
}

func (x *ListTrustedContactsResponse) GetContacts() []*TrustedContactResponse {
	if x != nil {
		return x.Contacts
	}
	return nil
}

type RemoveTrustedContactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // set by the gateway from the verified JWT
	ContactId     string                 `protobuf:"bytes,2,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTrustedContactRequest) Reset() {
	*x = RemoveTrustedContactRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTrustedContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTrustedContactRequest) ProtoMessage() {}

func (x *RemoveTrustedContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTrustedContactRequest.ProtoReflect.Descriptor instead.
func (*RemoveTrustedContactRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{22}
}

func (x *RemoveTrustedContactRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RemoveTrustedContactRequest) GetContactId() string {
	if x != nil {
		return x.ContactId
	}
	return ""
}

type RemoveTrustedContactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTrustedContactResponse) Reset() {
	*x = RemoveTrustedContactResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTrustedContactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTrustedContactResponse) ProtoMessage() {}

func (x *RemoveTrustedContactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTrustedContactResponse.ProtoReflect.Descriptor instead.
func (*RemoveTrustedContactResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{23}
}

func (x *RemoveTrustedContactResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type TriggerSOSRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                         // set by the gateway from the verified JWT
	ContextMessage string                 `protobuf:"bytes,2,opt,name=context_message,json=contextMessage,proto3" json:"context_message,omitempty"` // optional — meetup title/location/time, or empty
	Latitude       float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude      float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	// ADR-003 — see AddTrustedContactRequest.caller_trust_level.
	CallerTrustLevel int32 `protobuf:"varint,5,opt,name=caller_trust_level,json=callerTrustLevel,proto3" json:"caller_trust_level,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TriggerSOSRequest) Reset() {
	*x = TriggerSOSRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerSOSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerSOSRequest) ProtoMessage() {}

func (x *TriggerSOSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerSOSRequest.ProtoReflect.Descriptor instead.
func (*TriggerSOSRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{24}
}

func (x *TriggerSOSRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TriggerSOSRequest) GetContextMessage() string {
	if x != nil {
		return x.ContextMessage
	}
	return ""
}

func (x *TriggerSOSRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *TriggerSOSRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *TriggerSOSRequest) GetCallerTrustLevel() int32 {
	if x != nil {
		return x.CallerTrustLevel
	}
	return 0
}

type TriggerSOSResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// How many of the caller's trusted contacts were actually alerted —
	// individual send failures don't fail the whole call (ADR-026 §4), so
	// this may be less than the caller's total contact count.
	ContactsNotified int32 `protobuf:"varint,1,opt,name=contacts_notified,json=contactsNotified,proto3" json:"contacts_notified,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TriggerSOSResponse) Reset() {
	*x = TriggerSOSResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerSOSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerSOSResponse) ProtoMessage() {}

func (x *TriggerSOSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerSOSResponse.ProtoReflect.Descriptor instead.
func (*TriggerSOSResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{25}
}

func (x *TriggerSOSResponse) GetContactsNotified() int32 {
	if x != nil {
		return x.ContactsNotified
	}
	return 0
}

var File_auth_v1_auth_proto protoreflect.FileDescriptor

const file_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x12auth/v1/auth.proto\x12\aauth.v1\"\xc0\x01\n" +
	"\x1eCompleteFederatedSignupRequest\x12:\n" +
	"\bprovider\x18\x01 \x01(\x0e2\x1e.auth.v1.IdentityProviderProtoR\bprovider\x12\x19\n" +
	"\bid_token\x18\x02 \x01(\tR\aidToken\x121\n" +
	"\x15age_confirmed_over_18\x18\x03 \x01(\bR\x12ageConfirmedOver18\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\tR\x05nonce\"\xbd\x01\n" +
	"!CompleteLinkedInOnboardingRequest\x12-\n" +
	"\x12authorization_code\x18\x01 \x01(\tR\x11authorizationCode\x12!\n" +
	"\fredirect_uri\x18\x02 \x01(\tR\vredirectUri\x121\n" +
	"\x15age_confirmed_over_18\x18\x03 \x01(\bR\x12ageConfirmedOver18J\x04\b\x04\x10\x05R\rpkce_verifier\"\xed\x01\n" +
	"\x13LinkIdentityRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12:\n" +
	"\bprovider\x18\x02 \x01(\x0e2\x1e.auth.v1.IdentityProviderProtoR\bprovider\x12\x19\n" +
	"\bid_token\x18\x03 \x01(\tR\aidToken\x12-\n" +
	"\x12authorization_code\x18\x04 \x01(\tR\x11authorizationCode\x12!\n" +
	"\fredirect_uri\x18\x05 \x01(\tR\vredirectUri\x12\x14\n" +
	"\x05nonce\x18\x06 \x01(\tR\x05nonce\"G\n" +
	"\x12GuestSignupRequest\x121\n" +
	"\x15age_confirmed_over_18\x18\x01 \x01(\bR\x12ageConfirmedOver18\"\x89\x01\n" +
	"\x1aCompleteEmailSignupRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x121\n" +
	"\x15age_confirmed_over_18\x18\x04 \x01(\bR\x12ageConfirmedOver18J\x04\b\x03\x10\x04R\bpassword\"\x94\x02\n" +
	"\x0fSessionResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x12\x1e\n" +
	"\vis_new_user\x18\x05 \x01(\bR\tisNewUser\x12\x1b\n" +
	"\tfull_name\x18\x06 \x01(\tR\bfullName\x12*\n" +
	"\x11profile_photo_url\x18\a \x01(\tR\x0fprofilePhotoUrl\x12\x1f\n" +
	"\vtrust_level\x18\b \x01(\x05R\n" +
	"trustLevelJ\x04\b\x02\x10\x03J\x04\b\x04\x10\x05R\faccess_tokenR\x1faccess_token_expires_in_seconds\"<\n" +
	"\x15RefreshSessionRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\";\n" +
	"\x14RevokeSessionRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"1\n" +
	"\x15RevokeSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x83\x01\n" +
	"\x18StartVerificationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x126\n" +
	"\apurpose\x18\x02 \x01(\x0e2\x1c.auth.v1.VerificationPurposeR\apurpose\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\"M\n" +
	"\x19StartVerificationResponse\x120\n" +
	"\x14resend_after_seconds\x18\x01 \x01(\x05R\x12resendAfterSeconds\"\xb3\x01\n" +
	"\x11VerifyCodeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x126\n" +
	"\apurpose\x18\x02 \x01(\x0e2\x1c.auth.v1.VerificationPurposeR\apurpose\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x12!\n" +
	"\fcompany_name\x18\x05 \x01(\tR\vcompanyName\"p\n" +
	"\x1cSubmitPersonalDetailsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"legal_name\x18\x02 \x01(\tR\tlegalName\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\",\n" +
	"\x11GetProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xed\x05\n" +
	"\x0fProfileResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12*\n" +
	"\x11profile_photo_url\x18\x03 \x01(\tR\x0fprofilePhotoUrl\x12\x1f\n" +
	"\vtrust_level\x18\x04 \x01(\x05R\n" +
	"trustLevel\x12%\n" +
	"\x0ephone_verified\x18\x05 \x01(\bR\rphoneVerified\x126\n" +
	"\x17personal_email_verified\x18\x06 \x01(\bR\x15personalEmailVerified\x12:\n" +
	"\x19personal_details_complete\x18\a \x01(\bR\x17personalDetailsComplete\x12%\n" +
	"\x0ecompany_domain\x18\b \x01(\tR\rcompanyDomain\x12.\n" +
	"\x13work_email_verified\x18\t \x01(\bR\x11workEmailVerified\x12%\n" +
	"\x0erating_average\x18\n" +
	" \x01(\x01R\rratingAverage\x12!\n" +
	"\frating_count\x18\v \x01(\x05R\vratingCount\x12!\n" +
	"\fphone_number\x18\f \x01(\tR\vphoneNumber\x12%\n" +
	"\x0epersonal_email\x18\r \x01(\tR\rpersonalEmail\x12\x1d\n" +
	"\n" +
	"legal_name\x18\x0e \x01(\tR\tlegalName\x12\x18\n" +
	"\aaddress\x18\x0f \x01(\tR\aaddress\x12-\n" +
	"\x12linkedin_connected\x18\x12 \x01(\bR\x11linkedinConnected\x12\x19\n" +
	"\bis_guest\x18\x10 \x01(\bR\aisGuest\x12!\n" +
	"\fcompany_name\x18\x11 \x01(\tR\vcompanyName\x12+\n" +
	"\x11meetups_completed\x18\x13 \x01(\x05R\x10meetupsCompleted\"\x9b\x01\n" +
	"\x1bCompleteProfileSetupRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12!\n" +
	"\fcompany_name\x18\x03 \x01(\tR\vcompanyName\x12#\n" +
	"\rcompany_email\x18\x04 \x01(\tR\fcompanyEmail\"]\n" +
	"\x1eUpdateLastKnownLocationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x03 \x01(\x01R\x03lng\";\n" +
	"\x1fUpdateLastKnownLocationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xae\x01\n" +
	"\x18AddTrustedContactRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fphone_number\x18\x03 \x01(\tR\vphoneNumber\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12,\n" +
	"\x12caller_trust_level\x18\x05 \x01(\x05R\x10callerTrustLevel\"\xac\x01\n" +
	"\x16TrustedContactResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fphone_number\x18\x03 \x01(\tR\vphoneNumber\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x125\n" +
	"\x17created_at_unix_seconds\x18\x05 \x01(\x03R\x14createdAtUnixSeconds\"5\n" +
	"\x1aListTrustedContactsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"Z\n" +
	"\x1bListTrustedContactsResponse\x12;\n" +
	"\bcontacts\x18\x01 \x03(\v2\x1f.auth.v1.TrustedContactResponseR\bcontacts\"U\n" +
	"\x1bRemoveTrustedContactRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"contact_id\x18\x02 \x01(\tR\tcontactId\"8\n" +
	"\x1cRemoveTrustedContactResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xbd\x01\n" +
	"\x11TriggerSOSRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0fcontext_message\x18\x02 \x01(\tR\x0econtextMessage\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\x12,\n" +
	"\x12caller_trust_level\x18\x05 \x01(\x05R\x10callerTrustLevel\"A\n" +
	"\x12TriggerSOSResponse\x12+\n" +
	"\x11contacts_notified\x18\x01 \x01(\x05R\x10contactsNotified*\x95\x01\n" +
	"\x15IdentityProviderProto\x12!\n" +
	"\x1dIDENTITY_PROVIDER_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17IDENTITY_PROVIDER_APPLE\x10\x01\x12\x1c\n" +
	"\x18IDENTITY_PROVIDER_GOOGLE\x10\x02\x12\x1e\n" +
	"\x1aIDENTITY_PROVIDER_LINKEDIN\x10\x03*\xfb\x01\n" +
	"\x13VerificationPurpose\x12$\n" +
	" VERIFICATION_PURPOSE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aVERIFICATION_PURPOSE_PHONE\x10\x01\x12'\n" +
	"#VERIFICATION_PURPOSE_PERSONAL_EMAIL\x10\x02\x12(\n" +
	"$VERIFICATION_PURPOSE_CORPORATE_EMAIL\x10\x03\x12%\n" +
	"!VERIFICATION_PURPOSE_EMAIL_SIGNUP\x10\x04\x12$\n" +
	" VERIFICATION_PURPOSE_EMAIL_LOGIN\x10\x052\xbb\x10\n" +
	"\vAuthService\x12\\\n" +
	"\x17CompleteFederatedSignup\x12'.auth.v1.CompleteFederatedSignupRequest\x1a\x18.auth.v1.SessionResponse\x12b\n" +
	"\x1aCompleteLinkedInOnboarding\x12*.auth.v1.CompleteLinkedInOnboardingRequest\x1a\x18.auth.v1.SessionResponse\x12F\n" +
	"\fLinkIdentity\x12\x1c.auth.v1.LinkIdentityRequest\x1a\x18.auth.v1.SessionResponse\x12Y\n" +
	"\x10StartEmailSignup\x12!.auth.v1.StartVerificationRequest\x1a\".auth.v1.StartVerificationResponse\x12T\n" +
	"\x13CompleteEmailSignup\x12#.auth.v1.CompleteEmailSignupRequest\x1a\x18.auth.v1.SessionResponse\x12D\n" +
	"\vGuestSignup\x12\x1b.auth.v1.GuestSignupRequest\x1a\x18.auth.v1.SessionResponse\x12X\n" +
	"\x0fStartEmailLogin\x12!.auth.v1.StartVerificationRequest\x1a\".auth.v1.StartVerificationResponse\x12J\n" +
	"\x12CompleteEmailLogin\x12\x1a.auth.v1.VerifyCodeRequest\x1a\x18.auth.v1.SessionResponse\x12J\n" +
	"\x0eRefreshSession\x12\x1e.auth.v1.RefreshSessionRequest\x1a\x18.auth.v1.SessionResponse\x12N\n" +
	"\rRevokeSession\x12\x1d.auth.v1.RevokeSessionRequest\x1a\x1e.auth.v1.RevokeSessionResponse\x12_\n" +
	"\x16StartPhoneVerification\x12!.auth.v1.StartVerificationRequest\x1a\".auth.v1.StartVerificationResponse\x12G\n" +
	"\x0fVerifyPhoneCode\x12\x1a.auth.v1.VerifyCodeRequest\x1a\x18.auth.v1.SessionResponse\x12g\n" +
	"\x1eStartPersonalEmailVerification\x12!.auth.v1.StartVerificationRequest\x1a\".auth.v1.StartVerificationResponse\x12O\n" +
	"\x17VerifyPersonalEmailCode\x12\x1a.auth.v1.VerifyCodeRequest\x1a\x18.auth.v1.SessionResponse\x12X\n" +
	"\x15SubmitPersonalDetails\x12%.auth.v1.SubmitPersonalDetailsRequest\x1a\x18.auth.v1.SessionResponse\x12h\n" +
	"\x1fStartCorporateEmailVerification\x12!.auth.v1.StartVerificationRequest\x1a\".auth.v1.StartVerificationResponse\x12P\n" +
	"\x18VerifyCorporateEmailCode\x12\x1a.auth.v1.VerifyCodeRequest\x1a\x18.auth.v1.SessionResponse\x12B\n" +
	"\n" +
	"GetProfile\x12\x1a.auth.v1.GetProfileRequest\x1a\x18.auth.v1.ProfileResponse\x12V\n" +
	"\x14CompleteProfileSetup\x12$.auth.v1.CompleteProfileSetupRequest\x1a\x18.auth.v1.ProfileResponse\x12l\n" +
	"\x17UpdateLastKnownLocation\x12'.auth.v1.UpdateLastKnownLocationRequest\x1a(.auth.v1.UpdateLastKnownLocationResponse\x12W\n" +
	"\x11AddTrustedContact\x12!.auth.v1.AddTrustedContactRequest\x1a\x1f.auth.v1.TrustedContactResponse\x12`\n" +
	"\x13ListTrustedContacts\x12#.auth.v1.ListTrustedContactsRequest\x1a$.auth.v1.ListTrustedContactsResponse\x12c\n" +
	"\x14RemoveTrustedContact\x12$.auth.v1.RemoveTrustedContactRequest\x1a%.auth.v1.RemoveTrustedContactResponse\x12E\n" +
	"\n" +
	"TriggerSOS\x12\x1a.auth.v1.TriggerSOSRequest\x1a\x1b.auth.v1.TriggerSOSResponseBEZCprofessional-meetups-monolith/backend/internal/proto/auth/v1;authv1b\x06proto3"

var (
	file_auth_v1_auth_proto_rawDescOnce sync.Once
	file_auth_v1_auth_proto_rawDescData []byte
)

func file_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_v1_auth_proto_rawDesc), len(file_auth_v1_auth_proto_rawDesc)))
	})
	return file_auth_v1_auth_proto_rawDescData
}

var file_auth_v1_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_auth_v1_auth_proto_goTypes = []any{
	(IdentityProviderProto)(0),                // 0: auth.v1.IdentityProviderProto
	(VerificationPurpose)(0),                  // 1: auth.v1.VerificationPurpose
	(*CompleteFederatedSignupRequest)(nil),    // 2: auth.v1.CompleteFederatedSignupRequest
	(*CompleteLinkedInOnboardingRequest)(nil), // 3: auth.v1.CompleteLinkedInOnboardingRequest
	(*LinkIdentityRequest)(nil),               // 4: auth.v1.LinkIdentityRequest
	(*GuestSignupRequest)(nil),                // 5: auth.v1.GuestSignupRequest
	(*CompleteEmailSignupRequest)(nil),        // 6: auth.v1.CompleteEmailSignupRequest
	(*SessionResponse)(nil),                   // 7: auth.v1.SessionResponse
	(*RefreshSessionRequest)(nil),             // 8: auth.v1.RefreshSessionRequest
	(*RevokeSessionRequest)(nil),              // 9: auth.v1.RevokeSessionRequest
	(*RevokeSessionResponse)(nil),             // 10: auth.v1.RevokeSessionResponse
	(*StartVerificationRequest)(nil),          // 11: auth.v1.StartVerificationRequest
	(*StartVerificationResponse)(nil),         // 12: auth.v1.StartVerificationResponse
	(*VerifyCodeRequest)(nil),                 // 13: auth.v1.VerifyCodeRequest
	(*SubmitPersonalDetailsRequest)(nil),      // 14: auth.v1.SubmitPersonalDetailsRequest
	(*GetProfileRequest)(nil),                 // 15: auth.v1.GetProfileRequest
	(*ProfileResponse)(nil),                   // 16: auth.v1.ProfileResponse
	(*CompleteProfileSetupRequest)(nil),       // 17: auth.v1.CompleteProfileSetupRequest
	(*UpdateLastKnownLocationRequest)(nil),    // 18: auth.v1.UpdateLastKnownLocationRequest
	(*UpdateLastKnownLocationResponse)(nil),   // 19: auth.v1.UpdateLastKnownLocationResponse
	(*AddTrustedContactRequest)(nil),          // 20: auth.v1.AddTrustedContactRequest
	(*TrustedContactResponse)(nil),            // 21: auth.v1.TrustedContactResponse
	(*ListTrustedContactsRequest)(nil),        // 22: auth.v1.ListTrustedContactsRequest
	(*ListTrustedContactsResponse)(nil),       // 23: auth.v1.ListTrustedContactsResponse
	(*RemoveTrustedContactRequest)(nil),       // 24: auth.v1.RemoveTrustedContactRequest
	(*RemoveTrustedContactResponse)(nil),      // 25: auth.v1.RemoveTrustedContactResponse
	(*TriggerSOSRequest)(nil),                 // 26: auth.v1.TriggerSOSRequest
	(*TriggerSOSResponse)(nil),                // 27: auth.v1.TriggerSOSResponse
}
var file_auth_v1_auth_proto_depIdxs = []int32{
	0,  // 0: auth.v1.CompleteFederatedSignupRequest.provider:type_name -> auth.v1.IdentityProviderProto
	0,  // 1: auth.v1.LinkIdentityRequest.provider:type_name -> auth.v1.IdentityProviderProto
	1,  // 2: auth.v1.StartVerificationRequest.purpose:type_name -> auth.v1.VerificationPurpose
	1,  // 3: auth.v1.VerifyCodeRequest.purpose:type_name -> auth.v1.VerificationPurpose
	21, // 4: auth.v1.ListTrustedContactsResponse.contacts:type_name -> auth.v1.TrustedContactResponse
	2,  // 5: auth.v1.AuthService.CompleteFederatedSignup:input_type -> auth.v1.CompleteFederatedSignupRequest
	3,  // 6: auth.v1.AuthService.CompleteLinkedInOnboarding:input_type -> auth.v1.CompleteLinkedInOnboardingRequest
	4,  // 7: auth.v1.AuthService.LinkIdentity:input_type -> auth.v1.LinkIdentityRequest
	11, // 8: auth.v1.AuthService.StartEmailSignup:input_type -> auth.v1.StartVerificationRequest
	6,  // 9: auth.v1.AuthService.CompleteEmailSignup:input_type -> auth.v1.CompleteEmailSignupRequest
	5,  // 10: auth.v1.AuthService.GuestSignup:input_type -> auth.v1.GuestSignupRequest
	11, // 11: auth.v1.AuthService.StartEmailLogin:input_type -> auth.v1.StartVerificationRequest
	13, // 12: auth.v1.AuthService.CompleteEmailLogin:input_type -> auth.v1.VerifyCodeRequest
	8,  // 13: auth.v1.AuthService.RefreshSession:input_type -> auth.v1.RefreshSessionRequest
	9,  // 14: auth.v1.AuthService.RevokeSession:input_type -> auth.v1.RevokeSessionRequest
	11, // 15: auth.v1.AuthService.StartPhoneVerification:input_type -> auth.v1.StartVerificationRequest
	13, // 16: auth.v1.AuthService.VerifyPhoneCode:input_type -> auth.v1.VerifyCodeRequest
	11, // 17: auth.v1.AuthService.StartPersonalEmailVerification:input_type -> auth.v1.StartVerificationRequest
	13, // 18: auth.v1.AuthService.VerifyPersonalEmailCode:input_type -> auth.v1.VerifyCodeRequest
	14, // 19: auth.v1.AuthService.SubmitPersonalDetails:input_type -> auth.v1.SubmitPersonalDetailsRequest
	11, // 20: auth.v1.AuthService.StartCorporateEmailVerification:input_type -> auth.v1.StartVerificationRequest
	13, // 21: auth.v1.AuthService.VerifyCorporateEmailCode:input_type -> auth.v1.VerifyCodeRequest
	15, // 22: auth.v1.AuthService.GetProfile:input_type -> auth.v1.GetProfileRequest
	17, // 23: auth.v1.AuthService.CompleteProfileSetup:input_type -> auth.v1.CompleteProfileSetupRequest
	18, // 24: auth.v1.AuthService.UpdateLastKnownLocation:input_type -> auth.v1.UpdateLastKnownLocationRequest
	20, // 25: auth.v1.AuthService.AddTrustedContact:input_type -> auth.v1.AddTrustedContactRequest
	22, // 26: auth.v1.AuthService.ListTrustedContacts:input_type -> auth.v1.ListTrustedContactsRequest
	24, // 27: auth.v1.AuthService.RemoveTrustedContact:input_type -> auth.v1.RemoveTrustedContactRequest
	26, // 28: auth.v1.AuthService.TriggerSOS:input_type -> auth.v1.TriggerSOSRequest
	7,  // 29: auth.v1.AuthService.CompleteFederatedSignup:output_type -> auth.v1.SessionResponse
	7,  // 30: auth.v1.AuthService.CompleteLinkedInOnboarding:output_type -> auth.v1.SessionResponse
	7,  // 31: auth.v1.AuthService.LinkIdentity:output_type -> auth.v1.SessionResponse
	12, // 32: auth.v1.AuthService.StartEmailSignup:output_type -> auth.v1.StartVerificationResponse
	7,  // 33: auth.v1.AuthService.CompleteEmailSignup:output_type -> auth.v1.SessionResponse
	7,  // 34: auth.v1.AuthService.GuestSignup:output_type -> auth.v1.SessionResponse
	12, // 35: auth.v1.AuthService.StartEmailLogin:output_type -> auth.v1.StartVerificationResponse
	7,  // 36: auth.v1.AuthService.CompleteEmailLogin:output_type -> auth.v1.SessionResponse
	7,  // 37: auth.v1.AuthService.RefreshSession:output_type -> auth.v1.SessionResponse
	10, // 38: auth.v1.AuthService.RevokeSession:output_type -> auth.v1.RevokeSessionResponse
	12, // 39: auth.v1.AuthService.StartPhoneVerification:output_type -> auth.v1.StartVerificationResponse
	7,  // 40: auth.v1.AuthService.VerifyPhoneCode:output_type -> auth.v1.SessionResponse
	12, // 41: auth.v1.AuthService.StartPersonalEmailVerification:output_type -> auth.v1.StartVerificationResponse
	7,  // 42: auth.v1.AuthService.VerifyPersonalEmailCode:output_type -> auth.v1.SessionResponse
	7,  // 43: auth.v1.AuthService.SubmitPersonalDetails:output_type -> auth.v1.SessionResponse
	12, // 44: auth.v1.AuthService.StartCorporateEmailVerification:output_type -> auth.v1.StartVerificationResponse
	7,  // 45: auth.v1.AuthService.VerifyCorporateEmailCode:output_type -> auth.v1.SessionResponse
	16, // 46: auth.v1.AuthService.GetProfile:output_type -> auth.v1.ProfileResponse
	16, // 47: auth.v1.AuthService.CompleteProfileSetup:output_type -> auth.v1.ProfileResponse
	19, // 48: auth.v1.AuthService.UpdateLastKnownLocation:output_type -> auth.v1.UpdateLastKnownLocationResponse
	21, // 49: auth.v1.AuthService.AddTrustedContact:output_type -> auth.v1.TrustedContactResponse
	23, // 50: auth.v1.AuthService.ListTrustedContacts:output_type -> auth.v1.ListTrustedContactsResponse
	25, // 51: auth.v1.AuthService.RemoveTrustedContact:output_type -> auth.v1.RemoveTrustedContactResponse
	27, // 52: auth.v1.AuthService.TriggerSOS:output_type -> auth.v1.TriggerSOSResponse
	29, // [29:53] is the sub-list for method output_type
	5,  // [5:29] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_auth_v1_auth_proto_init() }
func file_auth_v1_auth_proto_init() {
	if File_auth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_auth_proto_rawDesc), len(file_auth_v1_auth_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_auth_v1_auth_proto_depIdxs,
		EnumInfos:         file_auth_v1_auth_proto_enumTypes,
		MessageInfos:      file_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_auth_v1_auth_proto = out.File
	file_auth_v1_auth_proto_goTypes = nil
	file_auth_v1_auth_proto_depIdxs = nil
}
